Lotto/step1 제출입니다. !
sosow0212/2024-mju-mentoring-spring-2 pull request #10
Opened 2024-08-02 15:55 UTC by moonwhistle

8/3 제출

* 이번 미션을 하며 정말 많은 지식들이 머리에 들어온 것 같고 아직도 헷갈리는게 많은 것 같습니다... 
* 뭔가 제대로된 스프링을 향해 나아가고 있는 것 같아서 뿌듯하다는 생각이 듭니다!
* API 문서를 작성하였고, HTTP RESTFul에 대해 학습하였으며 JPA에 관해서도 학습 진행하였습니다.
* 데베에서 꺼내오는 코드를 처음 써본 것 같은데 이러한 방식으로 작성하는 것이 맞는지 잘 모르겠습니다!
* dto에서 entity로 변환하는 메서드를 사용하여도 되는지 궁금합니다 !

## API

1. 사용자 등록시 이름과 소유 금액을 함께 저장하는 기능.
   * endPoint : [POST, /create]
   * 설명 : 이름, 소유 금액 저장
   * Exception : 없음
   * request :
     {
     "name": "juna",
     "money": 5000
     }
   * response : 없음
   
* 작성 방식
  * 사용자마다 id(기본키)를 가지게 하였음 => 동명이인 방지
  * 기본키 identity 전략을 사용.

2. 로또를 n장 구매하는 기능. (로또 추가 구매 기능 포함.) - 이때 로또 당첨 번호도 같이 생성 후 비교.
   * endPoint : [POST, /buy]
   * 설명 : 로또 구매, 구매 시점에 랜덤으로 번호 발급, 로또 당첨 번호도 같이 생성 및 저장(저장 시 당첨 여부 계산)
   * Exception : 돈 보다 많은 로또 구매할 경우, 
   * request :
     {
     "userId": 1,
     "count": 3
     }
   * response : 없음

* 작성 방식
    * LottoEntity에 User를 참조하여 어떤 유저가 몇 장 샀는지 저장 가능하게 하였음.
    * 로또 당첨 번호도 같이 생성해준 이유는, 도메인에 로또 당첨 번호 생성해서 비교하는 메서드 구현하면 너무 복잡해질 것 같아서 로또 당첨 번호 엔티티와 메서드를 따로 만들었음.
    * 로또 번호를 생성하는 동시에 당첨 번호도 같이 생성하여 비교하게 하였음 => 당첨 여부, 유저 당첨 금액 같이 update

3. 특정 사용자가 지금까지 뽑은 모든 로또의 번호와 당첨 여부를 함께 확인하는 기능.
    * endPoint : [GET, /user/{id}/lottos] @PathVariable
    * 설명 : 특정 사용자 로또 정보 조회
    * Exception : 로또 사지 않았는데 조회할 경우.
    * request : x 
    * response :
      [
      {
      "lottoNumber": "[32, 20, 45, 30, 19, 7]",
      "win": false
      },
      {
      "lottoNumber": "[4, 31, 18, 29, 27, 13]",
      "win": false
      }
      ]
   
* 작성 방식
  * LottoRepository에 List<LottoEntity-> findAllByUserId(Long userId); 메서드 만들어서 로또 엔티티 다 가져올 수 있게 구현.
  * 가져온 데이터를 LottoResponse에 담아 컨트롤러에 전달하는 방식
  * 당첨 여부라 하였으니, boolean 값으로 받았음.

4. 특정 사용자가 지금까지 뽑은 특정 로또의 번호와 당첨 여부를 확인하는 기능.
    * endPoint : [GET, /user/{id}/lottos?order=1] @PathVariable, @RequestParam
    * 설명 : 특정 사용자의 특정 로또 정보 조회
    * Exception : 로또 사지 않았는데 조회할 경우, 3개 샀는데 4번 째 로또 고르는 경우
    * request : x
    * response :
      {
      "lottoNumber": "[32, 20, 45, 30, 19, 7]",
      "win": false
      }
   
* 작성 방식
  * API 3번(특정 사용자 모든 로또 조회) 메서드 재활용.
  * @PathVariable 로 특정 사용자 조회 후, @RequestParam 으로 몇 번째 로또 받을 것인지 구현.

5. 모든 사용자의 구매 로또 개수와 당첨 금액을 확인하는 기능.
   * endPoint : [GET, /users] 
   * 설명 : 모든 사용자의 로또, 당첨 금액 조회.
   * Exception : 유저 없을 경우.
   * request : x
   * response :
     [
     {
     "name": "juna",
     "lottoTicket": 2,
     "winning": 0
     }
     ]

* 작성 방식
  * findAll() 메서드 사용하여 모든 유저 끌어옴
  
  
  

## RestFul 과 HTTP 메서드

### REST 란? 
* REST(Representational State Transfer) 네트워크 아키텍처 원칙을 기반으로 한 웹 서비스 디자인 방식이다. REST 는 리소스를 기반으로 한 설계 철학을 따르며, 이러한 리소스는 URI을 통해 식별된다. --> 쉽게 말해, REST는 네트워크 상에서 Client와 Server 사이의 통신 방식 중 하나이고, 이미지나 텍스트 같은 자원들을 JSON 혹은 XML 형식으로 URL 통해 주고 받는 것.

#### REST 의 주요원칙
* Client–server 구조 : 클라이언트와 서버는 서로 독립적이어야 하며, 클라이언트는 url만 알아야 한다. 그리고, 클라이언트와 서버의 인터페이스가 변경되지 않는 한, 이 둘은 독립적으로 개발되거나 대체될 수 있게 유지해야한다. (관심사의 명확한 분리).
* Stateless(무상태성) : 각 요청은 독립적이며, HTTP 요청에 대한 어떤 것도 저장하지 않는다.(필수적인 것 빼고) 클라이언트의 모든 정보는 요청에 포함되어야 한다.
* Cacheable : 서버는 Response cache-control 헤더에 해당 요청이 캐싱이 가능한 지에 대한 여부를 제공해야 한다. 클라이언트는 Response를 캐싱하여 서버와 클라이언트 간의 상호작용을 줄이고, 성능과 서버 가용성을 늘릴 수 있음.
* Layered system(다중 계층): REST는 다중 계층 구조를 가질 수 있도록 허용한다.(API 서버와 데베 서버 따로 두는 느낌)  레이어는 자기와 통신하는 컴포넌트 외 레이어에 대해서는 정보를 얻을 수 없다.
* Code on demand (optional): 서버가 클라이언트에서 실행시킬 수 있는 로직을 전송하여 클라이언트의 기능을 확장시킬 수 있다. 이를 통해 클라이언트가 사전에 구현해야하는 기능의 수를 줄여 간소화시킬 수 있다.
* Uniform interface(일관된 인터페이스) : 
  * identification of resources : 요청 시 개별 자원을 식별할 수 있어야함
  * manipulation of resources through representations : 어떤 자원에 대헤 작업하기 위한 적절한 표현과 메타데이터를 충분히 갖추고 있다면, 서버는 해당 자원을 변경, 삭제할 수 있는 정보를 가지고 있단 의미
  * self-descriptive messages : 자신을 어떻게 처리해야하는지 정보를 포함해야함
  * hypermedia as the engine of application state : 단순히 결과 뿐만이 아니라 결과에 대한 정보를 포함해야 함
    
### HTTP 메서드란? 
* 클라이언트와 서버 간의 통신에서 사용된다. 각 메서드는 특정한 작업을 수행하며, RESTful 서비스에서 리소스 조작을 위해 주로 사용됨. HTTP 메서드는 CRUD(Create, Read, Update, Delete) 기능을 제공.

1. GET - 서버에서 리소스를 조회. 
   * 안전성: 서버 상태를 변경하지 않는다.
   * 멱등성: 동일한 요청을 여러 번 수행해도 결과가 동일.
   * 캐싱: GET 요청은 캐싱할 수 있다.

2. POST - 서버에 새로운 리소스를 생성. 
   * 안전성: 서버 상태를 변경.
   * 멱등성: 동일한 요청을 여러 번 수행하면 여러 개의 리소스가 생성될 수 있음.
   * 캐싱: 일반적으로 캐싱하지 않음.

3. PUT - 서버의 기존 리소스를 업데이트합. 주로 전체 수정. 
   * 안전성: 서버 상태를 변경.
   * 멱등성: 동일한 요청을 여러 번 수행해도 결과가 동일.
   * 캐싱: 캐싱할 수 있음.

4. PATCH - 서버의 기존 리소스를 부분적으로 업데이트. 
   * 안전성: 서버 상태를 변경.
   * 멱등성: 동일한 요청을 여러 번 수행해도 결과가 동일.
   * 캐싱: 일반적으로 캐싱하지 않음.

5. DELETE - 서버에서 리소스를 삭제. 
   * 안전성: 서버 상태를 변경.
   * 멱등성: 동일한 요청을 여러 번 수행해도 결과가 동일.
   * 캐싱: 일반적으로 캐싱하지 않음.

6. HEAD - GET 요청과 동일하지만, 응답 본문을 포함하지 않음. 리소스의 메타데이터(헤더)만 반환. 
   * 안전성: 서버 상태를 변경하지 않음.
   * 멱등성: 동일한 요청을 여러 번 수행해도 결과가 동일.
   * 캐싱: 캐싱할 수 있다.

7. OPTIONS - 서버가 지원하는 HTTP 메서드를 확인. 
   * 안전성: 서버 상태를 변경하지 않음.
   * 멱등성: 동일한 요청을 여러 번 수행해도 결과가 동일.
   
8. TRACE - 요청이 서버에 도달하는 과정을 추적. 
   * 안전성: 서버 상태를 변경하지 않음.
   * 멱등성: 동일한 요청을 여러 번 수행해도 결과가 동일.
   
### RestFul 이란?
* RESTful 서비스는 REST 원칙을 준수하는 웹 서비스.
---
## JPA란 무엇인가? 
* JPA(Java Persistence API)는 자바 진영의 ORM 기술 표준이다. 애플리케이션과 JDBC 사이에서 동작한다.

### ORM이란 무엇인가?
* Object-Relational Mapping 이름 그대로 객체와 관계형 데이터 베이스 매핑한다는 뜻.
* ORM 프레임워크는 객체와 테이들블 매핑해서 패러다임의 불일치 문제를 개발자 대신 해결.
  * ex) 개발자가 insert SQL문을 직접 작성하는 것이 아니라, 객체르 자바 컬렉션에 저장하듯 ORM 프레임워크에 저장하면 됨. -> ORM 프레임워크가 자동 매핑.
* 자바 진영의 대표적인 ORM 프레임 워크 : Hibernate

### JPA를 사용하는 하는 이유
1. 생산성
    * 지루하고 반복적인 CRUD용 SQL을 개발자가 직접 작성하지 않아도 된다.
    * Create Table 같은 DDL 문을 자동으로 생성해주는 기능 있음

2. 유지보수
    * SQL 직접 다루면 엔티티에 필드 하나 추가만 해도 관련된 JDBC API 수정해야 함. But JPA 사용하면 JPA가 대신 처리. => 유지보수 해야하는 코드 줄어듦.
    * 패러다임 불일치 문제를 해결해주므로 객체지향 언어가 가진 장점을 활용해서 유지보수하기 좋은 도메인 모델을 편리하게 설계

3. 패러다임의 불일치 해결
    * 상속, 연관관계, 객체 그래프 탐색, 비교하기와 같은 패러다임의 불일치 문제를 해결.
      * 상속 : 
        * JDBC API 사용하면 부모 객체 데이터 꺼내오는 코드, 자식 객체 데이터 꺼내오는 SQL 코드 다 만들어야함. => JPA 사용하면 해결
        * 자바 컬렉션에 저장하듯 JPA에 객체를 저장하면 됌. ex) jpa.persist()
      * 연관관계 : 참조로 연관관계 맺을 수 있음 -> 저장, 조회 등  기능 할때 참조로 해결 가능. ex) entity에 Team team 선언. 외래 키 선언 필요 X.
      * 객체 그래프 탐색(참조를 사용해 연관된 팀 찾는 것): 
        * SQL을 직접 다루면 처음 실행하는 SQL에 따라 객체 그래프를 어디까지 탐색할 수 있는지 정해짐. => 개발자에게 너무 큰 제약(SQL에 의존적인 개발)
        * JPA 사용하면 객체 그래프 마음껏 탐색 가능. 지연로딩(필요한 시점에 데이터를 꺼내오는 것)을 투명하게 처리.
      * 비교 : 
        * 테이블은 기본 키의 값으로 row 구분 - 객체는 동일성(==)과 동등성(equals)을 구분
        * JPA는 같은 트랜잭션일 때 같은 객체가 조회되는 것을 보장함. 

4. 성능
    * JPA는 애플리케이션과 데이터베이스 사이에서 작동 -> 최적화 관점에서 시도해 볼 수 있는 것이 많음.

5. 데이터 접근 추상화와 벤더 독립성
    * 관계형 데이터 베이스는 같은 기능도 벤더마다 사용법이 다른 경우 많이 있음.(ex) 페이징, 데이터베이스 마다 페이징 처리 기법이 달라서 따로 따로 익혀야 함) -> JPA 사용하면 데이터 베이스 변경할 때 다른 데이터베이스를 사용한다고 알려주기만 하면 문제 해결.
  
  
### JPA를 사용하는 원리
* 자바 객체와 데이터베이스 테이블 간의 매핑을 통해 객체지향 프로그래밍의 장점을 유지하면서 데이터베이스와 상호작용한다. 엔티티, 엔티티 매니저, 영속성 컨텍스트, JPQL을 통해 데이터의 생성, 조회, 업데이트, 삭제 작업을 수행.

#### JPA 자세한 원리
1. 엔티티 매니저 팩토리에서 엔티티 매니저 생성 -> 엔티티 매니저 내부에 영속성 컨텍스트 같이 만들어짐.(영속성 컨텍스트는 엔티티 매니저를 통해 접근 가능)
2. 영속성 컨텍스트가 가상의 데이터베이스 같은 역할을 수행 -> 영속성 컨텍스트 덕분에 1차 캐시, 동일성 보장, 트랜잭션을 지원하는 쓰기 지연, 변경감지, 지연 로딩 사용 가능.
3. 영속성 컨텍스트에 저장한 엔티티 플러시 통해 데베 반영 (일반적으로 트랜잭션을 커밋할 때 영속성 컨텍스트 플러시)

* 엔티티 매니저란?
   * 엔티티를 저장, 수정, 조회, 삭제하는 등 엔티티와 관련된 모든 일 처리
   * 말 그대로 엔티티를 관리하는 관리자다.
   * 영속성 컨텍스트 사용(엔티티를 영구 저장하는 환경 이라는 뜻.) => 영속성 컨텍스트에 엔티티를 저장하거나 조회하고 보관한다.

* 엔티티 매니저 팩토리와 엔티티 매니저 
  * 데이터베이스 사용하는 애플리케이션은 일반적으로 하나의 엔티티 매니저 팩토리 생성. => 필요할 때마다 엔티티 매니저 펙토리에서 엔티티 매니저 생성
    * **중요** 엔티티 매니저 팩토리는 여러 스레드가 동시에 공유해도 안전 BUT 엔티티 매니저는 여러 스레드 동시 접근 시 동시성 문제 발생
  
* 엔티티의 생명주기
  1. 비영속 : 영속성 컨텍스트와 관계가 없는 상태
  2. 영속 : 영속성 컨텍스트에 저장된 상태 -> 엔티티가 영속성 컨텍스트에 의해 관리된다는 뜻
  3. 준영속 : 영속성 컨텍스트에 저장되었다가 분리된 상태 -> 이에 해당하는 엔티티는 영속성 컨텍스트가 제공하는 기능을 사용할 수 없다.
  4. 삭제 : 삭제된 상태

* 영속성 컨텍스트의 특징
  1. 영속성 컨텍스트와 식별자 값
     * 영속상태는 식별자가 반드시 있어야 함.(엔티티를 식별자로 구별 -> 없으면 예외 발생)
  2. 플러시를 통해 영속성 컨텍스트 안에 있는 엔티티를 데베에 저장
  3. 장점
     * 1차 캐시 지원
     * 동일성 보장
     * 트랜잭션을 지원하는 쓰기 지연
     * 변경 감지
     * 지연 로딩

### JPA 특징
1. 객체-관계 매핑(ORM)
   * 엔티티는 데이터베이스 테이블에 매핑되며, 필드는 테이블의 열에 매핑.

2. 투명한 데이터 접근
   * 엔티티 매니저를 통해 데이터베이스 접근이 이루어지므로, 데이터베이스 종속성을 줄일 수 있다.

3. 캐싱 
   * JPA는 1차 캐시를 통해, 동일한 트랜잭션 내에서 동일한 엔티티에 대한 중복 조회를 방지.
   * 2차 캐시를 통해 애플리케이션 전반에 걸쳐 엔티티를 캐싱할 수 있음.

4. 자동화된 DDL 생성 
   * 엔티티 클래스의 매핑 정보를 기반으로 데이터베이스 테이블을 자동으로 생성 및 변경할 수 있음.
   *  [...]

2024-08-03 06:42 UTC, sosow0212 requested changes
미션하시느라 수고 많으셨습니다 👍
스프링 사용이 처음인데 너무 잘하셔서 깜짝 놀랐습니다! 아직은 다듬어야 할 부분들이 있지만 이 부분들은 키워드 학습을 통해 하나씩 다듬어가면 좋을 것 같아요~
리뷰가 조금 많은데 천천히 학습해보시고 모르시는 부분은 연락주세요!

2024-08-03 06:42 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/controller/LottoController.java
> +    }
ResponseEntity.create(...)도 있는데 해당 방식은 뭐가 다를까요?
URI를 넣어주는데 이건 어떤 이유일까요 ㅎㅎ RESTful에 대해 공부하기 지금 딱 좋을 것 같아요!
응답코드와, url 설계는 어떻게 할지, 그리고 자원의 표기란 무엇인지 등등 같이 확인해보세요
사실 응답은 정말 팀바팀 컨벤션이라 다 다르지만 여러 방법에 대해 이해하고 있으면 협업할 때 많은 도움이 됩니다!

2024-08-03 06:42 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/controller/LottoController.java
> +    @GetMapping("/user/{id}/lottos")
RESTful에 의하면 users가 더 적절할 것 같습니다!
그리고 id가 lottos 뒤에도 나올 수 있을 것 같은데(당장은 안나와도 미래를 고려한다면) users의 id를 나타낼 때 네이밍을 userId와 같이 더 헷갈리지 않게 하면 좋을 것 같습니다!

2024-08-03 06:42 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/controller/LottoController.java
> +package com.lotto.web.controller;
도메인형 패키지 구조도 있는데, 관심사가 다른 객체들이 많아진다면 가시성이 좋아서 저는 보통 도메인형 패키지 구조를 선호하는데 한 번 이 부분도 알아보세요 !

2024-08-03 06:42 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/domain/exception/CustomErrorCode.java
> +package com.lotto.web.domain.exception;
exception 도메인 패키지 안에 두는 거 좋습니다! 저는 원래 domain외부에 exception을 지정해주었는데 advice만 웹의 응답이니 다른 계층의 패키지가 더 좋다고 생각이 들어요

`@RestControllerAdvice`와 스프링 예외 처리 방식은 무엇이고 어떤 원리로 작동되는지에 대해서 지금 알아보시면 많이 도움될 것 같습니다. 중요한 개념이니 꼭 확인해보세요! 현재는 커스텀 예외만 발생하고 응답으로 처리는 안 되어있습니다 ㅎㅎ

그리고 CustomErrorCode나 CustomException 같은 경우도 지금은 User, Lotto가 섞여있습니다.
둘의 관심사는 다르기에 분리가 되는게 책임을 분리하는 것에 더 좋다고 생각하는데, 이 부분도 상속이나 인터페이스 기능을 이용해서 처리해보시면 어떨까요?

지금은 @RestControllerAdvice와 @ExceptionHandler에 대해 학습하지 않으셔서 왜 그래야하는지 감이 안 오실 수 있지만, 현재처럼 예외를 줄 때 A, B, C 객체들의 예외는 ACustomException, B.., CCustomException 이렇게 만들어질텐데
이 {A,B,C}CustomException이 하나의 부모 클래스를 바라보고 있다면, @ExceptionHandler에서 하나만 지정해줘도 모든 상속받은 자식 클래스도 캐치되어서 중복 코드를 줄이는데 크게 도움이 됩니다!

이 부분이 지금은 익숙치 않을 수 있는데 한 번 구현해보시면서 모르는 부분 연락하면서 풀어나가도 좋을 것 같습니다~

2024-08-03 06:42 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/dto/CreateRequest.java
> +public class CreateRequest {
DTO는 Record 클래스를 사용하는 건 어떨까요? 해당 클래스는 다른 클래스들과 무엇이 다를까요?

2024-08-03 06:42 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/dto/LottoRequest.java
> +    }
null 값이 들어가는데 다른 방식으로 구현해볼 순 없을까요? 어차피 id 값은 Wrapper타입일 것 같아요

2024-08-03 06:42 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/entity/LottoAnswer.java
> +package com.lotto.web.entity;
이건 좀 중요한 개념이라서 꼭 확인해보셨으면 좋겠습니다.

1. Entity와 Domain의 차이점은 무엇일까요?
2. JPA는 왜 등장하였고 어떤 이점이 있어서 사용할까요?
3. JPA는 외부 라이브러리 기술인데 1번에서 알아본 Entity와 섞이곤 합니다. JPA 객체와 Entity모델을 분리하는 것은 어떤 이유로 분리하고 합치는 경우는 어떤 이유로 합칠까요?
4. 해당 클래스는 1번에서 나온 두 부류 중 어떤 부분에 더 가까울까요? 하님 혼용이 됐을까요?
5. 현재 Domain 패키지 내에서 JPA를 결합한다고 팀 컨벤션으로 정해졌다면 어떻게 하는게 좋을까요?


이 질문이 다소 모호할 수 있는데 힌트를 드리자면 Entity와 Domain은 다르고 둘을 분리하는 것은 기술은 언제나 바뀔 수 있기 때문에 저는 좋다고 생각합니다! JPA가 등장하면서 이 둘의 관계가 모호해지면서 합쳐서 사용하는 경우가 많은데 어떻게 합쳐 사용할 수 있을지도 고민해보시면 좋을 것 같습니다 ㅎㅎ

근거만 있다면 어떤 방식이든 정답이 될 수 있는 문제이기 때문에 공부하시면서 본인의 기준을 잡아봐도 좋을 것 같아요!

2024-08-03 06:42 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/entity/User.java
> +    }
1. 해당 생성자는 어떤 것 때문에 어떤 원리로 필요할까요?
2. 접근제어자를 public으로 열었는데 무엇이 문제일까요?

2024-08-03 06:42 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/entity/LottoEntity.java
> +    @ManyToOne
매핑도 굉장히 중요해서 질문식으로 남길테니 꼭 혼자 공부하시면서 많은 고민 해보셨으면 좋겠습니다!

1. @ManyToOne을 사용하신 이유가 궁금합니다.
2. Long userId로 간접참조하면 1번 방식과 무엇이 다른가요?
3. ManyToOne 옵션들에는 무엇이 있고 현재는 다른 옵션이 필요 없을까요?
4. 양방향 매핑은 무엇인가요? 현재는 단방향 매핑으로 하셨는데 이유가 있을까요? 어떤 근거로 단방향 매핑으로 진행하셨나요?

2024-08-03 06:42 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/service/LottoService.java
> +    private final UserService userService;
이건 개인적이지만 Service에서 Service를 참고하는 건 좋은 구조라고 생각하진 않습니다.
Service는 비즈니스 로직을 구현한 부분인데 LottoService 기준으로 타 서비스의 메서드를 호출할 순 있지만 만약 요구사항이 바뀐다면 타 서비스에서 불필요하지만 LottoService만을 위한 메서드가 생길 수도 있고 응집도가 떨어지게 됩니다.

반면에 Repository와 같이 하위 레이어를 호출한다면 비즈니스 로직은 LottoService에서 만들 수 있기 때문에 상위 계층인 UserService와는 무관하게 돼서 의존의 레벨이 낮아진다고 생각합니다.

일단 Lotto와 User는 다른 관심사이므로 서로 간 의존하지 않는게 가장 좋긴 합니다. 이를 스프링 이벤트로 풀어나갈 수도 있고 인터페이스를 통해 의존을 줄일 수도 있습니다.

현재는 해당 방법들을 배우시지 않으셔서 괜찮지만 이런 문제도 있다는 점만 아시면 좋을 것 같습니다!

2024-08-03 06:42 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/service/LottoService.java
> +public class LottoService {
현재 Repository를 통해 MySQL 데이터베이스와 연결되어 객체를 저장하거나 조회하며 사용하고 있습니다.
`@Transactional`은 무엇이고 왜 필요하며 여기에 다른 속성은 없는지 공부해보시고 적용해보시면 좋을 것 같습니다. (readonly...)

2024-08-03 06:42 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/service/LottoService.java
> +        }
이 부분은 도메인의 역할인데 서비스로 로직이 노출되어 있습니다.

위에 리뷰들과 연관이 되어있는데요.
지금 도메인과 엔터티를 분리하셨는데, 도메인을 통해 로직을 모두 실행한 후 Mapper를 통해 Entity로 값만 변환해주어서 사용한다면 캡슐화를 할 수 있을 것 같습니다!

혹은 도메인 엔터티를 합치는 방법도 있는데 장단점 생각하시면서 원하시는 방법으로 진행해도 좋을 것 같습니다 ㅎㅎ

2024-08-03 06:42 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/service/LottoService.java
> +        userService.updateMoney(lottoRequest);
의존으로 인해 여러 서비스의 기능을 활용하게 되는데요! 이 부분 해결하시고 싶으시면 Event에 대해 학습하셔도 좋을 것 같습니다!
다만 개인적으로는 해당 미션에서는 단순 학습 정도만 하시고 다음 미션에서 하셔도 될 것 같긴 합니다 ㅎㅎ 지금도 너무 양이 많아서 한 번 쓱 공부만 하시면 좋을 것 같기도 합니다~

2024-08-03 06:42 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/service/UserService.java
> +    public User getUser(Long id) {
get과 find 네이밍 차이에 대해서 알아보시면 좋을 것 같습니다 ㅎㅎ
현재는 확실히 있기보다는 없을 수도 있으니 find가 적절하지 않을까요? 다른 메서드들도 확인해주세요!

2024-08-03 06:42 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/service/UserService.java
> +    }
1. 이 부분도 캡슐화가 되어있지 않습니다.
2. JPA에서 쓰기지연, 더티체킹 등등 여러가지 특징이 있는데 꼭 확인해보세요!
3. @Transactional 키워드랑 2번 키워드랑 어떤 연관이 있을지 고민해보세요.
4. 3번까지 했다면 45라인에서 save가 필요 없을 수 있는데 왜 그럴까요?

2024-08-03 06:42 UTC, sosow0212 commented on mission-lotto/src/test/java/com/lotto/web/domain/LottoNumberParserTest.java
> +package com.lotto.web.domain;
Service 레이어 테스트와 Controller 레이어 테스트도 중요합니다.

1. 통합테스트와 단위테스트는 무엇이 다를까요?
2. E2E 테스트는 무엇일까요?
3. 실제 빈을 띄우는 테스트와 Stub/Fake/Mock을 이용한 테스트는 각각 어떤 장단점이 있을까요?
4. 통합테스트를 통해 실제 빈을 띄운다면 주의할 점은 있을까요?
5. 테스트 격리란 무엇일까요?
6. TestFixture는 무엇일까요?

2024-08-05 08:32 UTC, moonwhistle commented on mission-lotto/src/main/java/com/lotto/web/controller/LottoController.java
> +    }
제가 작성한 코드는 상태 값만 넣어주는 것으로 알고 있습니다. 하지만 ReponseEntity.create(...) 이 방식을 사용하면 URI location = URI.create("/api/users/"+ user.getId());
        return ResponseEntity.created(location).build(); 이러한 형식으로 URI를 넣어줄 수 있고, 해당 URI로 접속하여 Get메소드를 사용해 사용자 정보를 받아올 수 있습니다!
        
HTTP 응답코드에 관해 공부해서 리드미에 작성하였고, 설계 원칙을 다시 찾아보며 url 설계 방법을 익혔습니다! 주로 소문자로 리소스에 관한 내용만 나타내는 것으로 익혔습니다 !

최종 결론은 멘토님이 추천해주신 메서드로 리팩터링 진행하였습니다! 나중에 사용자 조회나 제대로 객체가 만들어졌는지 확인하기 위해서는 멘토님이 추천해주신 방식이 더 좋다고 생각하였습니다!

2024-08-05 08:38 UTC, moonwhistle commented on mission-lotto/src/main/java/com/lotto/web/controller/LottoController.java
> +    @GetMapping("/user/{id}/lottos")
설계원칙에 따라 users로 리팩터링 하였고, userId로 바꾸어 추후에 헷갈리지 않게 하였습니다!

2024-08-05 09:23 UTC, moonwhistle commented on mission-lotto/src/main/java/com/lotto/web/dto/CreateRequest.java
> +public class CreateRequest {
record 클래스에 대해 다시 한 번 공부해보고 적용하였습니다! 

## record 클래스

### 개요
* 데이터의 불변 상태를 유지하기 위해 우리는 데이터 클래스를 생성해왔음. like dto.
  * 각 데이터 조각에 대해 private이고 final인 필드를 만든다.
  * 각 필드에 대한 getter를 만든다.
  * 각 필드에 해당하는 인수를 가진 public 생성자를 만든다.
  * 모든 필드가 일치할 때 동일한 클래스 객체에 대해 true를 반환하는 equals 메서드를 만든다.
  * 모든 필드가 일치할 때 동일한 값을 반환하는 hashCode 메서드를 만든다.
  * 클래스 이름과 각 필드 이름 및 해당 값을 포함하는 toString 메서드를 만든다.

* 이와 같은 방식으로 데이터 불변 클래스를 생성하면 문제점이 발생함
  1. 보일러플레이트 코드가 많다.
  2. 클래스의 목적이 가려진다: ex) 이름과 주소를 가진 사람을 나타내는 클래스라는 점이 명확하지 않다.

* 따라서 데이터 클래스임을 나타내는 클래스에 대한 필요성이 생김. => 자바 14부터 반복적인 클래스를 record 로 대체 가능.

### 주요 기능 및 이점

1. 생성자, equals, hashCode, toString 메서드 자동 생성:
   Java 컴파일러가 자동으로 private 및 final 필드를 생성하고, 이에 해당하는 public 생성자, equals, hashCode, toString 메서드를 생성.
   ~~~
   public record Person(String name, String address) {}
   ~~~
   Record를 사용하면, 각 필드에 대한 인자를 가지는 public 생성자가 자동으로 생성.

2. Getter 메서드
   * 필드 이름과 동일한 이름을 가진 public getter 메서드가 자동으로 생성.

3. 생성자 커스터마이징
  * 기본 생성자는 자동으로 생성되지만, 사용자 정의 생성자도 가능. 예를 들어, null 값 확인을 추가할 수 있음(validation).
    ~~~
    public record Person(String name, String address) {
    public Person {
        Objects.requireNonNull(name);
        Objects.requireNonNull(address);
      }
    }
    ~~~
  * 다른 인수를 가진 생성자도 만들 수 있음.

4. static 메서드 사용 가능
  ~~~
  public record Person(String name, String address) {
      public static String UNKNOWN_ADDRESS = "Unknown";
  
      public static Person unnamed(String address) {
          return new Person("Unnamed", address);
      }
  }
  ~~~

### 결론
* Record를 사용하면 보일러플레이트 코드를 줄이고, 불변 클래스의 신뢰성을 높일 수 있음.

2024-08-05 09:27 UTC, moonwhistle commented on mission-lotto/src/main/java/com/lotto/web/dto/LottoRequest.java
> +    }
데베에 id 값은 자동으로 저장되기에, LottoEntity 생성자 인자를 수정하여 다른 방식으로 구현하였습니다!

2024-08-05 12:08 UTC, moonwhistle commented on mission-lotto/src/main/java/com/lotto/web/controller/LottoController.java
> +package com.lotto.web.controller;
도메인형 패키지 구조는 처음 공부해보았는데, 가시성이 정말 좋은 것 같아서 멘토님 조언대로 리팩터링 하였습니다!

## 계층형 패키지 구조 vs 도메인형 패키지 구조

* 계층형 패키지 구조
~~~
controller
	⎿ UserController
	⎿ LottoController	

service
	⎿ UserService
	⎿ LottoService
	
dto ...
domain ...
~~~
1. 패키지만 보면 전체적인 구조 파악 가능
2. 계층별 응집도 상승
3. but 도메인별 응집도는 낮다.(하나의 패키지 안에 여러 도메인이 섞여있음.)
4. 규모가 커지면 가시성이 떨어진다


* 도메인형 패키지 구조
~~~
User
   ⎿ UserController
   ⎿ UserService
   ⎿ UserDto
    ...

Lotto
   ⎿ LottoController
   ⎿ LottoService
   ⎿ LottoDto
    ...
~~~
1. 도메인별 응집도가 높아진다.
2. 유스케이스별로 세분화해서 표현 가능
3. but 전반적인 흐름은 파악하기 어렵다.
4. 개발자 관점에 따라 패키지 두는 위치가 바뀔 수 있음.

### 결론
* 정답은 없지만 프로젝트 규모가 커지면 도메인 패키지 구조가 유리함.

2024-08-05 13:21 UTC, moonwhistle commented on mission-lotto/src/main/java/com/lotto/web/domain/exception/CustomErrorCode.java
> +package com.lotto.web.domain.exception;
1. exception 패키지를 아예 하나 빼고(global 느낌), 예외가 필요한 패키지에 exception 패키지를 또 추가하여 어디에 예외가 쓰이는지 한 눈에 알 수 있게 하였습니다! 
2. 상속을 받아 예외처리 할 수 있도록 구현하였습니다! 
3. @ExceptionHandler 처음 사용해보았는데 신기합니다...
4. 멘토님 말씀대로 요즘 공식문서 번역해서 찾아보는데, 정말 많이 도움이 되는 것 같습니다 감사합니다!!!

## Spring 예외 처리 


* @Controller 및 @ControllerAdvice 클래스는 컨트롤러 메서드에서 발생하는 예외를 처리하기 위해 @ExceptionHandler 메서드를 가질 수 있다.
~~~
@Controller
public class SimpleController {

    // ...

    @ExceptionHandler
    public ResponseEntity<String> handle(IOException ex) {
        // 예외 처리 로직
        return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body("IOException occurred: " + ex.getMessage());
    }
}
~~~

### ControllerAdvice
* @ControllerAdvice와 @RestControllerAdvice는 예외 처리, 데이터 바인딩, 모델 속성 설정 등의 기능을 글로벌하게 적용하기 위해 사용되는 기능.

#### 기본 원리
* @ExceptionHandler, @InitBinder, @ModelAttribute 메서드는 선언된 @Controller 클래스(또는 클래스 계층) 내에서 적용. 이러한 메서드를 전역적으로(여러 컨트롤러에 걸쳐) 적용하고자 할 경우, @ControllerAdvice 또는 @RestControllerAdvice 어노테이션이을 붙여 클래스 선언 가능.
* @ControllerAdvice는 @Component로도 어노테이트되어 있으므로, 컴포넌트 스캐닝을 통해 스프링 빈으로 등록될 수 있다.
* @RestControllerAdvice는 @ControllerAdvice와 @ResponseBody가 결합된 어노테이션으로, @ExceptionHandler 메서드를 메시지 변환을 통해 응답 본문으로 렌더링한다.

#### 동작 방식
* 애플리케이션 시작 시, @RequestMapping 및 @ExceptionHandler 메서드에 대한 클래스는 @ControllerAdvice로 어노테이트된 스프링 빈을 감지하고, 런타임에 해당 메서드를 적용. 전역 @ExceptionHandler 메서드(즉, @ControllerAdvice에서 선언된 메서드)는 로컬 메서드(즉, @Controller에서 선언된 메서드) 이후에 적용된다(Controller 예외 먼저, 이후 ControllerAdvice 예외 적용). 반면, 전역 @ModelAttribute 및 @InitBinder 메서드는 로컬 메서드 이전에 적용.

```적용 범위 좁히기```
* 기본적으로 @ControllerAdvice 메서드는 모든 요청(모든 컨트롤러)에 적용된다. 그러나 애노테이션의 속성을 사용하여 특정 컨트롤러의 하위 집합에만 적용되도록 범위를 좁힐 수 있다.

~~~
// @RestController로 어노테이트된 모든 컨트롤러를 대상으로 함
@ControllerAdvice(annotations = RestController.class)
public class ExampleAdvice1 {}

// 특정 패키지 내의 모든 컨트롤러를 대상으로 함
@ControllerAdvice("org.example.controllers")
public class ExampleAdvice2 {}

// 특정 클래스에 할당 가능한 모든 컨트롤러를 대상으로 함
@ControllerAdvice(assignableTypes = {ControllerInterface.class, AbstractController.class})
public class ExampleAdvice3 {}
~~~

### ExceptionHandler
* @ExceptionHandler 메서드는 컨트롤러 메서드에서 발생하는 특정 예외를 처리할 수 있다.
* @RestControllerAdvice와 함께 사용하여 전역 예외 처리를 구현할 수 있음.
* 메서드 인수: @ExceptionHandler 메서드는 @RequestMapping 메서드와 동일한 메서드 인수를 지원.
* 반환 값: @ExceptionHandler 메서드는 @RequestMapping 메서드와 동일한 반환 값을 지원.

2024-08-06 12:13 UTC, moonwhistle commented on mission-lotto/src/main/java/com/lotto/web/entity/User.java
> +    }
접근제어자 protected로 수정하였습니다!

## Entity - 기본 생성자 필요한 이유
* 기본 생성자가 존재하지 않는다면 DB에서 조회해 온 값을 엔티티로 만들 때 객체 생성 자체가 실패함. (JPA가 엔티티를 인스턴스화할 때 리플렉션(Reflection)을 사용하기 때문.)

``리플랙션이란? - 자바 프로그래밍 언어에서 런타임에 클래스, 인터페이스, 메서드, 필드 등의 구조를 검사하고 조작할 수 있는 기능을 의미.``

### 기본 생성자의 접근 제어자는 어떤 것을 써야 할까?
* 결론 : protected
  * lombok 의 @NoArgsConstructor(access = AccessLevel.PROTECTED)를 엔티티 클래스 위에 선언함으로 간단하게 생성자를 사용

1. private 사용했을 경우 : 리플랙션 사용할 때 접근 자체가 불가능 -> JPA는 프록시 기술을 사용하는데 거기서 프록시 기술을 쓸 때, jpa hibernate가 객체를 강제로 만들어야하는데 private 로 만들어보리면 막혀버림.
2. public 사용했을 경우 : 
   * public을 사용하면 setter 사용 가능 -> 객체의 일관성을 보장 X
   * 모든 클래스가 User 엔티티를 자유롭게 인스턴스화할 수 있게 됨 -> 캡슐화 위반

2024-08-06 15:04 UTC, moonwhistle commented on mission-lotto/src/main/java/com/lotto/web/entity/LottoEntity.java
> +    @ManyToOne
1. @ManyToOne을 사용한 이유는 하나의 member가 여러 개의 Lotto를 가질 수 있기에 설정해 주었습니다. (다대일 관계에서 다 쪽에 속하는게 로또이기에 로또에 선언해주었습니다.)
2. 간접참조를 진행하게 되면 쿼리를 따로 짜야하는 복잡성이 생기고, 직접 참조를 하면 Member 객체 자체를 가져올 수 있기에 이 객체 안에서 필요한 데이터를 꺼내 쓸 수 있어서 직접참조 하였습니다!
3. 최적화를 위해 지연로딩 어노테이션 설정해서 리팩터링 하였습니다!
4. 양방향 매핑은 각 엔티티에서 서로 참조하도록 하는 것입니다! 제가 단방향 매핑을 한 이유는 이번 미션 요구사항에 Member를 통해 Lotto를 조회하는 요구사항이 있긴 하였지만, 로또 측에서 MemberId로 모든 로또를 가져와서 반환하는 것이 조금 더 간단한 로직이라고 생각되어 단방향 매핑으로 진행하였습니다! 양방향 매핑으로 하는 것이 맞다면 리팩터링 하겠습니다 말씀해주시면 감사하겠습니다!!

2024-08-06 15:07 UTC, moonwhistle commented on mission-lotto/src/main/java/com/lotto/web/service/LottoService.java
> +    private final UserService userService;
서비스에서 서비스를 참조하도록 하여 구현 하면서 뭔가 어색하다는 느낌이 들긴 하였습니다.  Event 학습하여서 다음 미션에 적극 반영하도록 하겠습니다 !

2024-08-06 18:52 UTC, moonwhistle commented on mission-lotto/src/main/java/com/lotto/web/service/LottoService.java
> +        userService.updateMoney(lottoRequest);
Event에 대해 학습하고 다음 미션에서 적용해보겠습니다!!

2024-08-06 19:56 UTC, moonwhistle commented on mission-lotto/src/main/java/com/lotto/web/service/UserService.java
> +    public User getUser(Long id) {
find, get 앞으로 유의해서 사용하겠습니다 ! 리팩터링 하였습니다

2024-08-06 19:57 UTC, moonwhistle commented on mission-lotto/src/main/java/com/lotto/web/service/LottoService.java
> +        }
dto에 정적 팩터리 메서드를 사용하여 검증 진행하였고, 이후 mapper 를 통해 entity로 반환하도록 진행하였습니다!

2024-08-07 18:57 UTC, moonwhistle commented on mission-lotto/src/main/java/com/lotto/web/service/LottoService.java
> +public class LottoService {
학습 진행하였습니다 !

## Transaction(트랜잭션)
* 트랜잭션(Transaction 이하 트랜잭션)이란, 데이터베이스의 상태를 변화시키기 해서 수행하는 작업의 단위를 뜻함.

### 트랜잭션의 특징
1. 원자성 (Atomicity) 
   * 트랜잭션 내의 모든 명령이 모두 수행되어야 하며, 하나라도 수행 안될 경우 트랜잭션 모두 취소 => 롤백
2. 일관성 (Consistency)
   * 트랜잭션이 그 실행을 성공적으로 완료하면 언제나 일관성 있는 데이터베이스 상태로 유자.
3. 격리성 (Isolation)
   * 둘 이상의 트랜잭션이 동시에 병행 실행되는 경우 어느 하나의 트랜잭션 실행 중에 다른 트랜잭션의 연산이 끼어들 수 없음
4. 지속성 (Durability)
   * 트랜잭션이 성공적으로 완료됬을 경우, 결과는 영구적으로 반영되어야 한다는 점
     
   
### 트랜잭션 연산 및 상태 

#### 연산
* Commit 연산 : 한개의 논리적 단위(트랜잭션)에 대한 작업이 성공적으로 끝났고 데이터베이스가 다시 일관된 상태에 있을 때, 이 트랜잭션이 행한 갱신 연산이 완료된 것을 트랜잭션 관리자에게 알려주는 연산
* Rollback 연산 : 하나의 트랜잭션 처리가 비정상적으로 종료되어 데이터베이스의 일관성을 깨뜨렸을 때, 이 트랜잭션의 일부가 정상적으로 처리되었더라도 트랜잭션의 원자성을 구현하기 위해 이 트랜잭션이 행한 모든 연산을 취소(Undo)하는 연산 => Rollback 시에는 해당 트랜잭션을 재시작하거나 폐기.

#### 상태
* 활동(Active) : 트랜잭션이 실행중인 상태
* 실패(Failed) : 트랜잭션 실행에 오류가 발생하여 중단된 상태
* 철회(Aborted) : 트랜잭션이 비정상적으로 종료되어 Rollback 연산을 수행한 상태
* 부분 완료(Partially Committed) : 트랜잭션의 마지막 연산까지 실행했지만, Commit 연산이 실행되기 직전의 상태
* 완료(Committed) : 트랜잭션이 성공적으로 종료되어 Commit 연산을 실행한 후의 상태


### @Transactional
* @Transactional 어노테이션은 트랜잭션의 범위와 설정을 정의하는 데 사용 , 트랜잭션이 성공적으로 완료되면 커밋되고, 예외가 발생하면 롤백됨.
* 사용법 : 클래스에 적용(클래스에 해당하는 메서드 모두 적용), 메서드 적용.(둘 다 적용된 경우에는 메서드에 적용된게 우선순위 높음)

#### 트랜잭션 설정

1. propagation: 트랜잭션 전파 방식을 정의. (기본값: REQUIRED)
2. isolation: 트랜잭션 격리 수준을 정의. (기본값: ISOLATION_DEFAULT)
3. timeout: 트랜잭션 타임아웃을 초 단위로 설정. (기본값: 없음)
4. readOnly: 읽기 전용 트랜잭션 여부를 설정. (기본값: false)
5. rollbackFor: 롤백을 유발할 예외 타입을 지정.
6. noRollbackFor: 롤백을 유발하지 않을 예외 타입을 지정.

2024-08-07 19:28 UTC, moonwhistle commented on mission-lotto/src/main/java/com/lotto/web/service/UserService.java
> +    }
1. @Transactional 어노테이션을 학습하다 보니 자연스럽게 캡슐화 진행되었습니다 !
2. 확인하여 학습 진행하였습니다 .
3. @transactional 붙어있는 메서드 내에서 데이터 변경이 이루어지면 더티체킹에 의해 알아서 커밋되어 데이터가 변경됩니다. 또한, 트랜잭션이 커밋되기 전까지 변경사항을 보류하는 쓰기 지연이 이루어집니다.
4. 트랜잭션 내에서 엔티티 값 변경해주면 더티체킹에 의해 트랜잭션이 커밋되어 데베에 반영되기 때문입니다.

## JPA : 데베 상호작용을 위한 특징

### 쓰기 지연 (Write-Behind/Write-Delay)
* 쓰기 지연은 JPA가 엔티티에 대한 변경 사항을 즉시 데이터베이스에 반영하지 않고, 트랜잭션이 커밋될 때까지 변경 사항을 보류하는 기능. => 데이터베이스와의 상호작용 횟수를 줄여 성능을 최적화.

### 더티 체킹 (Dirty Checking)
* 더티 체킹은 JPA가 엔티티의 상태 변화를 감지하여 트랜잭션이 커밋될 때 자동으로 데이터베이스에 반영하는 기능. 엔티티의 속성 값이 변경되면, JPA는 이를 감지하고 필요한 업데이트 쿼리를 생성하여 데이터베이스에 반영.

### 1차 캐시 (First-Level Cache)
* 영속성 컨텍스트는 1차 캐시 역할을 함. 동일한 트랜잭션 내에서 동일한 엔티티를 여러 번 조회할 때, 데이터베이스를 다시 조회하지 않고 1차 캐시에서 엔티티를 반환 => 이렇게 하면 데이터베이스 접근 횟수를 줄이고 성능을 향상(최적화).

### 지연 로딩 (Lazy Loading)과 즉시 로딩 (Eager Loading)
* 엔티티 간의 연관 관계를 로딩할 때, JPA는 지연 로딩과 즉시 로딩을 제공. 
  * 지연 로딩은 실제로 연관된 엔티티가 필요할 때까지 로딩을 지연시키는 방식. 
  * 즉시 로딩은 엔티티를 조회할 때 연관된 엔티티도 즉시 로딩하는 방식.

### JPQL (Java Persistence Query Language)
* JPQL은 SQL과 유사한 구문을 사용하여 엔티티 객체를 조회하기 위한 쿼리 언어. JPQL은 데이터베이스 테이블이 아닌 엔티티 객체를 대상으로 쿼리를 작성.
* gpt 예제
~~~
public List<User> findUsersByName(String name) {
    return entityManager.createQuery("SELECT u FROM User u WHERE u.name = :name", User.class)
                        .setParameter("name", name)
                        .getResultList();
}
~~~

2024-08-07 23:03 UTC, moonwhistle commented on mission-lotto/src/test/java/com/lotto/web/domain/LottoNumberParserTest.java
> +package com.lotto.web.domain;
## 스프링 테스트 정리

### 단위 테스트 (Unit Test)
* 개별 모듈 또는 구성 요소를 테스트
* 목적
  * 개별 모듈 또는 클래스의 동작을 검증
  * 코드의 특정 부분이 예상대로 동작하는지 확인
* 범위
  * 주로 하나의 메서드나 클래스
  * 외부 의존성(Mock 객체 사용)은 제거하고 테스트

### 통합 테스트 (Integration Test)
* 여러 모듈 또는 구성 요소가 함께 작동하는지 테스트.(데이터베이스, 외부 API 등과의 상호작용도 포함)
* 목적
  * 여러 모듈 또는 클래스가 함께 올바르게 동작하는지 검증
  * 데이터베이스, 외부 API 등과의 상호작용을 포함
* 범위
  * 여러 클래스나 모듈 간의 상호작용
  * 실제 의존성을 사용하여 테스트

```통합 테스트에서 실제 빈을 띄울 때 주의할 점 : 데이터 베이스 격리 - Transactional 어노테이션을 사용하여 테스트가 끝난 후 롤백진행.```


### E2E 테스트 (End-to-End Test)
* 사용자 관점에서 시스템의 전체 워크플로우를 테스트
* 목적
  * 실제 사용자의 관점에서 예상대로 작동하는지 확인
  * 플리케이션의 모든 구성 요소(프론트엔드, 백엔드, 데이터베이스, 외부 서비스 등)가 통합되어 제대로 동작하는지 확인. (단위 테스트나 통합 테스트로는 확인 어려운 것들 확인 가능)
* 범위
  * 프론트엔드, 백엔드, 데이터베이스, 외부서버 등등..

### 실제 빈을 띄우는 테스트와 Stub/Fake/Mock을 이용한 테스트

#### 실제 빈을 띄우는 테스트 - 통합테스트, 컨트롤러 테스트
* 실제 환경과 유사한 조건에서 테스트
* 모든 스프링 기능(AOP, 트랜잭션 등) 테스트 가능
* 설정과 실행 시간이 길어질 수 있음
* 외부 시스템의 상태에 따라 테스트 결과가 달라질 수 있음

#### Stub/Fake/Mock을 이용한 테스트 - 단위테스트
* 빠르고 간단하게 테스트 가능
* 외부 시스템의 의존성을 제거하여 독립적 테스트 가능
* 실제 환경과 다를 수 있음
* Mock 객체 설정이 복잡할 수 있음


### 테스트 격리
* 각 테스트가 독립적으로 실행되어 다른 테스트의 결과나 상태에 영향을 받지 않도록 하는 것을 의미한다. 

1. 도메인 -> 단위테스트 진행 : 알아서 격리 됌. @BeforEach로 객체 생성 가능하기 때문.
2. 서비스 -> Mock + @Transactional 이용 
3. 컨트롤러 -> @WebMvcTest 어노테이션을 사용해서 SpringMvc에 필요한 빈들만 사용, @DataJpaTest라는 어노테이션을 사용해서 데이터 계층에 관련된 빈들만 가지고 slice테스트를 할 수 있음.

### TestFixture
* Test Fixture는 테스트를 실행하기 전에 설정해야 하는 초기 상태나 환경을 의미. 주로 객체를 생성하는데 많이 이용.

**사용법**
1. @BeforEach 사용해서 객체 setUp, @AfterEach 사용해서 객체 delete
2. Fixture 패키지 -> MemberFixture -> 정적 팩토리 메서드로 객체 생성.

2024-08-10 04:43 UTC, sosow0212 requested changes
어프루브 하려다가 조금 더 다듬고 하면 좋을 것 같아서 한 번 더 스킵했습니다!
리뷰 보시고 스스로 더 학습하시고 진행해보세요~ 하다가 어려워서 질문이 생긴다면 카톡으로 연락주세요!

거의 다 온 것 같습니다 ㅎㅎ

2024-08-10 04:43 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/global/exception/exceptions/CustomErrorCode.java
> +public enum CustomErrorCode {
ㅎㅎ 여기에 몇 가지만 더 추가하면 좋을 것 같습니다.

예외 응답을 줄 때 404, 400, 401, 409 등등의 여러 응답 코드로 분리될 수 있을 것 같아요. 이런 응답 코드도 CustomErrorCode의 필드로 두고 나중에 GlobalExceptionHandler에서 이를 반환해주는 식으로 하면 좋을 것 같습니다.

그리고 EXCEPTION_USER 이런 네이밍보다는 USER_NOT_FOUND_EXCEPTION 이런 네이밍을 두는 게 더 적합할 것 같아요~

2024-08-10 04:43 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/lotto/controller/LottoController.java
> +        return ResponseEntity.status(HttpStatus.OK).body(lottoService.getLottos(memberId));
ResponseEntity.ok(body) 이렇게해도 될 것 같습니다!

2024-08-10 04:43 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/lotto/dto/LottoResponses.java
> +    public static LottoResponses form(List<LottoResponse> lottoResponses) {
```suggestion
    public static LottoResponses from(List<LottoResponse> lottoResponses) {
```

2024-08-10 04:43 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/lotto/entity/LottoEntity.java
> +    @ManyToOne(fetch = FetchType.LAZY)
```suggestion
    private Long id;
    
    @ManyToOne(fetch = FetchType.LAZY)
```

2024-08-10 04:43 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/lotto/entity/LottoEntity.java
> +    private boolean win;
```suggestion
    private boolean isWinner;
```

2024-08-10 04:43 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/lotto/entity/LottoEntity.java
> +    private boolean win;
이거 약간 Entity 자체가 좀 이상한 것 같아요
Entity면 테이블 관련 필드만 있어야하는데 JPA랑 섞인 것 같고, Win과 같은 필드도 있는게 조금 낯설은 것 같아요.

Lotto (로또에 대한 정보만), Member(멤버에 대한 정보만), MemberLotto(memberId, lottoId, int score OR boolean isWinner ...) 이렇게 하는게 좋지 않을까요?

그리고 양방향 매핑이 왜 단방향보다 좋다고 생각하셨는지 여기에 댓글로 부탁드릴게요 ㅎㅎ 궁금합니다!

2024-08-10 04:43 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/lotto/service/LottoService.java
> +        saveLottos(lottoRequest, lottoAnswer.getLottoAnswer());
메서드 순서 맞춰주세요!

2024-08-10 04:43 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/lotto/service/LottoService.java
> +        Member member = memberService.findUser(lottoRequest.userId());
서비스를 의존하기보다는 Repository를 의존하는게 좋을 것 같습니다.
비즈니스 로직이 커진다면 서비스를 강의존할텐데 그 하위 레포지토리 레이어를 의존하면 해당 서비스 전략에 맞게 커스텀 가능할 것 같아요!

2024-08-10 04:43 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/lotto/service/LottoService.java
> +    }
도메인 로직인 것 같습니다!

2024-08-10 04:43 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/lotto/service/LottoService.java
> +        return lottoAnswer.orElseGet(this::createLottoAnswer);
이걸 한 문장으로 체이닝으로 할 수 있지 않을까요?

2024-08-10 04:43 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/member/controller/MemberController.java
> +        URI location = URI.create("/api/members/" + memberResponse.id());
👍

2024-08-10 04:43 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/member/entity/Member.java
> +    private int lottoCount;
Member가 lottoCount를 꼭 가져야할까요? 다른 기능이 생긴다면 불필요한 정보 아닐까요 ㅎㅎ

2024-08-10 04:43 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/member/entity/Member.java
> +    private int winning;
이것두요

2024-08-10 04:43 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/member/entity/Member.java
> +        this.money -= count * 1000;
1000은 상수화 해주세요!

2024-08-10 04:43 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/member/entity/Member.java
> +            throw new NotFoundMoneyException();
이거` throw new CustomException(CustomExceptionlCode.해당하는 예외)` 이렇게 되어야할 것 같아요!

2024-08-10 04:43 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/member/service/MemberService.java
> +    public MemberResponses findAllUsers() {
Members를 찾고 반환하고 dto로의 변환은 컨트롤러에서 하는게 적합하지 않을까요?

2024-08-10 04:43 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/member/service/MemberService.java
> +        int winning = member.getWinning() + LottoPrice.getLottoPrice(count);
getWinning은 상금인지 뭔지 구체화 해주세요!

2024-08-10 04:43 UTC, sosow0212 commented on mission-lotto/src/test/java/com/lotto/web/lotto/controller/LottoControllerTest.java
> +    @Autowired
@Autowired와 @MockBean의 차이점은 무엇일까요?

2024-08-10 04:43 UTC, sosow0212 commented on mission-lotto/src/test/java/com/lotto/web/lotto/controller/LottoControllerTest.java
> +@WebMvcTest(controllers = LottoController.class)
여기에 해당 어노테이션 단 것과 @SpringBootTest를 단 것과 무엇이 다를까요?
해당 어노테이션은 어떤 역할을 할까요?

2024-08-10 04:43 UTC, sosow0212 commented on mission-lotto/src/test/java/com/lotto/web/lotto/service/LottoServiceTest.java
> +@SpringBootTest
여기에 속성은 어떤 것들이 있을까요?

2024-08-10 04:43 UTC, sosow0212 commented on mission-lotto/src/test/java/com/lotto/web/lotto/service/LottoServiceTest.java
> +    @Transactional(readOnly = true)
@Transcational을 왜 붙일까요?
안 붙이고는 안될까요? 테스트 격리에 대해 공부해보시면 좋을 것 같습니다!

2024-08-10 07:15 UTC, moonwhistle commented on mission-lotto/src/main/java/com/lotto/web/global/exception/exceptions/CustomErrorCode.java
> +public enum CustomErrorCode {
에러코드 추가하였고, 네이밍 수정하여 리팩터링 진행하였습니다!

2024-08-10 07:15 UTC, moonwhistle commented on mission-lotto/src/main/java/com/lotto/web/lotto/controller/LottoController.java
> +        return ResponseEntity.status(HttpStatus.OK).body(lottoService.getLottos(memberId));
해당 코드처럼 리팩터링 진행하였습니다!

2024-08-10 07:16 UTC, moonwhistle commented on mission-lotto/src/main/java/com/lotto/web/lotto/dto/LottoResponses.java
> +    public static LottoResponses form(List<LottoResponse> lottoResponses) {
네이밍 리팩터링 하였습니다!

2024-08-10 07:17 UTC, moonwhistle commented on mission-lotto/src/main/java/com/lotto/web/lotto/entity/LottoEntity.java
> +    @ManyToOne(fetch = FetchType.LAZY)
개행 리팩터링 하였습니다 ! id 값은 띄워주어야 하는군요..!!

2024-08-10 08:19 UTC, moonwhistle commented on mission-lotto/src/main/java/com/lotto/web/lotto/service/LottoService.java
> +        Member member = memberService.findUser(lottoRequest.userId());
LottoService에 memberRespository 까지 가져다 쓰는게 Lotto가 Member 기능에 너무 의존한다는 느낌을 받아서 MemberService에 해당 메서드를 구현하였는데, 오히려 service를 강의존한다는 것을 생각하지 못한 것 같습니다 ! 

레파지토리에서 받아올 수 있도록 리팩터링 하였습니다!!

2024-08-10 08:31 UTC, moonwhistle commented on mission-lotto/src/main/java/com/lotto/web/lotto/service/LottoService.java
> +        return lottoAnswer.orElseGet(this::createLottoAnswer);
체이닝 완료했습니다!

2024-08-10 08:32 UTC, moonwhistle commented on mission-lotto/src/main/java/com/lotto/web/member/controller/MemberController.java
> +        URI location = URI.create("/api/members/" + memberResponse.id());
감사합니다 ㅎㅎ
controller 에서 service 단의 엔티티를 dto로 받고, controller에서는 dto로 사용자에게 반환하는 것을 이해하였습니다!

2024-08-10 08:34 UTC, moonwhistle commented on mission-lotto/src/main/java/com/lotto/web/member/entity/Member.java
> +        this.money -= count * 1000;
상수화 하여 리팩터링 하였습니다!

2024-08-10 08:38 UTC, moonwhistle commented on mission-lotto/src/main/java/com/lotto/web/member/entity/Member.java
> +            throw new NotFoundMoneyException();
엔티티와 기능을 구현하는 도메인 단에서는 exception 패키지를 설정하는 것보다 위의 리뷰처럼 throw new CustomException... 이런 식으로 예외를 설정해주는 것인가요??

2024-08-10 08:44 UTC, moonwhistle commented on mission-lotto/src/main/java/com/lotto/web/member/service/MemberService.java
> +    public MemberResponses findAllUsers() {
컨트롤러에서 dto 변환할 수 있도록 리팩터링 하였습니다!

2024-08-12 05:49 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/member/controller/MemberController.java
> +        URI location = URI.create("/api/members/" + memberResponse.id());
아 저는 URI 리다이렉션 반환이 좋아서 따봉한거였습니다 ㅎㅎㅋㅋ
서비스에서는 도메인 자체를 주고 컨트롤러에서는 dto로 감싸서 변환의 책임을 해주면 됩니다!

서비스에서 dto를 주고 컨트롤러에서 받은 dto를 또 다른 dto로 변환해주는 것도 괜찮지만, 서비스에서 순수 값이 변경된 도메인만을 준다면 컨트롤러에서 알아서 그 값들 중 필요한 것들만 getter로 반환해줄 수 있으니요

2024-08-12 05:50 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/member/entity/Member.java
> +            throw new NotFoundMoneyException();
아닙니다!

여기서는 `thorw new MemberException(MemberExceptionType.LACK_OF_MONEY)` 이런식으로요!

2024-08-12 14:06 UTC, moonwhistle commented on mission-lotto/src/main/java/com/lotto/web/lotto/entity/LottoEntity.java
> +    private boolean win;
1. Entity를 없애고 Domain 위에 JPA를 달아서 합치고, MemberLotto 클래스 따로 파서 도메인 하나 분리하겠습니다!

2. 다른 요구사항이 생기는 경우에 양방향 매핑이 되어있으면 멤버측에서 로또를 쉽게 끌어와서 여러 기능을 구현할 수 있을 것이라고 생각하여 양방향 매핑이 더 좋다고 생각하였습니다 ! 그런데 여러 공부하면서 연관관계를 최소화 하는 것이 데베 관리에 더 좋다는 글들이 있어서, 어쩌면 단방향 매핑도 나쁘지 않을 것이라는 생각이 들었습니다..!

2024-08-12 14:07 UTC, moonwhistle commented on mission-lotto/src/main/java/com/lotto/web/lotto/service/LottoService.java
> +        saveLottos(lottoRequest, lottoAnswer.getLottoAnswer());
메서드 순서 맞춰주었습니다!

2024-08-12 14:10 UTC, moonwhistle commented on mission-lotto/src/main/java/com/lotto/web/member/controller/MemberController.java
> +        URI location = URI.create("/api/members/" + memberResponse.id());
앗 그렇군요 !! 
컨트롤러에서 순수 변경된 값만 가져와서 다시 dto로 포장해 반환할 수 있도록 리팩터링 하겠습니다!

2024-08-12 14:27 UTC, moonwhistle commented on mission-lotto/src/main/java/com/lotto/web/lotto/service/LottoService.java
> +    }
도메인 로직해서 해당 메서드 구현하도록 리팩터링 하였습니다!

2024-08-12 15:11 UTC, moonwhistle commented on mission-lotto/src/main/java/com/lotto/web/member/entity/Member.java
> +    private int lottoCount;
MemberLotto 클래스 생성하여 분리하였습니다!!

2024-08-12 15:11 UTC, moonwhistle commented on mission-lotto/src/main/java/com/lotto/web/member/entity/Member.java
> +    private int winning;
MemberLotto 클래스 생성하여 분리하였습니다!!

2024-08-12 15:15 UTC, moonwhistle commented on mission-lotto/src/main/java/com/lotto/web/member/service/MemberService.java
> +        int winning = member.getWinning() + LottoPrice.getLottoPrice(count);
메서드명 구체화하여 상금으로 확실히 나타냈습니다!

2024-08-13 03:14 UTC, moonwhistle commented on mission-lotto/src/test/java/com/lotto/web/lotto/controller/LottoControllerTest.java
> +    @Autowired
## @Autowired 와 @MockBean 의 차이점

### @Autowired
* Spring 컨테이너에 의해 관리되는 빈을 자동으로 주입하는 데 사용되어짐. - 실제 동작

### @MockBean
* Spring 컨테이너에 가짜(Mock) 빈을 주입하는 데 사용되어짐. - 가짜 동작
* 실제 빈을 대신하여 테스트 환경에서 가짜 빈을 주입하여 외부 의존성을 제거하거나 제어된 테스트 환경을 조성.

2024-08-13 03:20 UTC, moonwhistle commented on mission-lotto/src/test/java/com/lotto/web/lotto/controller/LottoControllerTest.java
> +@WebMvcTest(controllers = LottoController.class)
## @WebMvcTest 와 @SpringBootTest 의 차이점

### @WebMvcTest
* Spring MVC 컴포넌트에 대한 테스트를 집중적으로 수행하기 위해 사용(주로 컨트롤러에 사용). - 테스트하기 위해 필요한 최소한의 Spring MVC 컴포넌트만 땡겨옴, 서비스 데베 같은 빈들은 땡겨오지 않음.
* 테스트 목적 : 컨트롤러 레이어의 테스트에 집중, 주로 HTTP 요청/응답에 대한 테스트
* 테스트 속도 :  로딩하는 빈의 수가 적으므로 상대적으로 빠르게 테스트가 진행.

### @SpringBootTest
* 플리케이션의 모든 구성 요소를 통합적으로 로드하여, 전체 애플리케이션 컨텍스트에서 테스트를 수행 - 모든 빈을 떙겨옴, 데베 연동 가능
* 전체 애플리케이션의 통합적인 동작을 테스트하고 싶을 때 사용 - 모든 계층의 테스트에 적합.
* 테스트 목적 : 애플리케이션 전체의 통합 테스트, 서비스 레이어, 데이터베이스 등 모든 계층을 포함한 테스트
* 테스트 속도 : 모든 빈을 로드하기 때문에 상대적으로 오래 걸림.

### 결론
* controller만 테스트 -> @WebMvcTest
* 통합적 전체 테스트 -> @SpringBootTest

2024-08-13 03:24 UTC, moonwhistle commented on mission-lotto/src/test/java/com/lotto/web/lotto/service/LottoServiceTest.java
> +    @Transactional(readOnly = true)
## 테스트 격리와 @Transactional

### 테스트에서 @Transactional 사용하는 이유.
* 테스트 격리:
  * 테스트 격리는 개별 테스트가 서로 영향을 주지 않도록 격리된 환경에서 실행되는 것을 의미 즉, 하나의 테스트가 다른 테스트에 영향을 미치지 않도록 보장

* 위와 같은 관점으로 보았을 때, @Transactional 사용하면, 테스트 메서드 내에서 수행되는 모든 데이터베이스 작업이 하나의 트랜잭션 내에서 수행. -> 테스트가 끝난 후에는 기본적으로 트랜잭션이 rollback되므로, 데이터베이스 상태가 초기화되어 다른 테스트에 영향을 주지 않게 된다.

### @Transactional 사용하지 않는다면? 
* 테스트 메서드가 수행하는 데이터베이스 작업이 실제로 commit 된다. -> 다음 테스트에서 데이터베이스 상태가 이전 테스트에 의해 변경된 상태로 남아 있을 수 있음.

## 결론 
* @Transactional을 사용하는 것은 테스트 간의 독립성을 보장하고, 데이터베이스 상태를 일관되게 유지하기 위함이다.(테스트 격리 관점에서 보았을 때도 사용하는 것이 맞음.)

2024-08-13 07:45 UTC, sosow0212 approved these changes
수고하셨습니다! 다음 미션 진행하시면서 부족한 부분들 채워서 진행하시면 될 것 같습니다~
질문사항은 카톡에 답변 드렸습니다! 빈에 대해 이해도 잘 하셨고 테스트도 잘 하신 것 같아 좋습니다 👍
테스트 격리가 무엇인지 찾아보시고 다음 미션 땐 통합테스트 환경에서 테스트격리도 같이 진행해보면 좋을 것 같습니다!

2024-08-13 07:45 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/global/exception/exceptionhandler/GlobalExceptionHandler.java
> +        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(errorResponse);
여기서 무조건 BAD_REQUEST 즉 400 에러를 반환하게 되는데요
우리가 CustomExceptionType에 에러코드를 명시해뒀으니 `HttpStatus.from(ExceptionType.code)` 아마 이렇게 하면 상황에 맞는 우리가 기재한 코드가 응답코드로 반환 될 것 같아요! IDE를 보고있지 않아 정확히 메서드가 from이 아닐 수도 있는데 찾아보면 있습니다~ 아니면 ExceptionType에 404와 같은 int형 값이 아닌 HttpStatus.BAD_REQUEST와 같이 기본제공상수를 넣어줘도 괜찮을 것 같네요!
그리고 404와 같은 상태코드 말고도 추가적으로 ExceptionType에 커스텀 상태코드도 많이 넣곤 합니다. 즉 팀원과 임의로 AO0001은 404이지만 A자원이 없는 경우, AO0002는 404지만 B자원이 없는 경우 뭐 이런식으로 하기도 합니다 ㅎㅎ
이 부분은 다음 미션때 활용해보세요~

2024-08-13 07:45 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/global/exception/exceptions/CustomErrorCode.java
> +    MONEY_NOT_FOUNT_EXCEPTION(404, "돈 없음."),
이건 상태코드랑 네이밍이 좀 잘못된 것 같아요~
NOT_FOUND는 요청 자원이 없는 경우인데, 돈이 없는데 로또 구매를 하려고 요청을 보내는 건 400 BAD_REQUEST가 조금 더 적절하지 않나 생각합니다!

그래서 LACK_OF_MONEY_EXCEPTION 이런 네이밍이 더 적절할 것 같아요 ㅎㅎ

2024-08-13 07:45 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/lotto/controller/LottoController.java
> +        LottoResponses lottoResponses = LottoMapper.toLottoResponses(lottoResponse);
이 부분도 그냥 DTO에게 변경을 위임해도 좋을 것 같아요.

DTO가 도메인을 의존하긴 하지만 어차피 변환의 책임만 지기 때문에 이정도는 편의성이나 가독성 면에서 이점이 더 많다고 생각합니다!
`var result = LottoResponse.from(lottoService.getLottos(memberId))` 이렇게 하고 변환 로직을 안에다 둬도 됩니다

이건 좀 장단점이 있어서 본인만의 기준을 정해봐도 될 것 같아요! 대신 어떤 장단점이 있는지 확인하면서요 ㅎㅎ
저는 개인적으로 dto에 변환로직을 두기는 합니다!

2024-08-13 07:45 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/lotto/controller/LottoController.java
> +    @GetMapping(value = "/members/{memberId}/lottos", params = "order")
RESTful도 잘 이해하셨네요!

2024-08-13 07:45 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/lotto/dto/LottoResponses.java
> +    private static void validateLottoOrder(List<LottoResponse> lottoResponses, int order) {
dto에서 validation을 해줄 필요가 없을 것 같습니다
지금은 예외처리 즉 비즈니스 로직을 dto가 알고있는데 이 부분은 모두 서비스단에서 끝내야합니다!

2024-08-13 07:45 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/lotto/entity/LottoEntity.java
> +    private String lottoNumber;
ㅎㅎ 이거 오해 있을까봐요 띄우는게 가독성면에서 좋아서 제안 드렸는데 이건 스타일이라 편하신대로 하셔도 됩니다!

```suggestion
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "memberId")
    private Member member;
    
    @Column
    private String lottoNumber;
    
    @Column
    ...
    
```

2024-08-13 07:45 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/lotto/entity/LottoEntity.java
> +    private boolean win;
정답이 없기 때문에 둘다 장단점 알고 상황에 맞게 쓰시면 됩니다!

2024-08-13 07:45 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/lotto/service/LottoService.java
> +        }
이것도 Lottos라는 일급컬렉션으로 만들고 생성을 도메인 로직으로 뺀 후 나중에 saveAll로 getLottos()를 통해 저장해줄 수 있을 것 같습니다!

2024-08-13 07:45 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/web/member/mapper/MemberMapper.java
> +public class MemberMapper {
dto에서 toDomain, toDto가 아닌 Mapper를 중간에 두셨네요! 의존을 끊기 위해서 책임을 매퍼로 두셨네요~

2024-08-13 07:45 UTC, merged

2024-08-17 07:34 UTC, moonwhistle commented on mission-lotto/src/main/java/com/lotto/web/global/exception/exceptionhandler/GlobalExceptionHandler.java
> +        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(errorResponse);
멘토님 코드 리뷰 보면서 에러 코드에 관한 부분이 생각보다 많이 중요하다고 느껴집니다..! 제대로 공부해서 보드 미션에 적용시켜보겠습니다 감사합니다!

2024-08-17 07:36 UTC, moonwhistle commented on mission-lotto/src/main/java/com/lotto/web/lotto/controller/LottoController.java
> +        LottoResponses lottoResponses = LottoMapper.toLottoResponses(lottoResponse);
변환의 책임을 지는 정도는 dto에서 구현해도 되는군요.. 일부로 컨트롤러에서만 dto 에 관한 로직 구현하려고 하다보니 저렇게 작성한 것 같습니다. 이정도의 책임은 dto에서 구현해보겠습니다!

2024-08-17 07:37 UTC, moonwhistle commented on mission-lotto/src/main/java/com/lotto/web/global/exception/exceptions/CustomErrorCode.java
> +    MONEY_NOT_FOUNT_EXCEPTION(404, "돈 없음."),
알겠습니다!! 상황 잘 따져가며 네이밍 할 수 있도록 노력하겠습니다..!! 너무 생각없이 404로 설정했네요 ㅠ

2024-08-17 07:38 UTC, moonwhistle commented on mission-lotto/src/main/java/com/lotto/web/lotto/controller/LottoController.java
> +    @GetMapping(value = "/members/{memberId}/lottos", params = "order")
감사합니다 ㅎㅎ

2024-08-17 07:39 UTC, moonwhistle commented on mission-lotto/src/main/java/com/lotto/web/lotto/entity/LottoEntity.java
> +    private String lottoNumber;
오.. 자바처럼 뭔가 컨벤션이 있는 줄 알았습니다! 저는 띄우는게 그래도 보기 편한거 같습니다..!

2024-08-17 07:40 UTC, moonwhistle commented on mission-lotto/src/main/java/com/lotto/web/lotto/service/LottoService.java
> +        }
사실 Lottos를 어떻게 작성해야 효율적일까를 많이 고민하고 있었지만 굳이 필요하다는 생각이 들지 않아서 구현하지 않았습니다. 그런데 saveAll 메서드가 있다는 것을 알고 나니 Lottos를 구현하는 것이 더 효율적일 것이라는 생각이 들었습니다 !!

2024-08-17 07:41 UTC, moonwhistle commented on mission-lotto/src/main/java/com/lotto/web/member/mapper/MemberMapper.java
> +public class MemberMapper {
넵 멘토님 조언 덕분에 Mapper 구현할 수 있었습니다!