Lotto/step1 제출합니다!
sosow0212/2024-mju-mentoring-spring-2 pull request #11
Opened 2024-08-04 23:01 UTC by Hheojiwon

로또 미션 제출하겠습니다! 

- HTTP 메서드와  RESTful API, JPA 학습하였습니다!  어려웠지만 이번에 학습하면서 많이 알아가게 된 것 같습니다.
-  도메인 로직과 서비스 로직을 작성하는 부분도 좀 헷갈렸던 것 같습니다 ... 현재 코드는 서비스 레이어가 좀 복잡한 것 같다고 느껴지는데  알려주시면 감사하겠습니다!!

---

## 1. 사용자 등록(POST)
```
POST /api/lotto/register

{
    "name" : "jiwon",
    "money" : 5000 
}
```

## 2. 로또 구매(POST)
```
POST /api/lotto/buy

{
    "name" : "jiwon",
    "ticketCount" : 2
}
```
- exception: 금액 부족한 경우 예외 발생

## 3. 로또 결과 이름으로 조회(GET)
```
GET /api/lotto/result?name=jiwon&winNumbers=1,2,3,4,5,6

response
[
    {
        "lottoNumber": [
            4,
            7,
            31,
            35,
            36,
            42
        ],
        "result": false
    },
    {
        "lottoNumber": [
            1,
            8,
            17,
            22,
            26,
            39
        ],
        "result": false
    }
]
```
-  exception: 존재하지 않는 사용자 이름인 경우 예외 발생

## 4. 로또 결과 로또 id로 조회(GET)
```
GET /api/lotto/result/1?winNumbers=1,2,3,4,5,6

response
{
    "lottoNumber": [
        4,
        7,
        31,
        35,
        36,
        42
    ],
    "result": false
}
```
- result: 1~4등 당첨은 true 반환
- exception: 존재하지 않는 로또 id인 경우 예외 발생

## 5. 로또 전체 결과 조회(GET)
```
GET /api/lotto/allResults?winNumbers=1,2,3,4,5,6

response
{
    "userResults": [
        {
        "name": "jiwon",
        "lottoCount": 2,
        "prizeMoney": 0
        }
    ]
}

```

2024-08-05 00:48 UTC, sosow0212 requested changes
처음이신데 엄청 잘 구현해주셨네요 👍
아직은 캡슐화가 되지 않은 곳도 있지만 이 부분은 스프링이 익숙치 않으셔서 그런 것 같습니다!
지난 번에 비해서 엄청 성장하신게 코드로 보입니다~
통합테스트도 잘 작성해주셨는데요 리뷰 보시고 몇 부분들 더 공부하시면서 더 다듬으면 좋을 것 같습니다!

2024-08-05 00:48 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/controller/LottoController.java
> +        }
상태변경을 마친 List<Lotto>를 감싼 일급컬렉션 Lottos를 반환 받고 Dto에 변환로직을 위임해서 더 깔끔하게 만들어보는 건 어떨까요?

2024-08-05 00:48 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/controller/LottoController.java
> +        boolean isWinning = lottoService.isWinningLotto(userLotto.getLottoNumbers(), winNumbers);
이것도 필요하다면 새로운 객체를 만들어서(ex. Judge) 하나로 묶을 수 있을 것 같습니다!

2024-08-05 00:48 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/controller/LottoController.java
> +    @GetMapping("/result")
RESTful은 무엇이고, url 설계 원칙과 HTTP Method에 대해 공부해보시면 좋을 것 같습니다!

2024-08-05 00:48 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/controller/LottoController.java
> +    @Autowired
생성자가 한 개라서 @Autowired는 필요 없습니다~

2024-08-05 00:48 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/controller/LottoController.java
> +        }
이 부분도 마찬가지입니다!
url 설계와 반환 다시 고려해보세요

2024-08-05 00:48 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/controller/dto/AllResultsResponse.java
> +package com.lotto.controller.dto;
Response를 해주는 dto 패키지와 Request를 하는 dto 패키지 분리를 해보는 건 어떨까요?

분리를 한다면 Response, Request 패키지는 각각 어디에 있으면 좋을지도 레이어드 아키텍처 관점에서 의존을 생각하면서 분리해보세요!

2024-08-05 00:48 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/domain/LottoResult.java
> +    private final LottoRank rank;
일급 컬렉션 객체의 원칙이 지켜지질 않고있습니다.

필요하다면 lottoNumbers, winNumbers를 각각 일급컬렉션 객체로 포장한후 LottoResult에서 포장된 객체들을 조합해서 사용해도 좋을 것 같아요

2024-08-05 00:48 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/domain/LottoResult.java
> +        }
기존에는 matchCount를 필드로 빼셔서 진행하셨는데 메서드 지역변수로 선언하셨네요! 좋습니다 👍

2024-08-05 00:48 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/domain/Lottos.java
> +        this.lottos=lottos;
정렬 신경써주세요 !

2024-08-05 00:48 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/domain/Lottos.java
> +    public static Lottos buyLotto(int numberOfTickets, RandomNumber randomNumber){
static일 필요는 없을 것 같습니다

2024-08-05 00:48 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/entity/User.java
> +@NoArgsConstructor
접근 제어자 설정을 안해도 될까요?

All~, No~ 어노테이션은 각각 무엇을 하는지 고민해보고 특히 No~ 어노테이션은 왜 사용하는지 고민해보시면 좋을 것 같습니다

2024-08-05 00:48 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/entity/User.java
> +    private List<UserLotto> userLotto = new ArrayList<>();
1. User에서 Lotto를 OneToMany로 단방향 매핑하는 방법
2. Lotto에서 User를 ManyToOne으로 단방향 매핑하는 방법
3. User, Lotto 에서 각각 OneToMany, ManyToOne으로 양방향 매핑하는 방법

이 셋의 차이점은 무엇이고 각각 언제 쓰면 좋을까요?

2024-08-05 00:48 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/entity/User.java
> +        }
null값이 될 수 있을까요?

2024-08-05 00:48 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/entity/UserLotto.java
> +    @ElementCollection
해당 어노테이션은 왜 사용할까요??

2024-08-05 00:48 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/entity/UserLotto.java
> +    @GeneratedValue
기본키 생성 전략이 빠져있습니다!

2024-08-05 00:48 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/repository/LottoRepository.java
> +    List<UserLotto> findByUser_UserName(String userName);
JpaRepository 안에 이미 @Repository가 있어 빈으로 등록되어 있습니다!
즉 상속 받는다면 해당 클래스에선 이미 @Repository가 있는 것과 같아서 어노테이션은 필요 없습니다

2024-08-05 00:48 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/service/LottoService.java
> +    private RandomNumber randomNumber;
DIP 원칙 👍

2024-08-05 00:48 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/service/LottoService.java
> +        checkUserName(user == null);
이 부분이 좀 어색한데요
repository에서 조회할 때 반환형을 Optional<User> 로 준다면 서비스에서 비즈니스 로직에 맞게 null일 때 처리할 수 있지 않을까요? 서비스든 다른 곳이든 로직 내에서 null이 나오는 건 자바에서 위험합니다!

Optional을 활용해보세요~

2024-08-05 00:48 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/service/LottoService.java
> +        validateMoney(user, price);
도메인 로직이 외부(서비스)에 노출되었네요! 캡슐화 해주세요

2024-08-05 00:48 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/service/LottoService.java
> +public class LottoService {
1. @Transactional 어노테이션이 무엇이고 왜 사용하는 것일까요
2. @Transactional(readonly = true)를 사용하면 어떻게 될까요
3. JPA와 @Transactional 어노테이션은 어떤 관계가 있을까요
4. JPA와 같이 썼을 때 어떤 특징이 있을까요? (MySQL 기준)

이 질문 해결하시면서 공부 해보시면 좋을 것 같습니다!

2024-08-05 00:48 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/service/LottoService.java
> +        }
이 부분도 도메인 로직인데 캡슐화가 안 되어있네요!

2024-08-05 00:48 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/service/LottoService.java
> +        checkUserName(!userRepository.existsByUserName(name));
1. 얘도 위에 Optional 처럼 null 생각해서 다시 구현해주세요
2. 메서드 순서 맞춰주세요~ (public A -> private A' -> private A'' ... -> public B -> public B` ...)

2024-08-05 00:48 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/service/LottoService.java
> +        };
switch문 말고 if문 사용해주세요! 스위치는 실수해서 런타임 에러가 날 여지가 많기 때문에 지양해주세요!

2024-08-05 00:48 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/service/UserService.java
> +        }
얘도 Optional과 체이닝으로 예외까지 처리해보면 좋을 것 같습니다

2024-08-05 00:48 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/service/UserService.java
> +    }
지금은 단순히 알아만 두시면 좋을 것 같습니다!

findAll은 위험한 메서드입니다.
DB에 데이터가 10억 건 혹은 무수히 더 많은 데이터가 있을 때 모두 조회를 한 후 List에 적재를 하는데 그렇게 되면 OOME 문제가 발생할 수도 있고 DB에 부하를 주고 처리 시간이 오래 걸리기 때문에 요청자 입장에선 커넥션 풀을 오래 기다리거나 심각할 경우 다운이 될 수도 있습니다!

나중에는 이를 페이징으로 해결하는데 참고만 해주시면 좋을 것 같습니다!

2024-08-05 00:48 UTC, sosow0212 commented on mission-lotto/src/test/java/com/lotto/LottoServiceTest.java
> +public class LottoServiceTest {
테스트 좋습니다!

1. 통합테스트와 단위테스트의 차이
2. Fake, Stub, Mock Test 차이
3. 테스트 격리란 무엇이고 어떻게 하는지

이 정도 학습해보시면 많이 도움되실 것 같아요. 팀원마다 스타일이 달라서 통합테스트도, 단위테스트의 여러 기법들도 다 알긴해야하는데 본인만의 기준을 생각해봐도 좋을 것 같습니다

2024-08-05 00:48 UTC, sosow0212 commented on mission-lotto/src/test/java/com/lotto/LottoServiceTest.java
> +    @Transactional
테스트 격리는 어떻게 할까요?!

아마 개별 실행은 통과하지만 테스트 전체 실행에선 몇 가지 메서드는 테스트 실패하셨을텐데 DB에 데이터가 누적되고 지워지지 않아서 발생하는 현상입니다

@SpringBootTest 어노테이션에도 속성이 있는데 그 속성들은 무엇이고, 테스트 격리는 어떻게 할 수 있는지 여러 방법들에 대해서 지금쯤 공부하면 딱 좋을 것 같습니다.

블로그 검색도 해보시고 마지막에는 꼭 공식문서 보시면서 학습해보세요!

2024-08-11 11:04 UTC, Hheojiwon commented on mission-lotto/src/main/java/com/lotto/controller/LottoController.java
> +        }
넵 리팩토링 하였습니다!!

2024-08-11 11:07 UTC, Hheojiwon commented on mission-lotto/src/main/java/com/lotto/controller/LottoController.java
> +    @Autowired
넵 수정했습니다!

2024-08-11 11:44 UTC, Hheojiwon commented on mission-lotto/src/main/java/com/lotto/controller/LottoController.java
> +        }
수정했습니다!

2024-08-11 11:44 UTC, Hheojiwon commented on mission-lotto/src/main/java/com/lotto/controller/dto/AllResultsResponse.java
> +package com.lotto.controller.dto;
dto 패키지 분리 했습니다!

2024-08-11 11:45 UTC, Hheojiwon commented on mission-lotto/src/main/java/com/lotto/domain/Lottos.java
> +        this.lottos=lottos;
넵 ㅠㅠ 수정했습니다!

2024-08-11 11:47 UTC, Hheojiwon commented on mission-lotto/src/main/java/com/lotto/domain/Lottos.java
> +    public static Lottos buyLotto(int numberOfTickets, RandomNumber randomNumber){
static 사용하지 않는 방식으로 리팩토링 하였습니다!

2024-08-11 12:12 UTC, Hheojiwon commented on mission-lotto/src/main/java/com/lotto/entity/User.java
> +@NoArgsConstructor
@AllArgsConstructor: 모든 필드값을 파라미터로 받는 생성자를 만들어주는 애노테이션
@NoArgsConstructor: 아무런 매개변수가 없는 기본 생성자를 생성하는 애노테이션
기본 생성자의 접근 제어를 PROTECTED로 설정 해놓게 되면 무분별한 객체 생성에 대해 체크 할 수 있기 때문에 AccessLevel.PROTECTED를 사용

2024-08-11 12:16 UTC, Hheojiwon commented on mission-lotto/src/main/java/com/lotto/entity/User.java
> +    private List<UserLotto> userLotto = new ArrayList<>();
1. User 에서 Lotto를 @OnetoMany 로 단방향 매핑: 한 User에 여러 Lotto가 속함
2. Lotto에서 User를 @ManyToOne 로 단방향 매핑: 여러 Lotto가 한 User에 속함
여러개의 Lotto가 User 한명에게 사용될 수 있음, 하나의 엔티티에서만 다른 엔티티를 참조하는 방식
3. User, Lotto에서 각각 양방향 매핑:
User 객체에서 자신의 Lotto를 조회하거나 Lotto 객체에서 User  조회할 수 있다.  데이터 간의 연관성을 양쪽에서 모두 사용하고자 할 때 사용한다.

2024-08-11 12:23 UTC, Hheojiwon commented on mission-lotto/src/main/java/com/lotto/entity/UserLotto.java
> +    @ElementCollection
데이터베이스는 컬렉션을 저장할 수 없기 때문에 @ElementCollection을 사용해서 별도의 테이블을 만들어서 저장해야 합ㄴ다!

2024-08-11 12:23 UTC, Hheojiwon commented on mission-lotto/src/main/java/com/lotto/entity/UserLotto.java
> +    @GeneratedValue
수정했습니다..!

2024-08-11 12:23 UTC, Hheojiwon commented on mission-lotto/src/main/java/com/lotto/repository/LottoRepository.java
> +    List<UserLotto> findByUser_UserName(String userName);
넵!! 수정했습니다

2024-08-11 12:24 UTC, Hheojiwon commented on mission-lotto/src/main/java/com/lotto/service/LottoService.java
> +        checkUserName(user == null);
Optional 활용해서 수정했습니다!

2024-08-11 12:25 UTC, Hheojiwon commented on mission-lotto/src/main/java/com/lotto/service/LottoService.java
> +        validateMoney(user, price);
넵!! 도메인 로직으로 리팩토링 하였습니다

2024-08-11 12:34 UTC, Hheojiwon commented on mission-lotto/src/main/java/com/lotto/service/LottoService.java
> +public class LottoService {
@Transactional 에노테이션을 붙인 메서드를 실행할 때 스프링은 트랜잭션을 시작하고, 메서드가 정상적으로 종료되면 트랜잭션을 commit 하고, 예외가 발생하면 트랜잭션을 rollback한다.
즉, 비정상적 종료로 인한 rollback이 발생할 경우에는 트랜젝션의 일부 작업만 데이터베이스에 반영되는 것을 방지해 데이터 일관성을 유지할 수 있다. 

생성 원리: 실행하는 시점에 proxy 생성에 필요한 클래스들이 자동으로 활성화된다. 
따라서 클라이언트 request를 보내면 @Transactionl이 적용된 메서드에 대한 트랜잭션 처리가 가능해진다.

속성 readonly=true 를 설정하게 되면 JPA는 해당 트랜젝션 내에서 조회하는 엔티티를 조회용으로 인식한다. (예상치 못한 수정 방지, 메모리 절약 가능) 

JPA에서는 트랜잭션이 끝나는 시점에 변화가 생긴 모든 엔티티들을 데이터베이스에 자동으로 반영해준다. 
Transactional 어노테이션을 붙여주면 상태 변경 검사를 하게 되고, 데이터 베이스에 commit을 해서 수정된 사항을 save 없이도 반영할 수 있도록 한다.
(transaction이 commit 될 때 상태 변경 검사가 이루어짐)

학습했습니다!

2024-08-11 12:35 UTC, Hheojiwon commented on mission-lotto/src/main/java/com/lotto/service/LottoService.java
> +        }
수정했습니다!

2024-08-11 12:41 UTC, Hheojiwon commented on mission-lotto/src/main/java/com/lotto/service/LottoService.java
> +        checkUserName(!userRepository.existsByUserName(name));
넵!! 수정했습니다

2024-08-11 13:01 UTC, Hheojiwon commented on mission-lotto/src/main/java/com/lotto/service/LottoService.java
> +        };
넵 수정했습니다

2024-08-11 13:01 UTC, Hheojiwon commented on mission-lotto/src/main/java/com/lotto/service/UserService.java
> +        }
수정했습니다!!

2024-08-11 13:12 UTC, Hheojiwon commented on mission-lotto/src/main/java/com/lotto/service/UserService.java
> +    }
넵 관련 내용 학습하겠습니다!

2024-08-11 13:27 UTC, Hheojiwon commented on mission-lotto/src/test/java/com/lotto/LottoServiceTest.java
> +    @Transactional
테스트 격리란?
- 테스트 간의 영향을 끼치지 않도록 하는 테스트 방법
- @Transactional 어노테이션을 사용해서, 테스트마다 롤백시켜 DB에 커밋이 되지 않게끔 격리 할 수 있다. 
- @SpringBootTest 의 webEnvironment 속성을 RANDOM_PORT로 설정하여 컨텍스트를 초기화여 격리할 수 있다. 

### @SpringBootTest 어노테이션 속성

WebEnvironment 속성
- WebEnvironment.MOCK : 아무런 설정이 없을 시 적용되는 디폴트 설정이다. mock 서블릿 환경으로 내장톰캣이 구동 X
- WebEnvironment.RANDOM_PORT : 스프링부트를 직접 구동시킨 것처럼 내장톰캣이 구동되나 랜덤포트로 구동된다.
- WebEnvironment.DEFINED_PORT : 정의된 포트로 내장톰캣이 구동된다.
- WebEnvironment.NONE : 일반적인 ApplicationContext를 로드하며 아무런 서블릿 환경을 구성하지 않는다


- classes: 속성을 통해 빈을 생성하는 클래스 지정 할 수 있다. 정의하지 않으면 프로젝트의 모든 빈을 등록한다. 
- properties: 테스트에 필요한 의존성 추가

학습했습니다!

2024-08-11 13:40 UTC, Hheojiwon commented on mission-lotto/src/main/java/com/lotto/controller/LottoController.java
> +    @GetMapping("/result")
### HTTP Method
클라이언트와 서버 사이에 이루어지는 Request와 Response 데이터를 전송하는 방식
GET : 조회 (서버로부터 데이터를 취득한다.)
POST : 등록 (서버에 데이터를 추가, 작성한다.)
PUT : 수정 (서버의 데이터를 갱신한다.)
DELETE : 삭제 (서버의 데이터를 삭제한다.)
HEAD : 서버 리소스의 헤더 (get과 동일하지만 서버에서 body를 return 하지 않음)
CONNECT : 프록시 동작의 터널 접속을 변경
OPTIONS : 리소스가 지원하고 있는 메소드의 취득


RESTful API의 설계 목표중 중 하나는 사용의 단순성과 성능을 최적화 하는 것
클라이언트가 서버의 작업에 영향을 미치지 않음!!
시스템을 무상태로 만들어, 각 요청이 독립적이고 서로 영향을 주지 않도록 한다. 

 
### url 설계 원칙
1. 명확하고 직관적인 구조 사용

2. 명사 사용과 복수형 표현
리소스에 대한 대표명으로 명사를 사용해야 한다. 
여러 사용자를 나타낼 때는 /users와 같이 복수형을 사용하고, 단일 리소스에는 /users/{id}와 같이 구체적인 식별자를 사용한다. 

3. CRUD 기능을 HTTP 메서드에 매핑
URL을 통해 특정 동작을 명시하지 않아도 된다. 
GET /users는 사용자 목록 조회
POST /users는 새로운 사용자 생성

4. 경로 변수의 사용 최소화
경로 변수는 필요한 경우에만 사용해야 하며, URL이 복잡해지는 것을 방지해야 한다. 
 
5. 쿼리 매개변수로 필터링, 정렬 및 페이징 지원
리소스 컬렉션에 대한 접근 시 쿼리 매개변수를 사용하여 이를 지원한다.

6. 밑줄, 대문자는 사용하지 않아야 한다

2024-08-11 13:58 UTC, Hheojiwon commented on mission-lotto/src/test/java/com/lotto/LottoServiceTest.java
> +public class LottoServiceTest {
1.
단위 테스트: 개별 모듈이나 메서드가 동작하는지 확인하는 테스트
통합 테스트: 서로 다른 모듈이나 컴포넌트가 함께 올바르게 동작하는지 확인하는 테스트

2.
Stub
인스턴스화 하여 구현한 가짜 객체 Dummy(객체를 전달하지만 실제로 사용 X)를 이용해 실제로 동작하는 것처럼 보이게 만든다.
호출 시 반환되는 값을 미리 정의하여 반환 수행
-> 메소드가 수행된 후, 객체의 상태를 확인하여 올바르게 동작했는지를 확인 (상태 검증)

Mock
내용에 따라 동작하도록 프로그래밍 된 객체이다. 
-> 메소드의 리턴 값으로 판단할 수 없는 경우, 특정 동작을 수행하는지 확인 (행위 검증)

2024-08-11 13:58 UTC, Hheojiwon commented on mission-lotto/src/main/java/com/lotto/controller/LottoController.java
> +        boolean isWinning = lottoService.isWinningLotto(userLotto.getLottoNumbers(), winNumbers);
LottoJudge 클래스 활용해서 수정하였습ㄴ다.!

2024-08-12 05:16 UTC, sosow0212 approved these changes
수고하셨습니다! 지연될 것 같아서 여기서 Approve 하겠습니다!
리뷰 내용 꼭 학습해주시고 다음 미션 때부터 적용해주세요~ 곧 프로젝트 하실텐데 꼭 알아야하는 내용들이니 천천히 제출하셔도 되니 한 번 잡고 가시는 것이 좋을 것 같습니다.

2024-08-12 05:16 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/controller/LottoController.java
> +    public ResponseEntity<UserResultResponse> getTargetLottoResult(@PathVariable(name = "lottoId") Long lottoId, @RequestParam(name = "winNumbers") List<Integer> winNumbers) {
다른 곳도 그렇고 winNumbers를 외부에서 받아오는 방식으로 구현해주셨네요!
다른 제약이 없어서 해당 방식으로 진행해도 상관은 없지만, 저 같으면 관리자 페이지에서 1회 생성해준 후 DB에 저장한 후에 파람으로 당첨번호가 아닌 사용자가 입력한 번호 혹은 lottoId만 넘어오면 알아서 비교할 수 있도록 할 것 같습니다.
프론트 측에서도 관리하기 좋을 것 같고요! 이건 참고만 해주세요~

2024-08-12 05:16 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/domain/LottoJudge.java
> +    private final List<Integer> winNumbers;
winNumbers가 일급컬렉션인데 `class Some { List<Integer> winNumbers }` 이렇게 묶고 `LottoJudge { UserLotto, Some }` 이렇게 하는 게 관리 차원에서 더 좋을 것 같습니다

2024-08-12 05:16 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/domain/LottoRandomNumber.java
> +@Service
@Service와 @Component의 차이는 무엇일까요? 여기엔 어떤 것을 넣는게 적절할지 고민해보시면 좋을 것 같습니다
@Controller, @Service, @Repository 와 같은 빈들은 모두 @Component로 이뤄져있습니다!

2024-08-12 05:16 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/domain/LottoRandomNumber.java
> +        return lottoNumbers;
이 부분도 행위 별로 메서드 분리를 해주면 더 좋을 것 같아요!

2024-08-12 05:16 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/domain/LottoRank.java
> +        }
인덴트 2이상이라 요구사항이 맞지 않습니다!

2024-08-12 05:16 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/domain/LottoRank.java
> +    }
```suggestion
        if (lottoRank == NONE) {
            return false;
        } else {
            return true;
         }
    }
```

else문이 나쁘다는 건 아니지만 예상치 못한 값이 나올 수 있기 때문에 가급적이면 지양해주세요!

if() { return false}
return true;

이렇게 해줘도 좋을 것 같습니다!

2024-08-12 05:16 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/entity/User.java
> +    private List<UserLotto> userLotto = new ArrayList<>();
매핑시에 의존과 의존의 최소화에 대해서 학습해보시면 좋을 것 같습니다
다음 미션 때에는 매핑시에 고민을하고 어떻게 매핑하셨는지 왜 그렇게 하셨는지 같이 남겨주세요!

2024-08-12 05:16 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/entity/User.java
> +        int price = ticketCount * 1000;
1000 값도 상수화 해주면 좋을 것 같습니다!

2024-08-12 05:16 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/entity/User.java
> +            throw new InsufficientFundsException();
다음 미션 땐 @RestControllerAdvice 학습하셔서 전역 예외 처리 도전해보세요!
그리고 스프링에서의 예외 처리 방법과 어떤 예외를 상속 받는지? @ConrollerAdvice, ExceptionHandler 등등은 어떻게 작동되는지도 학습하셔야합니다!

2024-08-12 05:16 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/service/LottoService.java
> +public class LottoService {
다음부터 메서드 레벨에 적절한 트랜잭션을 붙여주세요! 지금은 JPA와 mysql or h2(mysql Ver)을 사용하기 때문에 해당 기능들을 이용할 수 있습니다!

2024-08-12 05:16 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/service/LottoService.java
> +        }
이 지점에서 어떤 이유로 실패한다면 (ex. 네트워크 지연으로 Exception 발생 or etc...) 유저의 돈은 빠져나가지 않았는데 로또 구매는 된 걸로 기록될 것 같습니다

실제로 이런 이유 때문에 트랜잭션에 대해 많은 학습을 하고 여러 상황에 대해 고민해보는 연습이 필요합니다!
또한 JPA를 쓰고 있다면 트랜잭션 어노테이션이 있을 때 밑에 userRepository.save()를 하지 않아도 변경 감지 때문에 update가 됩니다! 매핑을 했을 때 `영속성` 전파 레벨도 있는데 이것도 꼭 공부하셔야합니다!

영속성이라는 용어가 낯설 수 있는데, 반드시 JPA를 사용하신다면 꼭 알아야하는 개념이고 영속성과 더불어 더티체킹, 일차캐싱 등등 JPA의 특징들이 전파레벨에 따라 매핑되는 테이블에도 적용이 되는 문제이다보니 꼭 학습하셔야합니다

2024-08-12 05:46 UTC, merged