Board/step1 제출입니다!
sosow0212/2024-mju-mentoring-spring-2 pull request #12
Opened 2024-08-19 09:27 UTC by moonwhistle

8/19 

로그인 관련 부분 확인받고 싶어서 pr 올립니다!!

* 쿠키 로그인을 구현하였고, 이처럼 다른 로그인도 작성하면 될지 코드리뷰 부탁드립니다 멘토님..!
* login 메서드 :  1. 로그인 아이디로 멤버를 가져옵니다. (멤버가 없을 시 예외 처리 하였습니다.) 2. 만일 멤버가 있다면 가져온 멤버를 통해 비밀번호 확인도 진행합니다. (비밀번호가 틀리다면 예외처리 하였습니다.) 3. 쿠키를 생성합니다. 4. 쿠키를 데베에 저장합니다.
* logout 메서드 : 1. 쿠키 이름은 MemberId 로 정해져있으므로 쿠키 초기화를 통해 쿠키를 삭제해줍니다. 2. HttpServletRequest에서 request.getCookie() 메서드를 통해 모든 쿠키를 가져오고 memberId 에 해당하는 쿠키를 가져와 데베에서 삭제합니다.
* logout 메서드에서 질문 사항이 있습니다. logout 의 경우 HttpServeletRequest 를 통해 가져오기 때문에 해당 api테스트 시 오류 나는 것이 정상일까요??(로그인 유저가 2 명 있을 경우) - 클라이언트의 페이지에서는 쿠키를 가지고 있는 유저가 한 명이기에 제대로 작동한다고 생각하는데 다른 방식으로 작성해야 될까요?? 
* 쿠키를 데베에 저장하고자 하는 이유는 다음과 같습니다. 사용자가 쿠키를 가지고 있다가 서버에 요청을 보내면서 쿠키를 같이 보내게 되는데 , 이때 서버가 쿠키에 대한 정보를 가지고 있지 않으면 확인 불가능 하므로 쿠키 정보 데베를 따로 관리하도록 코드 작성하였습니다. 이와 관련해서 인증 부분에서 getCookie 메서드가 사용될 수 있다고 판단하여 public으로 설정하였습니다.
* 쿠키에 아이디 값을 넣어주게 되니 보안에 취약하다는 것을 깨달았습니다. 그래서 세션값을 쿠키에 넣어 세션 로그인을 진행하려고 하는데 이 방식이 맞을까요?? 왜냐하면 세션을 생성해주어도 쿠키에 담아서 보내지 않으면 서버는 알 수 없지 않나요..?? 
* jwt 의 경우 아직 감이 안 잡힌 상태인 것 같습니다. 조금 더 많이 찾아보고 잘 구현해 보겠습니다!!

2024-08-19 10:20 UTC, sosow0212 requested changes
아주 적절한 고민을 하고 계신 것 같아서 좋습니다!
리뷰 내용 보시면서 세션까지 진행해보시면 궁금하셨던 내용들에 대해 많이 배우실 수 있을 것 같습니다 ㅎㅎ 코드가 굉장히 깔끔해져서 보기가 좋네요 수고하셨습니다 👍
질문하신 내용들을 봤는데 저도 처음에 많이 했던 고민들이었습니다. 로그인이라는 내용 자체가 Http에서 stateless, connectinoless와 같은 특징 때문에 우리가 볼 때 납득되기 힘든 부분이 많습니다. Http 관점에서도 고민해보시면 충분히 해결하실 고민들이라 질문 형식으로 리뷰 남겨봤습니다 🙇🏻‍♂️

2024-08-19 10:20 UTC, sosow0212 commented on mission-board/src/main/java/com/board/global/exception/exceptionhandler/dto/ErrorResponse.java
> +public record ErrorResponse(int status, String message) {
여기 int status가 아닌 HttpStatus 자체가 와도 괜찮을 것 같습니다!
그리고 body는 message만 보내도 되고 message와 함께 `A001` 이런 커스텀 코드 번호를 같이 주는게 좋을 것 같은데 이 부분은 선택적으로 사용하시면 됩니다 ㅎㅎ

2024-08-19 10:20 UTC, sosow0212 commented on mission-board/src/main/java/com/board/login/controller/LoginController.java
> +        log.info(loginResponse.memNickName()+"님 로그인 성공.");
`{ }` 를 활용해서 변수를 바인딩 할 수도 있습니다!
ex. `log.info("{}님 로그인 성공", loginResponse.memNickname)`

memNickname 같은 것도 축약 말고 풀어서 써주세요!

2024-08-19 10:20 UTC, sosow0212 commented on mission-board/src/main/java/com/board/login/domain/CookieEntity.java
> +    protected CookieEntity() {
👍

2024-08-19 10:20 UTC, sosow0212 commented on mission-board/src/main/java/com/board/login/controller/LoginController.java
> +        log.info(loginResponse.memNickName()+"님 로그인 성공.");
++ 로그인 한 유저가 들어왔을 때 요청을 처리할 수 있는 기능이 있다고 하면 (ex. 유저 이름 수정)
이때 로그인 정보는 어떻게 받을 수 있을까요?

2024-08-19 10:20 UTC, sosow0212 commented on mission-board/src/main/java/com/board/login/domain/CookieEntity.java
> +public class CookieEntity {
이 방법도 좋지만 스케일아웃 되지 않은 단일 서버이니 이런 상황에서는 자바 Map 자료구조를 사용해도 괜찮을 것 같아요!

2024-08-19 10:20 UTC, sosow0212 commented on mission-board/src/main/java/com/board/login/service/CookieLoginService.java
> +        }
~.findBy~(blabla)
         .orElseThrow(Exception)

이렇게 해도 될 것 같아요!

2024-08-19 10:20 UTC, sosow0212 commented on mission-board/src/main/java/com/board/login/service/CookieLoginService.java
> +        }
이것도 도메인의 역할로 캡슐화 해줄 수 있을 것 같습니다

2024-08-19 10:20 UTC, sosow0212 commented on mission-board/src/main/java/com/board/login/service/CookieLoginService.java
> +    private Cookie createCookie(HttpServletResponse response, String cookieContent) {
쿠키를 만들고 제거하는 전략 즉 책임을 어디서 해주는 것이 적절할까요? 새로운 클래스를 만드는 게 좋을까요? 아니면 어떻게 하는게 좋을까요! 레이어드 아키텍처 관점에서 고민 해보면 좋을 것 같습니다!
타당한 근거와 함께 고민해본 내용을 공유해주셨으면 좋겠습니다 :)

2024-08-19 10:20 UTC, sosow0212 commented on mission-board/src/main/java/com/board/login/service/LoginService.java
> +public interface LoginService {
interface로 분리해주셨는데 그 이유가 있을까요? 다른 LoginServiceImpl이 들어올 일이 있을까요?!
++ 혹시 세션이나 다른 것도 구현한다면 타당한 이유 같습니다 ㅎㅎ

2024-08-19 10:20 UTC, sosow0212 commented on mission-board/src/main/java/com/board/member/controller/MemberController.java
> +public class MemberController {
일치하지 않는 api 같네요! 확인 부탁드립니다

2024-08-19 10:20 UTC, sosow0212 commented on mission-board/src/main/java/com/board/member/domain/Member.java
> +    }
이것도 Lombok을 이용해서 어노테이션화 시킬 수 있을 것 같습니다!

2024-08-19 10:20 UTC, sosow0212 commented on mission-board/src/main/java/com/board/member/domain/Member.java
> +    @Column
이 컬럼도 그렇고 null 값을 막을 방법은 없을까요?

2024-08-19 10:20 UTC, sosow0212 commented on mission-board/src/main/java/com/board/member/mapper/MemberMapper.java
> +public class MemberMapper {
Mapper를 쓸 때와 Request.get~()를 통해 서비스단에서 Member를 생성해주는 것과 무슨 차이가 있을까요?
의존 관계에서의 차이와 사용할 때 고민했던 점들이 궁금합니다!

2024-08-19 10:20 UTC, sosow0212 commented on mission-board/src/main/java/com/board/login/service/CookieLoginService.java
> +    }
이것도 롬복의 기능 사용해서 생략해도 될 것 같습니다!

2024-08-19 10:20 UTC, sosow0212 commented on mission-board/src/main/java/com/board/login/service/CookieLoginService.java
> +        cookieRemove.setPath("/board");
해당 코드를 만드신 이유가 궁금합니다!
전체적으로 쿠키에서의 로그인 방식 흐름은 어떻게 된다고 생각하시나요?
또한 쿠키 방식 로그인의 문제점은 무엇일까요?

2024-08-19 10:20 UTC, sosow0212 commented on mission-board/src/main/java/com/board/login/domain/CookieEntity.java
> +public class CookieEntity {
사용자가 요청을 보낼때
cookie {"username" : "jay", "password" : "1234"}
이런식으로 보내도 해당 테이블이 필요할까요?

2024-08-19 10:20 UTC, sosow0212 commented on mission-board/생각.md
> +하나의 인터페이스 생성 -> 3개 클래스 구현(쿠키, 세션, 토큰)
👍

2024-08-19 15:01 UTC, moonwhistle commented on mission-board/src/main/java/com/board/global/exception/exceptionhandler/dto/ErrorResponse.java
> +public record ErrorResponse(int status, String message) {
제가 임의로 400, 401 지정해주는 것보다 HttpStatus 코드를 넣어 더 확실성 있게 에러 코드 작성할 수 있다는 생각을 처음 해본 것 같습니다..! 커스텀 코드 번호도 만들어서 리팩터링 하였습니다!! 진짜 어떤 오류인지 한 눈에 알아볼 수 있어서 훨씬 좋은 것 같습니다. ㅎㅎ

2024-08-21 11:17 UTC, moonwhistle commented on mission-board/src/main/java/com/board/login/controller/LoginController.java
> +        log.info(loginResponse.memNickName()+"님 로그인 성공.");
1. {} 활용하여 변수 바인딩 하였고, 축약해서 쓴 변수명도 다 풀어썼습니다!

2. 로그인 정보를 받는 방법은 두 가지가 있다고 생각합니다. 
(1) 쿠키 값이나 , 세션 값 혹은 토큰 값에서 사용자 정보를 읽어온 후 이러한 정보들을 관리하는 클래스에서 일치하는 값을 읽어와 해당 로그인 정보를 받을 수 있다고 생각합니다! 
(2) 보안에 취약하고 정말 정말 쓸 필요가 없는 기능이지만, 엔트포인트에 pathvariable을 통해 userid(pk) 값을 넣어주고, userid를 받아와 데베에서 조회하여 로그인 정보를 받아올 수 있다고 생각합니다

2024-08-21 11:58 UTC, moonwhistle commented on mission-board/src/main/java/com/board/login/service/CookieLoginService.java
> +        }
해당 방식으로 리팩터링 진행하였습니다.!

2024-08-21 11:58 UTC, moonwhistle commented on mission-board/src/main/java/com/board/login/service/CookieLoginService.java
> +        }
비밀번호 체크 메서드 도메인 역할로 캡슐화 진행하였습니다!

2024-08-21 12:56 UTC, moonwhistle commented on mission-board/src/main/java/com/board/login/service/CookieLoginService.java
> +    private Cookie createCookie(HttpServletResponse response, String cookieContent) {
해당 리뷰를 통해 레이어드 아키텍쳐에 대해 조금 더 공부해 볼 수 있었습니다.
공부를 통해 쿠키를 만들고 제거하는 책임은 컨트롤러 레이어에서 하는 것이 적절하다고 판단하였습니다!
왜냐하면 컨트롤러(프레젠테이션) 레이어는 http 요청과 응답에 대한 로직에 관한 책임을 가지고 있는데, 쿠키와 세션 모두 http 통신에 관한 로직이므로 컨트롤러에서 작성하는 것이 맞다고 판단하였습니다.
인증과 인가의 경우는 비지니스 로직이므로 서비스 층에서 작성하는 것이 좋을 것 같다는 생각도 들었습니다.

결론은 컨트롤러 레이어에서 쿠키 생성 및 제거를 할 수 있도록 리팩터링 하였습니다!

2024-08-21 12:56 UTC, moonwhistle commented on mission-board/src/main/java/com/board/login/service/LoginService.java
> +public interface LoginService {
다른 것도 구현해보겠습니다!!

2024-08-21 12:56 UTC, moonwhistle commented on mission-board/src/main/java/com/board/member/controller/MemberController.java
> +public class MemberController {
확인하여 리팩터링 진행하였습니다!

2024-08-21 13:00 UTC, moonwhistle commented on mission-board/src/main/java/com/board/login/domain/CookieEntity.java
> +public class CookieEntity {
Map 구조를 사용하여 쿠키를 저장하도록 구현하긴 하였는데, 일급컬렉션을 지키기도 애매하고 뭔가 좀 허술하다는 느낌이 듭니다. 다음 코드리뷰때 확인 한 번 해주시면 감사하겠습니다!

2024-08-21 13:00 UTC, moonwhistle commented on mission-board/src/main/java/com/board/member/domain/Member.java
> +    }
Lombok사용하여 어노테이션화 진행하였습니다!

2024-08-21 13:03 UTC, moonwhistle commented on mission-board/src/main/java/com/board/member/domain/Member.java
> +    @Column
@NotNull 어노테이션을 사용하여 null 값을 막을 수 있습니다!

2024-08-21 13:08 UTC, moonwhistle commented on mission-board/src/main/java/com/board/login/service/CookieLoginService.java
> +    }
@RequiredArgsConstructor
   - final 필드 또는 @NonNull 필드를 포함하는 생성자를 자동으로 생성.
   - 주로 final 필드에 자주 사용

 @AllArgsConstructor
   - 모든 필드를 매개변수로 받는 생성자를 자동으로 생성
   
   
    @AllArgsConstructor 사용하였습니다!

2024-08-21 19:00 UTC, moonwhistle commented on mission-board/src/main/java/com/board/login/service/CookieLoginService.java
> +        cookieRemove.setPath("/board");
제가 위와 같은 코드를 만든 이유는 쿠키를 초기화하는 방식으로 생성하였던 쿠키를 삭제해주기 위해 저 코드를 만들었습니다!!

쿠키에서의 전제척인 로그인 흐름은 다음과 같습니다.
1. 서버가 쿠키를 생성: 클라이언트(웹 브라우저)가 서버에 요청을 보내면, 서버는 응답에 쿠키를 포함시킴. 이 쿠키는 Set-Cookie라는 HTTP 헤더에 포함되어 전달.
2. 클라이언트가 쿠키를 저장: 브라우저는 서버로부터 받은 쿠키를 클라이언트의 로컬 스토리지(브라우저의 쿠키 저장소)에 저장. 쿠키에는 이름, 값, 만료 시간, 경로 등의 정보가 포함되어 있음.
3. 클라이언트가 동일한 서버에 요청을 보낼 때, 브라우저는 해당 요청에 자동으로 저장된 쿠키를 포함시켜서 같이 보냄. => HTTP 요청의 Cookie 헤더에 쿠키 정보가 포함되어 서버로 전달.
4. 서버는 클라이언트가 보낸 쿠키를 읽고, 쿠키의 값을 기반으로 사용자 식별.
5.  쿠키에는 만료 시간이 설정할 수 있음. 만료 시간이 지나면, 브라우저는 해당 쿠키를 자동으로 삭제. 혹은  브라우저 설정을 통해 수동으로 쿠키를 삭제 가능.

쿠키 로그인의 문제점은 다음과 같습니다.
* 쿠키 문제점
  * 쿠키 값을 임의대로 변경할 수 있음
  * 쿠키에 보관된 정보를 타인이 훔쳐갈 수 있음
  * 한 번 도용된 쿠키 정보는 계속 악용될 수 있음

* 쿠키는 탈취 문제가 제일 큼. 안그래도 쿠키에 정보 변경 마음대로 할 수 있는데, Http로 전송되는 쿠키의 경우 탈취당하여 개인정보 빼앗기기가 쉽다.
  * 그래서 나온 방안 -> 쿠키에 세션 정보 담아서 보냄 : 세션 로그인

2024-08-21 19:04 UTC, moonwhistle commented on mission-board/src/main/java/com/board/member/mapper/MemberMapper.java
> +public class MemberMapper {
의존을 하고 안하고의 차이가 생각보다 크다는 것을 느꼈기에 mapper를 사용하게 되었습니다.

mapper 를 사용하지 않을 경우, 수정 사항이 생기면 인자 하나 하나 바꿔줘야 하는데 이 작업을 데베와 상호작용하는 도메인층에서 하게 되니까 위험성이 있다고 느꼈습니다. 그리고, 테스트를 하거나 로직을 구현할 때 객체를 바로 집어넣는 것이 아닌, 인자를 하나하나 넣어줘야 하기에 이 과정에서 실수가 많이 생길 수 있다는 생각이 들었습니다.
그래서 mapper를 따로 구현하여 코드를 작성하게 되었고, 객체만 집어넣어주면 mapper에서 알아서 반환이 되도록 코드를 작성했기에 위와 같은 문제점들을 해결할 수 있었습니다.

2024-08-21 19:06 UTC, moonwhistle commented on mission-board/src/main/java/com/board/login/domain/CookieEntity.java
> +public class CookieEntity {
로그인 정보를 쿠키에 넣어준다는 말씀이실까요..?? 만일 그렇다면 해당 테이블을 작성 할 필요가 없을 것 같습니다! 해당 정보들은 유저 데베에 이미 저장되어 있기 때문입니다. !!

2024-08-26 15:16 UTC, sosow0212 approved these changes
큰 문제가 없는 것 같아서 1차적으로 Approve 하도록 하겠습니다! 답변 보시고 일부 코드 다듬어보시고 2차 제출 때 jwt와 같이 제출해주시면 그때 더 자세히 각 방법에 대해 토론해보면 좋을 것 같습니다 ㅎㅎ 질문사항에 대해선 카톡 답변으로 남기겠습니다! 추가적으로 궁금한 점이 있다면 연락주세요 👍

2024-08-26 15:16 UTC, sosow0212 commented on mission-board/src/main/java/com/board/article/domain/Article.java
> +
```suggestion
```

2024-08-26 15:16 UTC, sosow0212 commented on mission-board/src/main/java/com/board/article/domain/Article.java
> +    private String content;
```suggestion
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "memberId")
    private Member member;
    
    @Column
    private String title;
    
    @Column
    private String content;
```

nullable 속성도 추가해주면 좋을 것 같아요 ㅎㅎ

2024-08-26 15:16 UTC, sosow0212 commented on mission-board/src/main/java/com/board/article/domain/Article.java
> +    }
프론트단에서 업데이트할 때

title, content,... 정보를 모두 보내준다면 기존 값은 그대로 저장되고 바뀐 값은 변경될 것 같아요!
updateContent(Article updatedArticle) 이런 식으로 해서 해주는 것도 좋을 것 같습니다

2024-08-26 15:16 UTC, sosow0212 commented on mission-board/src/main/java/com/board/article/mapper/ArticleMapper.java
> +public class ArticleMapper {
Mapper를 사용하는 이유가 무엇인가요? dto에서 해주는 것과는 무엇이 다를까요? 해당 방식에선 불필요한 의존이 생기지 않나요?!

2024-08-26 15:16 UTC, sosow0212 commented on mission-board/src/main/java/com/board/article/service/ArticleFindByArticleId.java
> +public interface ArticleFindByArticleId {
조회 인터페이스인가요? 왜 해당 인터페이스를 선언하셨고, 이를 Comment에서 사용하는데 의존이 발생하는 것 같아요

2024-08-26 15:16 UTC, sosow0212 commented on mission-board/src/main/java/com/board/article/service/ArticleService.java
> +        checkArticleExist(articles);
메서드 순서 맞춰주세요!

2024-08-26 15:16 UTC, sosow0212 commented on mission-board/src/main/java/com/board/article/service/ArticleService.java
> +    }
아티클이 없다면 서버에서 예외를 내려줘도 되지만 프론트에서 유연하게 처리할 수 있도록 빈 리스트를 반환해줘도 괜찮을 것 같습니다!
findById 같은 경우 없다면 null 값이지만, List에서는 빈리스트도 반환이 되니깐요!

2024-08-26 15:16 UTC, sosow0212 commented on mission-board/src/main/java/com/board/article/service/ArticleService.java
> +        Article article = checkRightAboutArticle(articleId, member);
이경우 트랜잭션은 readonly=true가 될까요? 아니면 false가 될까요? 이번 기회에 프록시와 트랜잭션 작동에 대해 학습 해보시면 좋을 것 같습니다.

2024-08-26 15:16 UTC, sosow0212 commented on mission-board/src/main/java/com/board/article/service/ArticleService.java
> +        if (!member.isMemberArticle(article.getMember().getId())) {
같은 멤버인지 조회하는 건 다른 관심사들이 추가되어도 똑같이 쓸 수 있을 것 같습니다.

isMemberArticle 보다는 isSameMember()라는 네이밍이 범용적으로 쓸 수 있을 것 같습니다

2024-08-26 15:16 UTC, sosow0212 commented on mission-board/src/main/java/com/board/comment/controller/CommentController.java
> +    @GetMapping("/members/comments")
자원을 표기하려면
```suggestion
    @GetMapping("/members/me/comments")
```

이런식으로 해도 좋을 것 같습니다 ㅎㅎ

2024-08-26 15:16 UTC, sosow0212 commented on mission-board/src/main/java/com/board/comment/service/ArticleFindByArticleIdService.java
> +        return articleRepository.findById(articleId).orElseThrow(() -> new CustomException(CustomErrorCode.NOT_EXIST_ARTICLE));
1. 객체지향 생활체조 규칙인 한 줄에 점 하나 규칙 지켜주세요!
2. 해당 클래스가 유의미할까요? 다른 방식으로 구현해보는 건 어떨까요? 의존과 관련해서 고민해보시면 도움이 될 것 같습니다

2024-08-26 15:16 UTC, sosow0212 commented on mission-board/src/main/java/com/board/login/domain/CookieStorage.java
> +    private final static Map<Long, Cookie> cookies = new HashMap<>();
동시성 문제가 무엇일까요? 현재에선 발생할까요? 발생한다면 Concurrent 자료구조는 무엇일까요!
Map을 그대로 사용하셨는데 스프링에선 하나의 요청에 대해 하나의 스레드를 할당하는 방식입니다. 이와 연관지어서 고민해보시면 좋을 것 같습니다!

2024-08-26 15:16 UTC, sosow0212 commented on mission-board/src/main/java/com/board/login/resolver/LoginArgumentResolver.java
> +        return sessionLoginService.findMemberBySession(session);
Member를 바로 꺼내서 주지 말고 Long memberId 를 반환하고 서비스에서 필요에 따라 조회를 하든 다른 방식으로 써보는 건 어떨까요? 현재 방법도 나쁘지는 않지만 어차피 조회가 되어야하는 거 서비스로 id를 보낸다면 조금 더 다양하게 활용할 수 있지 않을까요? 혹은 member를 조회하지 않는 경우에는 불필요한 조회도 안할 수 있을 것 같아요

2024-08-26 15:16 UTC, sosow0212 commented on mission-board/src/main/java/com/board/login/service/CookieLoginService.java
> +        member.checkPassword(loginRequest.memberPassword());
캡슐화 좋습니다! 한줄에 점 하나만 지켜주세요!

2024-08-26 15:16 UTC, sosow0212 commented on mission-board/src/main/java/com/board/login/annotation/Login.java
> +public @interface Login {
고민에 대한 부분은 만약 해당 어노테이션이 전역에서 사용한다면 사바사지만, 저라면 src/main/java/com/board/global/annotation 안에 둘 것 같습니다!

2024-08-26 15:16 UTC, sosow0212 commented on mission-board/src/main/java/com/board/login/resolver/LoginArgumentResolver.java
> +public class LoginArgumentResolver implements HandlerMethodArgumentResolver {
Resolver도 전역에서 사용되는 것이라면 마찬가지로 global 안에 resolver로 둘 것 같습니다 ㅎㅎ

2024-08-26 15:16 UTC, merged

2024-08-29 18:12 UTC, moonwhistle commented on mission-board/src/main/java/com/board/article/domain/Article.java
> +
개행 수정하였습니다!

2024-08-29 18:13 UTC, moonwhistle commented on mission-board/src/main/java/com/board/article/domain/Article.java
> +    private String content;
@Nullable 속성 추가하였습니다!

2024-08-29 18:13 UTC, moonwhistle commented on mission-board/src/main/java/com/board/article/domain/Article.java
> +    }
한 번에 값 받아서 update할 수 있도록 메서드 수정하였습니다!

2024-08-29 18:15 UTC, moonwhistle commented on mission-board/src/main/java/com/board/article/service/ArticleService.java
> +    }
무조건 빈 값이면 예외를 던져주어야 하는 줄 알았는데 아니군요..... 빈 리스트 던져주도록 수정하였습니다!

2024-08-29 18:17 UTC, moonwhistle commented on mission-board/src/main/java/com/board/comment/controller/CommentController.java
> +    @GetMapping("/members/comments")
me 가 쓰일 수 있다는 것은 처음 알았습니다 감사합니다!

2024-08-29 18:53 UTC, moonwhistle commented on mission-board/src/main/java/com/board/login/annotation/Login.java
> +public @interface Login {
넵 감사합니다 ㅎㅎ !!

2024-08-29 18:54 UTC, moonwhistle commented on mission-board/src/main/java/com/board/login/resolver/LoginArgumentResolver.java
> +public class LoginArgumentResolver implements HandlerMethodArgumentResolver {
넵!!

2024-08-31 06:25 UTC, moonwhistle commented on mission-board/src/main/java/com/board/article/mapper/ArticleMapper.java
> +public class ArticleMapper {
mapper 를 사용하는 이유는 값을 하나 하나 넣어줄 때 발생할 수 있는 휴먼 에러도 줄일 수 있고, 코드 자체가 간결해 보일 수 있기에 사용합니다!! 
dto에서 변환해준다면 도메인+ 엔티티 섞어서 쓰는 클래스에도 변환 로직을 작성하여야 해서 도메인 로직을 줄이고자 매퍼를 설정한 이유도 있습니다! 
제가 작성한 코드에서는 불필요한 의존이 없다고 생각하는데, 혹시 있다면 알려주시면 감사하겠습니다!

2024-08-31 06:25 UTC, moonwhistle commented on mission-board/src/main/java/com/board/article/service/ArticleFindByArticleId.java
> +public interface ArticleFindByArticleId {
의존을 끊으려고 인터페이스 작성하였는데, 오히려 의존을 발생시킨 것 같습니다. 
이벤트 처리를 통해 의존 끊어냈습니다!

2024-08-31 06:26 UTC, moonwhistle commented on mission-board/src/main/java/com/board/article/service/ArticleService.java
> +        checkArticleExist(articles);
메서드 순서 맞춰주었습니다!

2024-08-31 07:02 UTC, moonwhistle commented on mission-board/src/main/java/com/board/article/service/ArticleService.java
> +        Article article = checkRightAboutArticle(articleId, member);
학습 진행하고 false로 리팩터링 하였습니다! 

## 트랜잭션과 프록시

1. 트랜잭션(Transaction): 트랜잭션은 데이터베이스에서 일련의 작업들이 모두 성공적으로 완료되거나, 하나라도 실패할 경우 전부 취소되는 것을 보장하는 메커니즘.
2. 프록시(Proxy): 프록시는 실제 객체를 감싸서 추가적인 기능을 제공하는 대리 객체. 스프링에서는 AOP(Aspect-Oriented Programming)를 구현하기 위해 프록시를 사용.

### 스프링 AOP와 프록시
* 스프링에서 AOP(Aspect-Oriented Programming)는 주로 프록시 기반으로 작동. AOP를 통해 특정 메서드의 전후에 공통 기능(ex) 로깅, 트랜잭션 관리)을 적용할 수 있다.

1. JDK 동적 프록시: 대상 객체가 인터페이스를 구현하고 있을 때 사용.
2. CGLIB 프록시: 대상 객체가 인터페이스를 구현하지 않고 있을 때 사용.

### 트랜잭션과 프록시의 관계
1. 프록시가 트랜잭션 관리: @Transactional이 적용된 메서드가 호출될 때, 스프링은 프록시 객체를 사용하여 해당 메서드를 가로챔. -> 프록시는 트랜잭션을 시작하고, 메서드를 실행한 뒤 결과에 따라 트랜잭션을 커밋하거나 롤백 진행.
   * ex) Service 클래스의 updateArticle 메서드에 @Transactional이 붙어 있다고 가정 : 클라이언트가 updateArticle을 호출하면, 실제로는 Service의 프록시 객체가 호출. -> 이 프록시는 트랜잭션을 시작한 후, 실제 Service 객체의 updateArticle 메서드를 호출. 메서드 실행이 끝나면 프록시는 트랜잭션을 커밋하거나, 예외가 발생하면 롤백.
2. 프록시 내부 동작의 한계:
   * 자기 호출(self-invocation) 문제: 프록시 객체 내부에서 동일 객체의 다른 메서드를 호출하는 경우, 이 호출은 프록시를 거치지 않고 직접 호출. 이 경우 트랜잭션이 적용되지 않을 수 있음.
   * 해결 방법: 코드 구조를 변경하거나, AopContext.currentProxy()를 사용해 프록시를 참조하여 트랜잭션이 적용되도록 할 수 있음. but 이 방법은 코드가 스프링 AOP에 강하게 결합됌.

### 결론
* 스프링에서 트랜잭션 관리는 주로 프록시를 통해 이루어짐.
* 프록시 객체가 메서드 호출을 가로채고, 트랜잭션을 시작, 커밋, 롤백 진행.
* 프록시는 실제 객체를 감싸서 AOP 기능(예: 트랜잭션)을 함.
* 자기 호출(self-invocation)은 프록시를 우회하기 때문에 트랜잭션이 적용되지 않을 수 있음.
* 즉, 스프링의 트랜잭션 관리는 프록시라는 대리 객체가 뒤에서 마법처럼 일을 처리해주는 방식. 트랜잭션이 필요한 작업이 있으면 프록시가 이를 가로채서 알아서 처리해주는 구조.

---
## AOP
### AOP(Aspect-Oriented Programming) 개념 
* AOP(Aspect-Oriented Programming, 관점 지향 프로그래밍)는 프로그램 실행 시 특정 로직을 모듈화하여 여러 클래스에서 공통적으로 사용될 수 있도록 하는 방법. 

1. Aspect(애스펙트)
   * 정의: 애스펙트는 여러 클래스에 걸쳐 있는 공통적인 관심사를 모듈화한 것.
   * 예시: 트랜잭션 관리, 로깅 등이 대표적인 예.
   * 스프링에서의 구현: 스프링에서는 애스펙트를 일반 클래스로 구현하거나 @Aspect 애너테이션을 사용하여 구현.
2. Join Point(조인 포인트)
   * 정의: 프로그램 실행 중 특정 시점, 예를 들어 메서드 실행이나 예외 처리 등을 의미.
   * 스프링에서의 조인 포인트: 스프링 AOP에서 조인 포인트는 항상 메서드 실행을 나타냄.
3. Advice(어드바이스)
   * 정의: 특정 조인 포인트에서 애스펙트가 취하는 행동.
   * 어드바이스의 종류:
     * Before: 메서드 실행 전에 실행되는 어드바이스.
     * After Returning: 메서드가 정상적으로 완료된 후 실행되는 어드바이스.
     * After Throwing: 메서드가 예외를 던진 후 실행되는 어드바이스.
     * After (Finally): 메서드의 종료 여부와 상관없이 항상 실행되는 어드바이스.
     * Around: 메서드 호출을 감싸서 실행 전후에 실행되며, 메서드 호출을 중단하거나 대체할 수 있는 가장 강력한 어드바이스.
4. Pointcut(포인트컷)
   * 정의: 조인 포인트를 매칭하는 조건(판별자).
   * 스프링에서의 포인트컷: 스프링은 기본적으로 AspectJ의 포인트컷 표현식을 사용. 포인트컷은 특정 메서드 실행에 대해 어드바이스를 실행할 지 여부를 결정.
5. Introduction(인트로덕션)
   * 정의: 기존 타입에 새로운 메서드나 필드를 선언하는 것.
   * 스프링에서의 인트로덕션: 스프링 AOP를 사용해 새로운 인터페이스와 구현을 지정된 객체에 추가할 수 있음.
6. Target Object(대상 객체)
   * 정의: 하나 이상의 애스펙트에 의해 조언을 받는 객체. "Advised Object"라고도 한다.
   * 스프링에서의 대상 객체: 항상 프록시된 객체.
7. AOP Proxy(프록시)
   * 정의: AOP 프레임워크가 애스펙트의 계약(어드바이스 메서드 실행 등)을 구현하기 위해 생성한 객체.
   * 스프링에서의 프록시: JDK 동적 프록시 또는 CGLIB 프록시가 있음.
8. Weaving(위빙)
   * 정의: 애스펙트를 다른 애플리케이션 타입이나 객체와 연결하여 조언된 객체를 생성하는 과정.
   * 스프링에서의 위빙: 런타임에 수행된다.
   * 스프링 AOP에서 제공하는 어드바이스 타입
     * Before Advice: 조인 포인트가 실행되기 전에 실행되는 어드바이스로, 조인 포인트의 실행을 막을 수 없다(예외를 던지는 경우 제외).
     * After Returning Advice: 조인 포인트가 정상적으로 완료된 후 실행.
     * After Throwing Advice: 메서드가 예외를 던지면 실행.
     * After (Finally) Advice: 조인 포인트가 정상적이든 예외적이든 관계없이 항상 실행.
     * Around Advice: 조인 포인트를 감싸는 어드바이스로, 메서드 호출 전후에 실행되며, 메서드 실행을 중단하거나 대체할 수 있음. 가장 강력한 어드바이스 타입.
### 스프링 AOP의 목표와 기능
* 순수 자바로 구현: 스프링 AOP는 순수 자바로 구현되며, 클래스 로더 계층을 제어할 필요가 없어 서블릿 컨테이너나 애플리케이션 서버에서 사용할 수 있음.
* 메서드 실행 조인 포인트만 지원: 스프링 AOP는 스프링 빈의 메서드 실행만을 조언할 수 있음. 필드 접근이나 업데이트 조인 포인트를 조언하려면 AspectJ와 같은 언어를 염두해야 함.
* 스프링 IoC와의 긴밀한 통합: 스프링 AOP는 스프링의 IoC 컨테이너와 긴밀하게 통합되어 있으며, 주로 엔터프라이즈 애플리케이션의 공통 문제를 해결하는 데 초점을 맞추고 있다.
* AspectJ와의 차별점: 스프링 AOP는 세밀한 객체(주로 도메인 객체)를 조언하는 데에는 적합하지 않다. AspectJ는 이러한 경우에 더 적합.
* 프록시 기반 프레임워크: 스프링 AOP는 프록시 기반. 이는 스프링 AOP가 프록시 객체를 통해 AOP 기능을 제공한다는 것을 의미.
* 스프링 AOP에서 프록시 선택
  * JDK 동적 프록시: 기본적으로 인터페이스를 구현한 객체에 대해 사용.
  * CGLIB 프록시: 인터페이스를 구현하지 않은 클래스에 대해 사용.
  * 프록시 선택 기준: 스프링 AOP는 기본적으로 JDK 동적 프록시를 사용하며, 인터페이스를 구현하지 않은 객체에 대해서만 CGLIB을 사용. 필요시 CGLIB을 강제로 사용할 수 있다.

### 결론
* 스프링 AOP는 엔터프라이즈 애플리케이션에서 발생하는 공통 문제를 해결하기 위해 AOP 개념을 이용하여, 메서드 실행 전후에 부가적인 로직을 삽입하는 기능을 제공. 이를 통해 로깅, 트랜잭션 관리와 같은 횡단 관심사를 효과적으로 처리할 수 있다. 
* 스프링 AOP는 주로 프록시 기반으로 동작하며, 인터페이스 기반 프록시와 클래스 기반 프록시(CGLIB)를 필요에 따라 선택적으로 사용할 수 있다.

2024-08-31 07:04 UTC, moonwhistle commented on mission-board/src/main/java/com/board/article/service/ArticleService.java
> +        if (!member.isMemberArticle(article.getMember().getId())) {
넵 알겠습니다! 네이밍 리펙터링 하였습니다!

2024-08-31 07:08 UTC, moonwhistle commented on mission-board/src/main/java/com/board/comment/service/ArticleFindByArticleIdService.java
> +        return articleRepository.findById(articleId).orElseThrow(() -> new CustomException(CustomErrorCode.NOT_EXIST_ARTICLE));
1. 아직도 객체지향 생활체조 규칙 오류 범하는게 조금 그렇네요 ㅠㅠㅠ 습관화 하겠습니다!!
2. 이벤트 로직으로 구현하였습니다!

2024-08-31 07:08 UTC, moonwhistle commented on mission-board/src/main/java/com/board/login/resolver/LoginArgumentResolver.java
> +        return sessionLoginService.findMemberBySession(session);
memberId로 받도록 리졸버 구현하였고 이에 따라서 memberService에서 이벤트 발생시켜서 멤버 찾아오는 이벤트 구현하였습니다!

2024-08-31 07:09 UTC, moonwhistle commented on mission-board/src/main/java/com/board/login/service/CookieLoginService.java
> +        member.checkPassword(loginRequest.memberPassword());
넵 알겠습니다!!

2024-08-31 07:45 UTC, moonwhistle commented on mission-board/src/main/java/com/board/login/domain/CookieStorage.java
> +    private final static Map<Long, Cookie> cookies = new HashMap<>();
## Map 자료 구조의 동시성 문제 

### 문제점
~~~
public class CookieStorage {

    private final static Map<Long, Cookie> cookies = new HashMap<>();
}
~~~
* HashMap은 스레드에 안전하지 않은 자료구조이다.
* 여러 클라이언트 요청이 동시에 CookieStorage 클래스의 cookies 맵에 접근하여 데이터를 읽거나 쓰려고 한다면 동시성 문제가 발생.
    * 두 스레드가 동시에 같은 Map에 값을 삽입하거나 삭제할 때, 한 스레드가 작업을 완료하기 전에 다른 스레드가 같은 자원에 접근하면 데이터가 손상될 수 있음.

### 해결책: Concurrent 자료구조
~~~
public class CookieStorage {

    private final static Map<Long, Cookie> cookies = new ConcurrentHashMap<>();
}
~~~
* ConcurrentHashMap과 같은 스레드에 안전한 자료구조를 사용.