Racing/step2 미션 1차 제출 하겠습니다.
sosow0212/2024-mju-mentoring-spring-2 pull request #3
Opened 2024-07-10 08:59 UTC by SEUNGBOONG

1차적으로 피드백을 받기 위해서 제출하겠습니다!! 
기존 도메인 등을 유지하려고 했습니다. 

질문 !!
1. 콘솔에서도 작동하게 하려면 컨트롤러를 새로운것을 하나. 생성했는데 맞는 방식인지 궁금합니다. 

2. 포스트맨 결과값이  ![Uploading 포스트맨결과.png…]()
이와 같이 나오는데 이것은 빈컨테이너에 다른. 메서드들도 빈컨테이너 등록에 부족함이 있었는지 궁금합니다!

3. 공부를해보니 인스턴스 값이 여러 개 일떄 @RequestBody를 사용하는 것을 보고.  적용을 해봤습니다. 이것역시 클린 코드를 위함일까요? 
그리고 DTO 처럼 작동하는 것 처럼 보여서 DTO 패키지에 넣어뒀는데 맞는 판단일까요? 

4. Cars 만 @Component를 적용했는데 Car에다가 했어야했나 라는 의구심이 들었습니다!

5. 리드미에 제가 설정한 URL 주소로 해놓고 포스트맨을 작동했습니다.  아직 미숙해서 정신이 혼란스럽습니다ㅜ

2024-07-10 13:13 UTC, sosow0212 requested changes
현재 디렉토리 구조가 기존에 미션에 주어진 뼈대가 아닌 새로운 디렉토리에서 진행하기에 여러 오류가 발생하고 있습니다.

이 부분 기존 방식처럼 다시 원상복구 해주시고 리뷰 참고해서 수정해주세요!
가급적 제가 리뷰에 남긴 질문에 대해 코멘트로 어떤 생각을 가지고 진행하셨는지 적어주시면서 맞춰나가보면 좋을 것 같습니다!!

헷갈리는 리뷰가 있다면 바로 연락주세요.
수고하셨습니다 👍

2024-07-10 13:13 UTC, sosow0212 commented on mission-racing/src/racingSpring/src/main/java/com/example/racingspring/controller/RacingController.java
> +package com.example.racingspring.controller;
기존 패키지를 사용하지 않고 바꾼 이유가 있을까요? 기존 패키지에서 공존하도록 만드는게 의도였습니다!
지금은 패키지 때문에 자잘하게 다른 오류들이 생기고 있네요!

기존 패키지로 모든 코드 통으로 옮겨주세요~

2024-07-10 13:13 UTC, sosow0212 commented on mission-racing/src/racingSpring/src/main/java/com/example/racingspring/controller/RacingSpringController.java
> +public class RacingSpringController {
SpringController보다는 WebController 와 같은 이름이 더 명확할 것 같아요~

2024-07-10 13:13 UTC, sosow0212 commented on mission-racing/src/racingSpring/src/main/java/com/example/racingspring/controller/RacingSpringController.java
> +    }
생성자가 하나일 땐 @Autowired는 사용하지 않아도 됩니다
여러 생성자가 있을 때 사용하시면 될 것 같아요

2024-07-10 13:13 UTC, sosow0212 commented on mission-racing/src/racingSpring/src/main/java/com/example/racingspring/controller/RacingSpringController.java
> +    public WinnerResponse startRace(@RequestBody StartRaceRequest request) {
`StartRaceRequest`의 위치가 현재 `domain/dto` 아래에 있습니다.

Request, Response는 레이어드 아키텍처에서 컨트롤러 레이어의 역할이라고 생각해서 해당 패키지에 두는 건 다른 레이어를 침범한다고 생각이 드는데 어떻게 생각하시나요?

2024-07-10 13:13 UTC, sosow0212 commented on mission-racing/src/racingSpring/src/main/java/com/example/racingspring/domain/Cars.java
> +@Component
빈으로 등록한 이유가 있나요?

+ `getCarStates` 메서드의 로직 자체가 뷰를 의존하고 있는데 수정하면서 이 부분도 확인해주세요

2024-07-10 13:13 UTC, sosow0212 commented on mission-racing/src/racingSpring/src/main/java/com/example/racingspring/domain/dto/StartRaceRequest.java
> +public class StartRaceRequest {
자바17을 사용중인데 record 클래스도 한 번 사용해보세요~

2024-07-10 13:13 UTC, sosow0212 commented on mission-racing/src/racingSpring/src/main/java/com/example/racingspring/domain/dto/WinnerResponse.java
> +    @GetMapping("api/cars/result")
여기에 GetMapping이 있는 이유가 있나요? 잘못된 접근인 것 같아요

사용자의 요청을 처리하는 순서는 어떻게 되고, 레이어드 아키텍처를 사용중이라면 각 계층에서 해당되는 역할을 고민해보면 좋을 것 같아요.

2024-07-10 13:13 UTC, sosow0212 commented on mission-racing/src/racingSpring/src/main/java/com/example/racingspring/service/RacingService.java
> +        }
1. 해당 로직은 캡슐화가 안되어 있습니다! 
2. Dto로 변환하는 것은 서비스에서 진행해주는 것이 적절할까요? 아니면 컨트롤러 혹은 dto내부에서 하는 것이 적절할까요? 이것도 계층 구조 생각해서 고민해보면 좋을 것 같습니다

2024-07-11 07:12 UTC, SEUNGBOONG commented on mission-racing/src/racingSpring/src/main/java/com/example/racingspring/controller/RacingController.java
> +package com.example.racingspring.controller;
Spring을 다운받고 스프링 패키지에 옮겨야 할거라고 생각을 했었습니다

2024-07-11 07:15 UTC, SEUNGBOONG commented on mission-racing/src/racingSpring/src/main/java/com/example/racingspring/controller/RacingSpringController.java
> +public class RacingSpringController {
넵 수정하겠습니다

2024-07-11 07:29 UTC, SEUNGBOONG commented on mission-racing/src/racingSpring/src/main/java/com/example/racingspring/controller/RacingSpringController.java
> +public class RacingSpringController {
혹시 제  질문에  메서드들도 빈컨테이너 등록에 부족함이 있었는지 궁금합니다! 이부분이있는데 빈등록을 더 진행해야 출력 값이 
미션 요구사항처럼 적용되는 것일 까요?

2024-07-11 07:30 UTC, SEUNGBOONG commented on mission-racing/src/racingSpring/src/main/java/com/example/racingspring/controller/RacingSpringController.java
> +    }
넵 확인했습ㄴ디ㅏ.!

2024-07-11 07:34 UTC, SEUNGBOONG commented on mission-racing/src/racingSpring/src/main/java/com/example/racingspring/domain/dto/WinnerResponse.java
> +    @GetMapping("api/cars/result")
네

2024-07-11 07:34 UTC, SEUNGBOONG commented on mission-racing/src/racingSpring/src/main/java/com/example/racingspring/domain/Cars.java
> +@Component
혹시     public List<String> getCarStates() {
        return cars.stream()
                .map(car -> car.getName() + ": " + "-".repeat(car.getMoveCount()))
                .collect(Collectors.toList());
    } 
    이메서드 말씀하시는 것 같은데 View를 어디서 의존하는지 찾지를 못하겠습니다 ㅜ

2024-07-11 07:35 UTC, SEUNGBOONG commented on mission-racing/src/racingSpring/src/main/java/com/example/racingspring/domain/dto/StartRaceRequest.java
> +public class StartRaceRequest {
넵 !

2024-07-11 07:40 UTC, SEUNGBOONG commented on mission-racing/src/racingSpring/src/main/java/com/example/racingspring/controller/RacingSpringController.java
> +    public WinnerResponse startRace(@RequestBody StartRaceRequest request) {
아 도메인에서 사용하지않고 Controller에서 사용하니 dto 패키지 자체가 Controller에 있어야할 것 같습니다!

2024-07-13 06:24 UTC, closed without merging