Racing/step2 미션제출하겠습니다!
sosow0212/2024-mju-mentoring-spring-2 pull request #5
Opened 2024-07-13 06:25 UTC by SEUNGBOONG

2024-07-13 06:26 UTC, SEUNGBOONG commented
관계를 고민해본결과

winnerResponse 에서 스프링이던 콘솔이던 작동하게하는 메서드를 구현한 후

Outputview에서도 가져다 쓰고
RacingService에서도 가져다 쓰게끔 리팩토링을 진행했다.
결국 재활용성을 높이려고 했고, 상속의 장점을 살려보려고 했다.



바꾸고 난 후 () -> WinnerResponse에 위치가 애매해졌다..
view에서도 가져다쓰고 RacingService에서도 가져다가 쓰는 경우가 생겨버렸다
이러면 WinnerResponse 패키지 위치가 애매해져버렸다 

406 Not Acceptable 발생 이유를 분석해보자 

하이퍼텍스트 전송 프로토콜(HTTP)의 406 Not Acceptable 클라이언트 에러 응답 코드는 서버가 요청의 주도적인 콘텐츠 협상 헤더에 정의된 허용
가능한 값 목록과 일치하는 응답을 생성할 수 없으며, 서버가 기본 표현을 제공하지 않음을 나타냅니다.
 즉 내가 getter 설정을 잘못한 것 같다..? 라는 느낌이 들었다. 



일단 WinnerResponse 라는 Dto 클래스에서 역할을 두가지 이상 가지고 있기에 분할 했다 컨트롤러에서만 사용하는 Dto 와 view에서 사용하느 dto로 구현
# 레이어드 아키텍처란?

- 스프트웨어 시스템을 여러 계층으로 나누어 각 계층이 특정한 역할을 담당하도록
- 설계하는 아키텍처 패턴이다.
- 코드의 조직과 구조를 명확하게 하여 유지보수와 확장성을 향상시킨다.
- 계층마다 자신의 책임에 집중한다.
- 다른 계층과의 상호작용은 명확하게 정의된 인터페이스를 통해 이루어진다.


계층 구조
1. 프렌제테이션 계층 : 사용자인터페이스와 사용자 경험을 담당하는 계층이다.
    - 웹애플리케이션에서는 JS 등 프런트엔드가 해당

2. 애플리케이션 계층:
    - 주요 비즈니스 로직을 포함하는 계층
    - 사용자의 요청을 받아서 처리하고 DB와 상호작용한다.
    - Spring에서는 Service가 해당

3. 도메인 계층
    - 비즈니스 규칙과 도메인 객체를 포함하는 계층
    - 도메인 모델을 정의하고 비즈니스 로직을 구현
    - Spring Entity클래스 역할

4. 퍼시스턴스 계층
    - DB와 상호작용을 담당하는 계층
    - 데이터를 저장 검색 업데이트 한다.
    - Repository역할

5. 인프라스트럭처 계층
    - 다른 계층에서 사용하는 공통적인 기능과 서비스를 제공
    - 로깅 메시징 이메일전송등 기능
    - 서비스에서 인프라스트럭처를 의존하는 것이 좋은 것만은 아님
    - 그래서 도메인 인터페이스를 넣고 도메인 내부에서는 인터페이스 자체는 나한테있는거고 
    - 외부에서 어떤 것을 넣어주냐 에 따라 서 달라지는것 
    - OCP 솔리드 지키는 것 외부 라이브러리가 들어간 언제든 바뀔수 있는 것들 Bean으로 주입해주는 것 
    - IOC DI랑연관있는것
# Spring annotation 을 공부해보자 ..!

# 핵심 애노테이션

1. @SpringBootApplication
    - Spring boot 애플리케이션의 진입점으로 사용
    - @Configuration, @EnableAutoConfiguration, @ComponentScane을 포함한다

2. @Component:
    - 자동으로 빈으로 등록되도록 지정
    - 주로 서비스나 레포지토리 클래스에 사용된다.
    - Spring 컨테이너가 이 클래스를 빈으로 관리하게 한다.

3. @Service
    - @Component 와 동일 서비스 계층에 사용되는 클래스에 의미를 부여한다.
    - 비즈니스 로직을 처리하는 서비스 계층을 명확히한다.
    - 구분 짓기 위해 사용하는 느낌이다!


4. @Repository
    - @Component와 동일하지만, 데이터 액세스 계층에 사용되는 클래스에 의미를 부여하고
    - 데이터 엑세스 예외로 변환한다.
    - 데이터베이스 예외를 스프링의 데이터 액세스 예외로 변환한다.



5. @Controller
    - MVC에서 컨트롤러 역할을 하는 클래스에 사용한다.
    -  웹 요청을 처리하고 뷰를 반환하는 컨트롤러로 동작하는듯

6. @RestController
    - Controller와 @ResponseBody의 조합으로
    - RESTful 웹 서비스 컨트롤러에 사용된다.
    - JSON/XML 형식의 데이터를 반환하는?

7. @Configuration:
    - 자바 기반 설정 파일을 나타낸다. 빈 정의를 포함할 수있다.

8. @Bean :
    - 메서드 레벨에서 사용되어 반환된 객체를 Spring의 빈으로 등록


# 의존성 주입

1. @Autowired :
    - 의존성 주입을 위한 애노테이션
    - 생성자, 필드, 메서드에 적용

2. @Qualifier:
    - @Autowired와 같이 사용
    - 명시적으로 주입할 때 사용
    - EX) @Qualifier("mySpecificService")
    - 주입할 빈을 이름으로 명시할 수 있음 코드 명확성을 위한 것인가?

3. @inject
    - javax.inject 패키지에서 제공
    - @Autowired 와 비슷

4. @Resource
    - @Autowired 와 비슷함
    - @Resource(name = "myService")
      private MyService myService;
    - 이런식으로 빈의 이름을 사용하여 주입


# Spring MVC 애노테이션 :


1. @RequestMapping
    - URL 요청을 처리할 메서드나 클래스에 매핑한다.
    - 지정된 경로에 대한 요청을 해당 메서드로 매핑

2. @GetMapping @PostMapping @PutMapping, @DeleteMapping, @PatchMapping

    - HTTP 메서드와 URL을 매핑한다.
    - @RequestMapping 의 축약형

3. @PathVariable
    - URL 경로에서 변수를추출하여 메서드 파라미터에 바인딩한다.
    - URL 경로의 변수를 메서드 파라미터로 추출한다.

4. @RequestParam
    - 요청 파라미터를 메서드 파라미터에 바인딩한다.

5. @RequestBody
    - 요청 본문을 메서드 파라미어테 바인딩한다.

6. @ResponseBody
    - 메서드의 반환 값을 HTTP 응답 본문으로 변환합니다.(클라이언트에게)

# Spring Data JPA 애노테이션


1. @Entity
    - JPA 엔티티 클래스를 지정


2. @Table
    - 엔티티와 매핑할 데이터베이스 테이블을 지정한다.



빈으로 관리한다는 것이 무엇일까? 에 대한 공부

1. 객체의 생명 주기를 컨테이너가 관리하고
2. 필요할 때 객체를 주입하거나 사용할 수 있도록 해준다
3. 의존성 주입을 통해 이루어진다.
4. 개발자가 객체의 생성의 관여하지않고 Spring이 해주는 것이다.
5. 빈으로 등록된 객체는 애플리케이션 전역에서 재사용가능 싱글턴 패턴으로 관리

2024-07-16 10:04 UTC, sosow0212 requested changes
과제 하시느라 수고 많으셨습니다. 리뷰 확인하고 수정해주세요!
어려운 부분이 있다면 연락주세요~
아직 내부 동작 원리에 대해서 알지 못해서 Cars를 서비스에 두면 안되는 이유 등등에 대해서 의문이 생길 수 있는데, 스프링 공식문서 혹은 Baeldung 사이트에서 이유를 찾아보면 좋을 것 같습니다.
한 번 공부해두면 나중에도 계속 기반 지식으로 가는 느낌이라 추천드립니다!!

2024-07-16 10:04 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/controller/WebController.java
> +    }
API 반환을 Map자체로 반환하는 건 개인적으로 좋지 않다고 생각합니다. (명세가 바뀐다면? Map의 Key, Value가 어떤 것을 의미하는지 모든 개발자가 파악할 수 있을지? 등등의 이유로)

따라서 해당 반환도 다음부터는 Dto를 통해서 해주면 더 좋을 것 같습니다!

2024-07-16 10:04 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/service/RacingService.java
> +    }
레이어드 아키텍처에서 변환에 책임은 Controller에 있습니다! 책임에 맞게 리팩토링 해주세요

2024-07-16 10:04 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/service/RacingService.java
> +    private Cars cars;
스프링부트에서는 톰캣 기준으로 요청이 들어오면 쓰레드풀에서 요청에 맞게 하나씩 쓰레드를 할당해줍니다.
현재 빈 스코프는 기본값인 Singleton으로 되어 있는데 그렇다면 RacingService(싱글톤 객체) 안에 있는 Cars는 임계영역이 될 것 같아요 즉 임계영역은 여러 곳에서 공통으로 접근할 수 있는 자원을 의미하는데요.

이렇게 필드로 선언을 해준다면 다수의 사용자가 registerCars를 사용한다면 결과값이 요청마다 바뀔 것 같습니다.
상태 저장이 필요하다면 다른 방법을 사용해보는 건 어떨까요?

또한 Cars 객체는 초기화되지 않은 상태라서 서버 실행 후 startRace 메서드부터 실행시킨다면 문제가 생길 것 같습니다

2024-07-16 10:04 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/service/RacingService.java
> +    }
1. static 메서드일 필요가 없어보입니다. 
2. 메서드 네이밍은 동사 + 소문자로 시작해주세요
3. 이것도 마찬가지로 반환의 책임을 컨트롤러에게 위임할 수 있도록 다른 방법을 사용해주세요

2024-07-16 10:04 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/service/RacingService.java
> +    }
1. 해당 로직은 도메인의 역할일 것 같아요!
2. Custom Exception을 사용해서 예외를 만들어주세요

2024-07-16 10:04 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/service/dto/CarResponse.java
> +    private final List<Map<String, Integer>> carStates;
`Map<String,Integer>` 자체를 Dto로 한 번 더 감싸면 위에서 언급한 문제점들이 모두 해결되고 Console에서도 중복 제거가 가능할 것 같습니다

2024-07-16 10:04 UTC, sosow0212 commented on mission-racing/src/test/java/com/racing/common/domain/vo/MoveCountTest.java
> +}
마지막 개행이 아직 자동으로 추가가 안됩니다 인텔리제이 설정 확인해주세요

2024-07-16 10:04 UTC, sosow0212 commented on mission-racing/src/test/java/com/racing/common/domain/vo/NameTest.java
> +
```suggestion
```

2024-07-16 10:04 UTC, sosow0212 commented on mission-racing/src/test/java/com/racing/domain/CarsTest.java
> +
```suggestion
```

2024-07-16 10:04 UTC, sosow0212 commented on study/7월15일공부및명세서.md
> +처음에 계속해서 이름이 출력되지않아서 고민 중에 Map을 사용해서 하라고하신 멘토님 말씀대로
Dto로 Map을 사용하는 것이 아닌 데이터베이스 사용이 아직 어려우면 인메모리 DB용으로 Map을 사용하라고 했습니다 ㅠ.ㅠ

2024-07-16 10:04 UTC, sosow0212 commented on study/h2db.md
> +# H2
👍

2024-07-16 17:20 UTC, SEUNGBOONG commented on mission-racing/src/main/java/com/racing/web/controller/WebController.java
> +    }
넵 다음부터는 DTO를 통해서 진행해보겠습니다!

2024-07-16 17:21 UTC, SEUNGBOONG commented on mission-racing/src/main/java/com/racing/web/service/RacingService.java
> +    }
그렇다면 굳이 메서드를 여기서 구현하지 않고 WebController에서구현하면 되는 부분일까여?

2024-07-16 17:23 UTC, SEUNGBOONG commented on mission-racing/src/main/java/com/racing/web/service/RacingService.java
> +    private Cars cars;
생성자 주입방식에 추가해서  @Autowired 로 주입을 해볼까여?

2024-07-16 17:23 UTC, SEUNGBOONG commented on mission-racing/src/main/java/com/racing/web/service/RacingService.java
> +    }
레이어드 아키텍처의 책임에 대해 한번 더공부하고 적용해보도록 하겠습니다

2024-07-16 17:24 UTC, SEUNGBOONG commented on mission-racing/src/main/java/com/racing/web/service/RacingService.java
> +    }
넵 확인했습니다! 아직 눈에 보이지가 않아서 번뜩 떠오르는 단계는 아닌것 같아 한번 반성하고 넘어가겠습니다

2024-07-16 17:24 UTC, SEUNGBOONG commented on mission-racing/src/test/java/com/racing/common/domain/vo/MoveCountTest.java
> +}
멘토님과 같이수정했던건데 ㅜㅜ아직도 적용이안될까요?

2024-07-17 03:56 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/service/RacingService.java
> +    }
저 메서드가 컨트롤러에서 해주는게 레이어드 아키텍처에서 변환의 책임을 하는 것이라고 생각합니다!
간혹 서비스에서 하는 분들도 있지만 컨트롤러까지 문제가 전파되어서 선호하지 않고 변환 책임을 오히려 컨트롤러에서 해주는게 의존도 줄일 수 있고 더 좋다고 생각합니다!

그리고 컨트롤러에 메서드가 지저분하다면 dto에 변환 로직을 정적팩토리메서드로 `도메인 to Dto 변환`의 책임을 둬도 됩니다!
(Dto에 도메인 의존이 생겨서 이것도 원칙적으로는 좋지 않은 설계이지만, Dto는 변환할 때만 사용을 하기 때문에 의존을 해도 문제가 다른 곳까지 전파되진 않아서 저는 타협해서 사용합니다!)

2024-07-17 03:59 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/service/RacingService.java
> +    private Cars cars;
생성자 주입이나 이런 부분에 대한 문제가 아닙니다!
Cars 객체를 빈으로 등록하라는 뜻이 아니라 구조적으로 현재는 여러 쓰레드가 Cars의 값을 건들 수 있기 때문에 Race condition 문제가 발생할 수 있다고 말씀드린거에요~

Cars를 싱글톤으로 생성된 RacingService에 두기 때문에 이런 일이 발생하는데 이를 어떻게 풀면 좋을지 고민해보세요~
Cars 자체를 필드에 두지 않고 데이터베이스로 해결할 수도 있고 아니면 @Request와 같은 빈 스코프를 설정해줘서 요청마다 새로운 객체를 만들도록 할 수도 있는데 후자의 방법은 굳이 추천하진 않습니다~

2024-07-17 03:59 UTC, sosow0212 commented on mission-racing/src/test/java/com/racing/common/domain/vo/MoveCountTest.java
> +}
왜 안될까요 ㅠ 한 번 더 확인해주세요

2024-07-17 15:07 UTC, sosow0212 requested changes
수고하셨습니다! CustomException이랑 Dto 사용에 대해 몇 가지 리뷰를 남겨봤습니다 리뷰 확인하고 반영해주세요!!

2024-07-17 15:07 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/service/RacingService.java
> +    }
1. 이것도 도메인에서 Dto로 변환에 책임을 Service에서 해주고 있네요!
레이어드 아키텍처에서 변환의 책임을 컨트롤러에서 담당해주는데 컨트롤러에서 Dto로의 변환을 하는 것이 더 좋아보입니다
서비스에서 반환 Dto에 문제가 생긴다면 컨트롤러까지 전파가 될 수 있는데, Service에서는 작업을 완료한 객체 자체를 반환하고 컨트롤러에서 반환해주는 것은 어떨까요?
1-1. 컨트롤러로 Domain 자체를 반환하고 컨트롤러에 domain to dto 변환 메서드를 생성하고 만들기
1-2. 컨트롤러로 Domain 자체를 반환하고 컨트롤러에서 Dto의 정적팩토리 메서드를 통해 도메인을 Dto로 바꾸기 (해당 방식은 Dto가 도메인을 의존해서 좋은 설계는 아니지만 개인적으로 저는 변환로직 정도는 괜찮다고 타협해서 사용하고는 있습니다.)
여기서 선택해서 바꿔보면 좋을 것 같습니다

2024-07-17 15:07 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/service/dto/CarResponse.java
> +public record CarResponse(List<Map<String, Integer>> carStates, List<String> winners) {
Map<String, Integer> 자체가 개발자들이 키 밸류가 각각 무엇인지 한 눈에 파악하기 힘들 것 같습니다.
따라서 Map<String, Integer> 자체로 Dto로 만들어서 사용하는 것이 좋을 것 같습니다

2024-07-17 15:07 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/service/dto/CarState.java
> +public record CarState(String name, int moveCount) {
Request인이 Response인지 명확하게 네이밍 변경이 필요할 것 같습니다!

2024-07-17 15:07 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/service/exception/CarNullException.java
> +public class CarNullException extends IllegalStateException{
IllegalStateException을 상속하신 이유가 무엇인가요?

2024-07-17 15:07 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/controller/WebController.java
> +
```suggestion
```

2024-07-17 15:07 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/service/RacingService.java
> +                .orElseThrow(NotFoundCar::new);
캡슐화 할 수 있을 것 같습니다!

2024-07-17 15:07 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/service/RacingService.java
> +        return new CarState(car.getName(), car.getMoveCount());
이것도 반환은 컨트롤러에서 해주는 것이 좋을 것 같습니다

2024-07-17 15:07 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/controller/WebController.java
> +        return racingService.getRaceResultByName(name);
`getRaceResultByName()`이라는 네이밍에서 엄청 중요하진 않지만, find와 get을 붙이는 것에 차이에 대해서 간단히 말씀 드리면

find : 무엇인가를 찾는다 (데이터가 없을 수도 있음 -> 예외 or etc...)
get : 무조건 무엇인가 있고 바로 가져온다 (데이터가 있어야함)

이런 차이가 있습니다! 지금은 find가 더 적절해보입니다~
[참고링크](https://softwareengineering.stackexchange.com/questions/182113/how-and-why-to-decide-between-naming-methods-with-get-and-find-prefixes)

2024-07-18 07:10 UTC, SEUNGBOONG commented on mission-racing/src/main/java/com/racing/web/service/RacingService.java
> +        return new CarState(car.getName(), car.getMoveCount());
넵

2024-07-18 07:11 UTC, SEUNGBOONG commented on mission-racing/src/main/java/com/racing/web/controller/WebController.java
> +        return racingService.getRaceResultByName(name);
넵 한번 읽고 수정진행했습니다!

2024-07-18 07:11 UTC, SEUNGBOONG commented on mission-racing/src/main/java/com/racing/web/service/RacingService.java
> +                .orElseThrow(NotFoundCar::new);
넵!

2024-07-18 07:12 UTC, SEUNGBOONG commented on mission-racing/src/main/java/com/racing/web/service/RacingService.java
> +    }
2번으로 진행했습니다!! 
DTO 자체가 변환 값만 주고 받을 수 있어야 한다 라고 국한되어있었습니다!
생가개보니 정팩메를 적용을 해도 된다고 까지 생각에 접근을 하지못했습니다!

2024-07-19 03:17 UTC, sosow0212 approved these changes
아직 아쉬운 부분이 조금 남아있지만 이런 것들은 다음 미션 때 해결해주세요!
공부한 내용에 여러가지 코멘트를 남겼는데 읽어보시고 따로 공부해보시면 스프링 동작원리나 어떻게 요청이 처리되는지 이해하는데 도움이 될 것 같습니다!
다음 단계부터는 CustomException이 발생하면 클라이언트 측으로 예외 메시지를 따로 보내줄 수 있도록 설정해보시면 좋을 것 같아요. (키워드 : RestControllerAdvice)
수고하셨습니다~

2024-07-19 03:17 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/service/RacingService.java
> +    private Cars cars;
이 부분 아직 수정이 안 되었는데 지금처럼 Cars 객체를 필드로 두게 된다면 Service가 싱글톤으로 생성되어 있어서 여러 쓰레드에서 Service의 필드인 Cars에 접근할 수 있습니다.

즉 여러 쓰레드가 Cars를 무분별하게 수정할 수 있다는 말인데 (임계영역) 이러면 동시성 문제가 발생할 수도 있고 데이터 정합성이 지켜지지 않을 수도 있습니다.

이는 나중에 데이터베이스가 들어오고 트랜잭션까지 추가된다면 더 큰 문제가 될 수 있음을 내포합니다. (만약 계좌 잔고같은 것이라면?)
다음 때부터는 메서드 내에서 객체를 생성하거나 상태 관리가 필요하다면 DB를 활용해보면 좋을 것 같습니다!

2024-07-19 03:17 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/controller/WebController.java
> +import org.springframework.web.bind.annotation.*;
와일드카드가 있네요!

2024-07-19 03:17 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/service/RacingService.java
> +import com.racing.web.controller.dto.StartRaceRequest;
Service에서 Controller가 역참조하고 있네요!
RequestDto가 Service.dto로 가면 해결될 것 같습니다

2024-07-19 03:17 UTC, sosow0212 commented on study/7월16일리팩토링 공부.md
> +코딩해보면 와닿을 것 같습니다!!
레이어드 아키텍처가 왜 등장했고 왜 사용하는지에 대해서 공부해보면 도움이 될 것 같습니다~

2024-07-19 03:17 UTC, sosow0212 commented on study/레이어드아키텍처.md
> +    - Spring Entity클래스 역할
Entity와 Domain의 차이도 알아보면 좋을 것 같습니다

2024-07-19 03:17 UTC, sosow0212 commented on study/레이어드아키텍처.md
> +    - IOC DI랑연관있는것
도메인 서비스에 구현체를 넣어주는 건 도메인에 infrastructure를 의존하지 않게 하기 위해서 도메인에 인터페이스로 두고, 외부에서 구현체를 DI로 주입해주는 것은 DIP 의존역전원칙이 잘 지켜지는 것입니다! 👍

2024-07-19 03:17 UTC, sosow0212 commented on study/스프링동작원리 및 멀티 쓰레드 방식의 장단점.md
> +    - 스레드 풀에서 스레드를 가져와 작업을 수행하고 작업이 완료되면 스레드를 반환
그렇다면 쓰레드풀은 무엇이고, 기본 쓰레드의 수는 몇 개이고, 쓰레드풀 설정은 언제해줘야하는지, 쓰레드가 너무 많아지면 어떤 일이 일어나는지도 공부해보면 좋을 것 같습니다!

2024-07-19 03:17 UTC, sosow0212 commented on study/스프링동작원리 및 멀티 쓰레드 방식의 장단점.md
> +2. 자원 공유 : 스레드간 자원공유가 가능하다?  - > 메모리 사용 최적화
이건 스프링에서 기본 빈 스코프가 싱글톤인 것과 관련있습니다.

빈 스코프란? : 빈의 생성, 생존 전략 정도라고 이해하면 좋을 것 같습니다.

즉 스프링에서는 빈의 스코프를 싱글톤을 기본 전략으로 택하는데요.

싱글톤의 특징은 하나의 객체만 생성하고 돌려쓰니 메모리를 적게 쓰니 이에 대한 장점이 있다는 것이고, 반대로 싱글톤이라서 싱글톤 내부에 필드가 있다면 여러 쓰레드가 접근하여 값을 바꿔 정합성이 떨어질 수 있다는 문제가 있습니다.

그렇다면 이럴 땐 어떻게 해야할까요? 여러 방법이 있을 것 같습니다.
1. 빈스코프를 Prototype, Request 등등으로 바꾼다. (이건 크게 추천하지 않습니다.)
2. 락을 걸거나 다른 방식을 통해 동시성을 보장해준다.
3. 임계영역이 될만한 자원을 두지 않는다. (여기선 Cars가 서비스의 필드로 선언 되었으므로 싱글톤 객체의 변수가 됨 --> 임계영역)

2024-07-19 03:17 UTC, sosow0212 commented on study/스프링동작원리 및 멀티 쓰레드 방식의 장단점.md
> +1. 비동기처리: @Async 와 같은 기능을 제공하여 메서드를 비동기적으로 실행할 수있어 병럴 처리 가능
비동기는 언제 사용하면 좋을까요?

2024-07-19 03:30 UTC, merged

2024-07-19 06:26 UTC, SEUNGBOONG commented on mission-racing/src/main/java/com/racing/web/controller/WebController.java
> +import org.springframework.web.bind.annotation.*;
수정완료했습니다!

2024-07-19 06:27 UTC, SEUNGBOONG commented on mission-racing/src/main/java/com/racing/web/service/RacingService.java
> +import com.racing.web.controller.dto.StartRaceRequest;
넵 수정완료했씁니다!

2024-07-19 06:27 UTC, SEUNGBOONG commented on study/7월16일리팩토링 공부.md
> +코딩해보면 와닿을 것 같습니다!!
넵 다음미션때 공부한내용정리해서 같이 PR하겠씁니다

2024-07-19 06:28 UTC, SEUNGBOONG commented on study/레이어드아키텍처.md
> +    - Spring Entity클래스 역할
넵 다음미션때 공부한내용정리해서 같이 PR하겠씁니다

2024-07-19 06:28 UTC, SEUNGBOONG commented on study/레이어드아키텍처.md
> +    - IOC DI랑연관있는것
넵!!

2024-07-19 06:28 UTC, SEUNGBOONG commented on study/스프링동작원리 및 멀티 쓰레드 방식의 장단점.md
> +    - 스레드 풀에서 스레드를 가져와 작업을 수행하고 작업이 완료되면 스레드를 반환
이것 역시공 부한내용정리해서 같이 PR하겠씁니다

2024-07-19 06:29 UTC, SEUNGBOONG commented on study/스프링동작원리 및 멀티 쓰레드 방식의 장단점.md
> +2. 자원 공유 : 스레드간 자원공유가 가능하다?  - > 메모리 사용 최적화
2번이 가장 많이 쓰는것같습니다 ! 공부 중에 락을 거는 방식이 가장 많이 쓰이는 것 처럼 느껴졌습니다!

2024-07-19 06:30 UTC, SEUNGBOONG commented on study/스프링동작원리 및 멀티 쓰레드 방식의 장단점.md
> +1. 비동기처리: @Async 와 같은 기능을 제공하여 메서드를 비동기적으로 실행할 수있어 병럴 처리 가능
비동기처리를 하는 이유는 클라이언트가 서버에게 데이터를 요청했을 때 서버가 응답을 언제줄지 확답이 없고 
지연이 될수도 있기때문에 사용합니다!