Racing car/step2 제출합니다!
sosow0212/2024-mju-mentoring-spring-2 pull request #6
Opened 2024-07-16 18:20 UTC by Hheojiwon

2단계 제출하겠습니다!
custom exception 사용하였고, 랜덤 숫자 생성의 책임을 Car이 가지지 않도록 인터페이스 활용해서 콘솔 코드 수정했습니다. 그 외 코드 정렬 및 말씀해 주신 부분 수정하였습니다.
2단계 진행하면서 racingService 생성하였고, 웹 컨트롤러 작성하였습니다. 
이름으로 car 랭킹을 조회하기 위한 메서드 추가하였습니다.
2단계 진행하면서 기본 어노테이션이나 어떤것을 빈으로 등록해야 하는지.. 등등 거의 처음이라 많이 찾아보면서 공부했는데 코드 작성 하면서 어려웠던 것 같습니다. 피드백 주시면 수정하겠습니다 ..!!

2024-07-17 03:38 UTC, sosow0212 requested changes
미션하시느라 수고 많으셨습니다!

가급적이면 Controller에서 데이터를 주고 받을 때 Dto를 사용해보시면 좋을 것 같고, 응답을 줄 때 ResponseEntity를 많이 사용하는데 왜 사용하는지, 다른 걸 사용할 순 없는지? 다른 걸 사용하면 응답코드는 어떻게 해줄지 등등에 대해 학습해보면 좋을 것 같아요

그리고 아직은 스프링 내부 동작원리에 대해서 파악하기 힘들 순 있지만 리뷰 남긴대로 서비스에 필드가 있으면 왜 안되는지에 대해서 운영체제 내용과 스프링 동작 원리와 함께 학습해보시면 좋을 것 같아요

CustomException을 사용했다면, 예외가 발생하면 사용자에게 응답이 어떻게 가고 그걸 또 원하는대로 변경해서 전달해줄 수 없는지도 고민해보세요!

Baeldung, 스프링 공식 문서 보시면서 학습하시는 거 추천드립니다!

2024-07-17 03:38 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/Exception/NameLengthException.java
> +package com.racing.Exception;
패키지 이름이 대문자로 되어있네요!

2024-07-17 03:38 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/controller/CarController.java
>          cars.generateCarList(inputNames);
`cars.generate~` 이 코드가 꼭 필요할까 싶어요 네이밍을 보거나 행위를 봐도 생성의 역할일텐데 생성자의 역할로 가도 되지 않을까요?
빈 List<Car>를 Cars에 넣어주고 생성하기보다는 Cars에 inputNames를 생성자 매개변수로 넣으면 생성되도록 하는 것이 더 명확할 것 같습니다

2024-07-17 03:38 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/controller/RacingController.java
> +    public void registerCars(@RequestBody Map<String, Object> request) {
가급적이면 RequestBody로 데이터를 받거나 혹은 데이터를 컨트롤러에서 반환할 때에는 Dto를 사용하는 것이 좋다고 생각합니다!

현재 구조에서는 request의 key value가 각각 어떤 것을 의미하는지 파악하기도 힘들 것 같고 Map에 key가 여러 개 들어온 상태로 서버로 올 수도 있습니다!

Dto를 통해 적용해보시고 하는 김에 record 클래스도 같이 공부해보면 좋을 것 같습니다!

2024-07-17 03:38 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/controller/RacingController.java
> +    }
이 부분도 반환되는 형식이 요구사항과 맞지 않네요!
그리고 다른 부분도 마찬가지지만 반환할 때 ResponseEntity를 사용해보면 어떨까요? 해당 클래스는 어떤 역할을 하는지 공부하고 적용해보시면 도움 많이 되실 것 같습니다

2024-07-17 03:38 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/controller/RacingController.java
> +}
마지막 개행 추가해주세요!

2024-07-17 03:38 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/model/Car.java
>      }
이 부분도 외부에서 randomNumber를 받는데 Car 클래스 안에 메서드로 RandomNumber를 생성해주는 메서드가 있네요!

그러면 외부에서 `var number = car.getRandomNumber();`를 사용한 후 `car.carMovePosition(number);`와 같이 사용할텐데 이게 좀 어색한 거 같아요

외부에서 수를 뽑아서 움직이는 메서드에 넣거나 혹은 carMovePosition() 메서드 매개변수로 인터페이스를 넣고(도메인 서비스) 내부에서 생성하고 움직이는게 구조적으로도 테스트적으로도 더 좋을 것 같습니다
(+ carMovePosition이라는 네이밍보단 메서드는 동사로 시작해야합니다!)

2024-07-17 03:38 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/model/Cars.java
> +    private List<Car> cars;
```suggestion
    private static final int NAME_MAX_LENGTH = 5;
    
    private List<Car> cars;
```

2024-07-17 03:38 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/model/Cars.java
> +    public List<String> carRank() {
이것도 메서드명은 동사로 시작해주세요

2024-07-17 03:38 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/model/Cars.java
> +    public Car getCarByName(String name) {
이건 사소한건데 get이라는 네이밍은 있다고 가정하고 꺼내는 것이고(예외가 없는 경우) find는 없을 수도 있다라고 가정하고(예외가 있을 수 있음) 찾을 때 보통 사용합니다!

[참고 링크](https://softwareengineering.stackexchange.com/questions/182113/how-and-why-to-decide-between-naming-methods-with-get-and-find-prefixes)

2024-07-17 03:38 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/service/RacingService.java
> +    private int tryCount;
`@Service` 어노테이션이 붙으면 기본적으로 싱글톤으로 객체가 생성됩니다.
현재는 톰캣이 사용자인 HttpServletRequest가 들어오면 쓰레드풀에서 쓰레드를 하나 꺼내서 할당해주는 식으로 작동이 됩니다.

만약에 10명에 사용자가 동시에 요청을 보낸다면 (서비스 필드 값의 상태를 바꿀 수 있다고 전제) 싱글톤으로 생성된 RacingService 내부에 필드값은 `임계영역`이 되어서 `RaceCondition`이 발생할 것 같습니다.

값에 대한 상태관리가 필요하다면 데이터베이스 혹은 현재 미션에선 간단하게 Map을 이용한 인메모리 데이터베이스를 직접 만들어 보는 것은 어떨까요?

계정 정보는 없다라고 전제하고(서비스를 사용하는 사용자는 한 명) 만드셔도 좋을 것 같습니다!

2024-07-17 03:38 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/service/RacingService.java
> +        return raceResults;
이 부분도 변환의 책임을 현재 서비스레이어에서 하고 있네요

레이어드 아키텍처를 학습해보시면 사용자 응답에 대한 변환은 컨트롤러에서 담당하는 것이 더 적합해보입니다.
도메인 자체를 컨트롤러로 넘기고 변환을 컨트롤러단에서 도메인의 getter를 이용하여 사용자 뷰로 변환해보는 것은 어떨까요?

현재 Service에서 getCars도 필요없어보입니다

2024-07-17 03:38 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/model/Cars.java
> +                .orElse(null);
여기서 orElseThrow로 CustomException을 발생시킨다면 서비스에서 찾지 못하는 경우도 예외처리가 될 것 같아요

2024-07-17 03:38 UTC, sosow0212 commented on mission-racing/src/test/java/com/racing/RacingServiceTest.java
> +@SpringBootTest
통합테스트 👍

`테스트 격리`가 무엇이고 SpringBootTest에서 `RANDOM_PORT` 와 같은 속성들은 각각 무엇이고 왜 사용하는지 학습해보면 좋을 것 같습니다.

프레임워크 작동원리 파악하기에도 좋다고 생각하고 언젠가 상위 레이어도 테스트를 할텐데 지금 학습하기 좋아보입니다!

2024-07-20 19:20 UTC, Hheojiwon commented on mission-racing/src/main/java/com/racing/Exception/NameLengthException.java
> +package com.racing.Exception;
수정했습니다!

2024-07-21 04:56 UTC, sosow0212 requested changes
기본을 잡고 가는게 굉장히 중요하다고 생각해서 리뷰에 질문식으로 남겨봤습니다.
꼭 공부하고 코멘트로 답변 남겨주시고, 모르는 것이 있다면 바로바로 질문해주세요! 스프링이 프레임워크라서 아무래도 처음에 동작원리와 빈 이런 것들이 생소하시겠지만, 스프링으로 서버 개발을 하고 활용하려면 결국에는 어떻게 돌아가고 왜 이 기술을 사용하는지는 꼭 알아야합니다!

예를 들면 dto로 반환하면 어떻게 클라이언트가 자바 객체를 Json 형태로 받는지 이런 부분에 대해서 기본적인 이유를 파악하면 나중에 RestTemplate이나 캐시에 객체를 관리할 때에도 같은 기술을 사용한다는 것을 금방 알 수 있고, 또한 리플렉션이라는 것이 무엇인지도 알게 되면서 jpa가 어떻게 동작되는지도 혹은 스프링에서 빈을 어떻게 스캔하는지 등등에 대해서도 쉽게 이해할 수 있게 됩니다.

꼭 어노테이션이나 사소한 방법에 대해서 그냥 넘어가시지 말고 지금 초기 단계에 학습하시면서 진행하면 나중에 정말 많이 도움 되실 거에요!

수고하셨습니다!!

2024-07-21 04:56 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/controller/CarController.java
> +        Cars cars = new Cars(inputNames);
메서드로 필드 관리 좋습니다👍
기존에 전역으로 관리했을 때와 다른 점도 생각해보시면 좋을 것 같아요

추가적으로 Cars의 필드인 List<Car> 자체를 생성자로 받는 것이 아닌 inputNames(String)을 생성자로 받고 있는데요.
기본 생성자는 List<Car>로 유지하고, 정적팩토리메서드로 Cars.from(inputNames) 와 같이 위에 방식을 구현하시면 생성 전략이 많아져도 기본 생성자는 퓨어하게 유지된 상태로 여러 생성 전략을 만들기 수월합니다!

2024-07-21 04:56 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/controller/RacingController.java
> +    public void registerCars(@RequestBody CarRegister register) {
1. 현재 CarRegister 라는 네이밍은 Request인지 생성된 후 반환되는 Response인지 명확하게 구분되지는 않습니다. Dto의 네이밍 방법은 여러가지가 있는데 예를 들어 CarRegisterRequestDto 라는 네이밍이 될 수도 있고 저는 Dto라는 네이밍이 Request에 포함되었다고 생각하기에 보통 CarRegisterRequest, CarRegisterResponse 와 같은 네이밍을 사용합니다. 이건 사람마다 조금씩 다르니 네이밍에 본인만의 기준을 가져도 좋을 것 같습니다.

2. void를 반환하더라도 ResponseEntity<Void>를 통해 반환하는 것은 어떨까요? void 반환과 ResponseEntity로 감싸준 것의 차이가 있는데, 그렇다면 왜 ResponseEntity를 사용하는지 학습해보면 좋을 것 같습니다

2024-07-21 04:56 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/controller/RacingController.java
> +    }
void여도 응답코드를 반환해주는 습관을 들이면 좋습니다!
기본 성공시 200 응답코드를 주지만 나중에는 클라이언트 기능처리의 요구사항으로 201 혹은 204와 같은 응답코드도 줄 수 있기 때문에 ResponseEntity를 사용해주세요!

2024-07-21 04:56 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/controller/RacingController.java
> +        return ResponseEntity.ok(resultResponse);
service에서 resultResponse를 반환하고 있네요!
레이어드 아키텍처에서 클라이언트에게 데이터를 변환하여 바꿔주는 책임은 컨트롤러에 있습니다.
서비스에서는 도메인을 반환받고, 컨트롤러에서는 받아온 도메인을 Dto로 변환할 수 있도록 해보는 건 어떨까요?

(이때 RaceResult의 패키지 위치는 어디에 있으면 좋을지 레이어드 아키텍처의 참조와 관련해서 고민해봐도 좋을 것 같습니다! -> {역참조})

2024-07-21 04:56 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/controller/RacingController.java
> +    public ResponseEntity<CarStatus> getCarStatus(@RequestParam("name") String name) {
1. @GetMapping에서 params를 사용하면서 매개변수에 @RequestParam을 사용하는 것과 하나씩 사용하는 것은 각각 무엇이 다를까요?
2. 이것들의 작동원리가 무엇일까요?

2024-07-21 04:56 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/exception/CarNotFoundException.java
> +public class CarNotFoundException extends RuntimeException{
CustomException 좋습니다!
정말 중요한 개념을 잡고 갔으면 좋겠어서 몇 가지 질문 남겨봅니다!

1. `Checked Exception과 Unchecked Exception의 차이는 무엇일까요?`
2. 해당 CustomException에서 `RuntimeException`을 상속받은 이유는 무엇인가요?
3. `CarNotFoundException`예외가 비즈니스 로직에서 발생하였을 때 클라이언트 측에게 응답은 어떻게 갈까요? 이 응답을 404 NOT_FOUND 로 주고 싶다면 어떻게 해야할까요?

```suggestion
public class CarNotFoundException extends RuntimeException {
```

2024-07-21 04:56 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/model/Cars.java
>  import java.util.*;
import에 와일드카드는 지양해주세요!

2024-07-21 04:56 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/model/Cars.java
> +    private List<Car> cars = new ArrayList<>();
```suggestion
    private static final int NAME_MAX_LENGTH = 5;
    
    private List<Car> cars = new ArrayList<>();
```

cars를 작성하신 코드처럼 바로 초기화해주는 것과 생성자를 통해 초기화해주는 것의 차이가 무엇이고, 어떤 장단점이 있을까요

2024-07-21 04:56 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/model/Cars.java
> +            throw new NameLengthException();
👍

2024-07-21 04:56 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/model/Cars.java
>          }
1. for문의 요소를 탐색할 때마다 RandomNumber라는 객체를 생성해준다면, 메모리 관리 차원에서 GC가 계속 돌아가서 성능적으로 문제는 없을까요?

2. 인터페이스인 RandomNumber를 바로 CarRandomNumber 구현체로 넣어주고 있는데 그렇다면 인터페이스 사용에 대한 장점을 못 누릴 것 같은데 어떻게 생각하시나요?
외부에서 구현체를 넣어준다면 도메인 내부에선 어떤 구현체인지 몰라도 외부 전략에 따라 수행할 수 있지 않을까요?
위에 방식대로 리팩토링 한다면 스프링에서도 빈으로 등록된 인터페이스의 구현체를 찾아서 DI로 해줄텐데 이렇게 한다면 스프링의 장점을 누릴 수 있을 것 같습니다!

2024-07-21 04:56 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/model/Cars.java
> +    public List<String> rankCars() {
메서드 명은 동사로 시작해주세요

2024-07-21 04:56 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/model/Cars.java
> +                .filter(car -> car.getName().equals(name))
`car.getName().equals(name)` 이 부분을 car의 메서드로 캡슐화 시켜주세요!

2024-07-21 04:56 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/service/RacingService.java
> +    private int tryCount;
Service에 필드로 도메인과 변수를 관리하고 있는데요.
@Service 어노테이션은 기본 빈 생성 전략이 `* 싱글톤` 이기 때문에 무수히 많은 유저가 요청을 보내도 딱 하나의 객체만 생성되어 계속 재활용하게 됩니다.
> 싱글톤이란? : 디자인패턴 중 생성 패턴 중 하나로, 딱 하나의 객체 인스턴스만 생성되어 재활용 할 수 있다. -> 메모리 관리 차원에서 효율적이지만, 자원에 대해 동시 접근 또한 가능하다. (이해가 안 간다면 A,B,C 사용자가 똑같은 객체의 이름만 A,B,C로 달아 자기 것을 쓰면 다른 사람들이 자신의 자원을 건들 일이 없지만 A,B,C 사용자가 싱글톤 객체 T 하나만 이용한다면 T의 필드는 이곳저곳에서 건들여 정합성 보장이 되지 않는다) --> 그렇다면 스프링에서 왜 기본 빈 스코프를 싱글톤으로 했는지도 유추해보면 좋을 것 같습니다.

이렇게 되면 아래 시나리오대로 문제가 생깁니다.

1. 사용자의 요청시 톰캣에서 요청마다 쓰레드를 할당해주고 쓰레드가 요청을 처리한다.
2. 이때 @Service 즉 싱글톤 스코프로 선언된 RacingService는 딱 하나의 인스턴스만 메모리에 올라가있고 여러 쓰레드는 하나의 객체의 자원을 동시에 접근하여 건들 수 있다.
3. 자원의 정합성이 맞지 않을 수 있다.
4. 추가적으로 현재는 registerCars에서 전역변수인 cars를 초기화해주고 나머지 메서드에서는 초기화하지 않는다. 즉 registerCars 메서드를 실행시키지 않고 다른 메서드를 먼저 실행시키면 예외(NPE)가 발생한다.

아직 위에 내용들이 이해가 가지 않는다면 일단은 Cars, tryCount를 메서드 내부에서만 작동할 수 있도록 관리한 후 공식문서로 계속 학습하시면서 이해하셔도 될 것 같습니다. 다만 왜 메서드 내부에서 객체와 필드를 관리하는지는 꼭 이해하셔야합니다!



++ 일부로 미션을 생각한 범위 내에서 자율적으로 할 수 있도록 딱 정해놓지를 않았는데요. 
아마도 멘티님은 registerCars로 차량을 등록한 후(아마 최초 한 번만 등록할 수 있도록 설정한 것 같아요) 레이싱을 하고 결과를 볼 수 있도록 하신 것 같습니다.

위에 경우가 맞다면 
1. registerCars에서 자동차를 등록할 때마다 기존의 자동차 내역들은 삭제가 되어야하고
2. race() 메서드를 실행할 때 자동차 내역이 없다면 예외를 발생해야하고
3. getCarStatus() 메서드를 실행할 때 name에 해당하는 자동차가 없을 때 예외를 발생해야합니다.

이렇게 진행하려면 registerCars에서 차량을 등록할 때 어딘가에 데이터를 저장하고 관리해야할텐데 그렇다면 h2, mysql과 같은 데이터베이스를 사용할 수도 있지만, 다음 미션에서 진행할 것이니 일단은 repository단 구현을 자바의 자료구조인 Map으로 인메모리 데이터베이스처럼 활용해볼 수도 있을 것 같습니다. (상휘 미션 참고)

한 번 내용 정리해보신 후 학습하시고 적용해보시면 좋을 것 같습니다!

2024-07-21 04:56 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/service/RacingService.java
> +        }
1. 차량이 없다면 null을 반환하는데 자바에서는 null을 제어하기 힘들어서 예상치 못한 문제로 번질 수 있습니다. Optional 키워드를 학습하고 적용해주세요!

2024-07-21 04:56 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/service/dto/RaceResult.java
> +        List<Map<String, Integer>> status,
1. Map<String, Integer>의 키 밸류가 무엇을 의미하는지 알기 힘들 것 같은데 List<...Response> 이런 형식으로 Dto로 한 번 더 묶어주세요

2. 레코드 방식은 자바 17에 생겼는데요. 만약에 자바 11로 개발을 한다면 어떻게 Dto를 만들어야할까요? 역직렬화와 직렬화가 각각 무엇이고 사용하려면 어떤 조건이 있어야할까요? (ex. 생성자)

2024-07-28 09:55 UTC, Hheojiwon commented on mission-racing/src/main/java/com/racing/controller/RacingController.java
> +    public void registerCars(@RequestBody CarRegister register) {
1. request, response를 구분할 수 있도록 네임 수정하였습니다!
2.  @ResponseEntity<T>
- HTTP 상태코드와 함께 객체에 해당하는 데이터가 같이 넘어간다.
- 응답으로 변환될 정보를 모두 담은 요소들을 객체로 만들어서 반환해줌.
ResponseEntity<Void> 를 통해 반환하도록 수정하였습니다.

2024-07-28 09:56 UTC, Hheojiwon commented on mission-racing/src/main/java/com/racing/controller/RacingController.java
> +    }
ResponseEntity 사용하여 반환하도록 수정했습니다

2024-07-28 10:10 UTC, Hheojiwon commented on mission-racing/src/main/java/com/racing/controller/RacingController.java
> +        return ResponseEntity.ok(resultResponse);
service에서 특정 dto에 의존하게 되면 코드 재사용성이 떨어지고, 역할이 복잡해질 수 있다는 것을 알게 되었습니다. 서비스에서는 도메인을 반환하고, 컨트롤러에서 DTO로 변환하여 반환하도록 수정하였습니다!

2024-07-28 10:39 UTC, Hheojiwon commented on mission-racing/src/main/java/com/racing/exception/CarNotFoundException.java
> +public class CarNotFoundException extends RuntimeException{
### Custom Exception

1. checked Exception
- 컴파일 시점에 컴파일러에서 확인하는 예외
- 예외 처리를 반드시 해줘야 한다

2. unchecked Exception
- 런타임에 발생한다.
- 프로그램 논리 내부에 오류가 있을때 발생

비즈니스 로직에서 발생하는 예외는 예외 처리를 강제할 필요가 없기 때문에 unchecked Exception으로 처리한다.

3. @ExceptionHandler를 사용하여 예외 응답을 따로 설정하여 전달할 수 있을 것 같습니다.!

2024-07-28 10:40 UTC, Hheojiwon commented on mission-racing/src/main/java/com/racing/model/Cars.java
>  import java.util.*;
넵 수정했습니다!

2024-07-28 10:57 UTC, Hheojiwon commented on mission-racing/src/main/java/com/racing/model/Cars.java
>          }
1. 반복문을 통해 RandomNumber 객체를 계속 생성하는 방식은 메모리 관리 차원에서 좋지 않은 것 같아 수정하였습니다. 
2. 이전처럼 인터페이스가 아닌  특정 구현체를 바로 넣어주는 방식을 사용하면,  코드의 유연성을 높여주는 인터페이스의 장점을 살리지 못하게 된다는 것을 느끼게 되었습니다.  수정하였습니다.

2024-07-28 10:57 UTC, Hheojiwon commented on mission-racing/src/main/java/com/racing/model/Cars.java
> +    public List<String> rankCars() {
넵 수정했습니다!

2024-07-28 10:58 UTC, Hheojiwon commented on mission-racing/src/main/java/com/racing/model/Cars.java
> +                .filter(car -> car.getName().equals(name))
넵 메서드를 이용해 캡슐화 하였습니다!

2024-07-28 11:21 UTC, Hheojiwon commented on mission-racing/src/main/java/com/racing/service/RacingService.java
> +    private int tryCount;
### 싱글톤 패턴
- 특정 클래스가 단 하나만의 인스턴스를 생성하여 사용하기 위한 패턴
- 생성자를 여러 번 호출하더라도 인스턴스가 하나만 존재하도록 보장하여 애플리케이션에서 동일한 객체 인스턴스에 접근할 수 있도록 함

스프링에서는 빈을 싱글톤으로 관리하여 메모리 효율성을 높이고, 빈의 생성과 소멸을 일관되게 관리하도록 한다는 것이 중요한 것 같습니다. 
기존 방식은 하나의 객체에 여러 쓰레드가 접근했을 때 예기치 않은 예외가 발생할 수 있고, 또 차를 등록하기 전 다른 메서드가 호출되면 초기화되지 않은 객체에 접근하게 되는 문제가 발생하게 된다는 점을 깨닫게 되었습니다. 학습하면서, 동시성과 상태를 관리하는 문제를 해결하기 위해서 상태 없는 빈을 사용해야 한다는 것을 알게 되었습니다. 
가르쳐 주신 대로 인메모리 데이터 베이스 역할을 하는 repository 를 구현하여 사용하는 방식으로 리팩토링 하였습니다!

2024-07-28 11:31 UTC, Hheojiwon commented on mission-racing/src/main/java/com/racing/service/RacingService.java
> +        }
NPE 방지를 위해 Optional로 null을 감싸서 반환하는 것이 더 안전하다는 것을 알게 되었습니다
Optional 사용해서 수정 하였습니다!

2024-07-28 12:01 UTC, Hheojiwon commented on mission-racing/src/main/java/com/racing/service/dto/RaceResult.java
> +        List<Map<String, Integer>> status,
1. 수정했습니다!

2.  
### Record class
불변 객체를 생성할 때 사용한다.
데이터를 전달하기 위한 클래스이다.
- 모든 필드에 final 선언 생략
- 필드 값을 모두 포함한 생성자 자동 생성
- 접근자 메서드(getter), hashCode(), toString() 메서드를 자동으로 생성한다.


모든 필드를 선언한 후 초기화할 수 있도록 생성자를 따로 작성하고, 각 필드에 대한 getter와 setter 메서드를 작성해야 할 것 같습니다..!

### 직렬화
- 객체를 저장, 전송할 수 있는 특정 포맷 상태로 바꾸는 과정.
- Serializable 인터페이스를 구현하여 직렬화를 수행할 수 있다.
- Transient를 이용해 직렬화 제외 가능

### 역직렬화
- 특정 포맷 상태의 데이터를 다시 객체로 변환하는 것
- ObjectinputStream 클래스를 이용해 객체로 변환한다.
- 기본 생성자가 없이도 역직렬화가 가능하다.

학습하며 정리한 내용입니다!

2024-07-28 12:08 UTC, Hheojiwon commented on mission-racing/src/main/java/com/racing/model/Cars.java
> +    private List<Car> cars = new ArrayList<>();
학습하면서, 초기화 값이 객체가 생성될때 동적으로 결정되어야 하는 경우에는 생성자를 통해 초기화 하는것이 유용하다는 점을 알게 되었습니다!
항상 동일한 초기값을 가져야 하는 경우에는 변수를 선언하면서 초기화 하는것이 적합한 것 같습니다.

2024-07-29 02:38 UTC, Hheojiwon commented on mission-racing/src/main/java/com/racing/controller/RacingController.java
> +    public ResponseEntity<CarStatus> getCarStatus(@RequestParam("name") String name) {
params 를 사용하면 name 파라미터가 포함된  경우에만 메서드가 매핑될 수 있고, 하나씩 사용하는 경우에는  required 속성을 이용해서 필수 여부를 조정할 수 있다.

@RequestParam은 @GetMapping과 함께 사용되 요청이 들어오면 URL에서 쿼리 파라미터를 찾아 메서드 파라미터에 바인딩한다. (파라미터 이름으로 바인딩)

2024-07-29 02:39 UTC, Hheojiwon commented on mission-racing/src/main/java/com/racing/controller/CarController.java
> +        Cars cars = new Cars(inputNames);
넵 리팩토링 하였습니다!!

2024-07-29 08:08 UTC, sosow0212 approved these changes
수고하셨습니다!!
꼭 복습 진행하시고 다음 미션 진행해주세요~

2024-07-29 08:08 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/controller/RacingController.java
>          return ResponseEntity.ok(resultResponse);
```suggestion
        return ResponseEntity.ok(RaceResult.resultResponse(cars));
```

선택 사항이지만 이렇게 해도 의미 파악에 문제는 없어서 좋을 것 같습니다!
별개의 리뷰지만 정적 팩토리 메서드에서 메서드 명은 컨벤션은 아니지만 보통 많은 사람들이 of, from, with ... 라는 네이밍을 많이 사용하곤 합니다.

1. of : 정적 팩토리 메서드에서 매개변수가 여러 개인 경우 (적합한 예시로는 자바에서 List.of(1,2,3,4,5)가 있겠네요!)
2. from : 매개변수가 한 개인 경우 (ex. RaceResult.from(cars))
3. 동사 + with : 구체적인 뜻을 부여해주고 싶은 경우 (Car.createWithHandle(...))

2024-07-29 08:08 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/model/Cars.java
> +    private RandomNumber randomNumber;
일급 컬렉션에선 필드는 한 개만 있어야합니다! (객체지향 생활체조 원칙 참고)

같은 메서드를 사용하더라도 아래처럼 두 가지 전략이 동시에 사용될 수도 있으니 randomNumber를 사용하고 싶다면 매개변수에 넣어주시는 게 좋을 것 같아요.
lotto.createNumbers(autoNumberGenerator)
lotto.createNumbers(customNumberGenerator)

2024-07-29 08:09 UTC, merged