Racing/step2 제출입니다!
sosow0212/2024-mju-mentoring-spring-2 pull request #7
Opened 2024-07-18 11:34 UTC by moonwhistle

7/18 racing/step2 제출

처음에 아예 감을 못잡아서 이승엽 파트원에게 조언을 구하여 미션 진행하였습니다.
* 콘솔 코드 부분에서 Name 원시값 포장하였습니다.
* MVC 패턴을 지키기 위해 domain 에서 값을 가져온 뒤 서비스로 넘겨주어 값을 출력할 수 있도록 구현하였습니다.
* 이론들이 많이 어려워서 고생하였지만, 제가 적은 것은 모두 이해하였습니다.
* 이번 미션을 하면서 왜 객체를 잘 나눠야 하고 또,  왜 작은 부분까지 나눠야 하는지 느낄 수 있었습니다.
* 이런 식으로는 아예 처음 작성하는 것인데 피드백 주시면 충실히 고쳐나가겠습니다!

제가 만들었던 콘솔로 미션을 진행하니, 느낌이 새로웠고 재밌었습니다. 감사합니다.

2024-07-19 03:30 UTC, sosow0212 requested changes
수고하셨습니다!
레이어드 아키텍처가 무엇인지 한 번 더 검색해서 확인해보시고 각각 레이어에서 어떤 책임이 있는지 공부해보시면 좋을 것 같습니다.

그리고 객체를 어디서 만들고 관리해줘야하는지, DI는 무엇이고 왜 사용하는지도 조금 더 공부해보면 좋을 것 같아요.

스프링은 프레임워크인데 프레임워크는 결국 개발자가 편리하게 개발하게 도와주는 도구라고 저는 생각하는데, 그렇다면 스프링은 어떤 점을 유용하게 해줄지 고민해보면 좋을 것 같아요 (IoC, DI와 연관 지어서) 이 부분이 지금은 익숙치 않을텐데 자바에서 미션을 진행할 때와 스프링의 빈을 사용해서 웹 미션을 진행할 때 코드에서 어떤 부분이 달라지고 이 부분이 왜 달라졌는지 고민한 번 해보면 좋을 것 같아요~

예를 들면 Controller에서 Service를 선언하고 생성자로 주입받는데, 그렇다면 주입을 어떻게 누가 해줄까요? 우리가 자바 콘솔 미션 때는 직접 Main에서 구현체를 만들어서 넣어줬는데 스프링은 그렇지 않아도 작동 되는 것처럼요. 그렇다면 이 기능을 어떻게 활용할 수 있고, 어떤 구현체를 찾아서 넣어주는지도 고민해보면 좋을 것 같습니다!

2024-07-19 03:30 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/common/domain/Car.java
> +    public int moveCount = INITIAL_NUMBER;
생성자로 만드는 것과 필드에서 초기화하는 것과 무엇이 다를까요?

2024-07-19 03:30 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/common/domain/Cars.java
> +                .collect(Collectors.toList());
이 부분도 메서드 분리를 한 번 해주면 좋을 것 같아요

2024-07-19 03:30 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/common/domain/Cars.java
> +                .filter(car -> car.getMoveCount() == maxCount)
`car.getMoveCount() == maxCount` 캡슐화를 할 수 있겠네요!

2024-07-19 03:30 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/common/domain/exception/CustomErrorCode.java
> +public enum CustomErrorCode {
이런 방법도 좋네요 👍

2024-07-19 03:30 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/controller/WebController.java
> +    private int tryCount;
웹 컨트롤러에 필드가 있어도 될까요?
Service에 있는 것과 무엇이 다를까요? 그리고 서비스에는 도메인을 사용하고자 한다면 어디서 선언하는게 좋을까요?

2024-07-19 03:30 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/controller/WebController.java
> +        this.tryCount = createCars.tryCount();
레이어드 아키텍처에서는 해당 로직들은 비즈니스 로직을 담당하는 서비스에서 진행하는 것이 적합해보입니다!

2024-07-19 03:30 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/controller/WebController.java
> +@RestController
@RestController와 @Controller의 차이는 무엇일까요?

2024-07-19 03:30 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/controller/WebController.java
> +        CreateRandomNumber createRandomNumber = new CarRandomNumber();
스프링에서 구현체를 빈으로 등록하면 해당 객체를 알아서 DI해서 넣어줄 것 같습니다

2024-07-19 03:30 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/controller/WebController.java
> +    private ResponseEntity<Map<String,Object>> getResult() {
API 요청에서 요청과 반환은 모두 Dto로 만들어주세요! Map과 같은 자료구조는 키와 밸류를 협업하는 개발자들이 쉽게 파악할 수 없을 것 같습니다. 이 또한 Dto안에 Dto 구조로 만들던 읽기 쉽게 바꿔주세요!

Dto 네이밍도 고려해보시면 좋겠는데
저는 개인적으로 CreateRequest, CarResultResponse와 같이 Request, Response를 끝에 붙여 쓰는 걸 선호합니다!
상휘님도 여러가지 생각해보고 자신의 기준을 만들면 좋을 것 같습니다~

2024-07-19 03:30 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/controller/WebController.java
> +        racingService.startRace(cars, createRandomNumber, tryCount);
반환이 없는데 ResponseEntity에 Void를 넣어줄 수 있습니다!
ResponseEntity를 사용하면 무엇이 좋을까요?

2024-07-19 03:30 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/controller/WebController.java
> +        }
이것도 비즈니스로직이 전부 컨트롤러로 노출이 되었네요!

2024-07-19 03:30 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/controller/WebController.java
> +    private ResponseEntity<Map<String, Integer>> getResultByName(@RequestParam("name") String name) {
`/api/cars/name?name=xxx` 현재는 이렇게 될 것 같아요

2024-07-19 03:30 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/service/RacingService.java
> +                .orElse(null);
1. 로직 캡슐화가 안 되어있습니다.
2. get, find 네이밍 차이는 무엇일까요?
3. 클라이언트는 있을 거라고 가정하고 찾았는데 없을 때 null 값을 줘도 될까요? 예외를 반환하는 건 어떨까요?

2024-07-19 03:30 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/service/RacingService.java
> +    }
이 부분도 도메인 로직일 것 같습니다~

2024-07-19 05:20 UTC, moonwhistle commented on mission-racing/src/main/java/com/racing/common/domain/Car.java
> +    public int moveCount = INITIAL_NUMBER;
여러 검색을 해보니, 필드에서 초기화 하는 경우 직관적이지만 (해당 필드에 관해서) 복잡한 메서드를 이용하기 어렵다는 사실을 알게 되었습니다. 반면에 생성자로 만들게 되는 경우는 여러 메서드를 유연하게 사용할 수 있다는 사실도 알게 되었습니다. 

저의 경우 moveCount와 관련해서 여러 메서드를 사용하고 있으니, 생성자로 변환하는 것이 더 맞다고 판단하여 생성자 형태로 변환하였습니다!

2024-07-19 05:27 UTC, moonwhistle commented on mission-racing/src/main/java/com/racing/common/domain/Cars.java
> +                .collect(Collectors.toList());
메서드 분리 진행하였습니다!

2024-07-19 05:32 UTC, moonwhistle commented on mission-racing/src/main/java/com/racing/common/domain/Cars.java
> +                .filter(car -> car.getMoveCount() == maxCount)
메서드 따로 분리하여서 캡슐화 진행하였습니다!!

2024-07-19 05:33 UTC, moonwhistle commented on mission-racing/src/main/java/com/racing/common/domain/exception/CustomErrorCode.java
> +public enum CustomErrorCode {
블로그 참고하였습니다 감사합니닷!

2024-07-19 05:47 UTC, moonwhistle commented on mission-racing/src/main/java/com/racing/web/controller/WebController.java
> +    private int tryCount;
스프링 빈으로 등록되는 클래스는 항상 무상태로 설계해야 된다는 것을 알았습니다 !! 이에 관한 내용은 리드미에 따로 작성하였습니다.
Service에서는 메서드 인자로만 받아 사용하기에 문제가 없다는 사실을 알 수 있었습니다!

2024-07-19 06:25 UTC, moonwhistle commented on mission-racing/src/main/java/com/racing/web/controller/WebController.java
> +        CreateRandomNumber createRandomNumber = new CarRandomNumber();
아.. 이론에만 치우쳐서 적용할 생각을 아예 하지 못한 것 같습니다. 더 노력해보겠습니다 알려주셔서 감사합니다!

2024-07-19 06:29 UTC, moonwhistle commented on mission-racing/src/main/java/com/racing/web/service/RacingService.java
> +    }
이미 Name클래스에 구현해 놓았는데 또 구현한 것 같습니다! 제거하였습니다!!

2024-07-19 08:41 UTC, moonwhistle commented on mission-racing/src/main/java/com/racing/web/controller/WebController.java
> +@RestController
- @Controller는 데이터를 객체를 반환할 때, 일반적인 경우 @Responsebody + @ResponseEntity를 활용하여 객체 반환합니다.
- @Restcontroller는 @Controller + @Responsebody 가 합쳐진 어노테이션이므로 @ResponseEntity만을 사용하여 객체 반환(반환 형태는 주로 JSON)합니다.

2024-07-19 08:42 UTC, moonwhistle commented on mission-racing/src/main/java/com/racing/web/controller/WebController.java
> +        racingService.startRace(cars, createRandomNumber, tryCount);
반환되는 객체가 없더라도 상태값을 나타낼 수 있기 때문에, 성공적으로 데이터가 보내졌는지 알 수 있는 것으로 알고 있습니다!!

2024-07-19 09:30 UTC, moonwhistle commented on mission-racing/src/main/java/com/racing/web/controller/WebController.java
> +        this.tryCount = createCars.tryCount();
서비스에서 담당하도록 리팩토링 하였습니다!

2024-07-19 13:10 UTC, moonwhistle commented on mission-racing/src/main/java/com/racing/web/controller/WebController.java
> +        }
비지니스 로직 서비스에 구현하도록 리팩터링 하였습니다!

2024-07-19 13:29 UTC, moonwhistle commented on mission-racing/src/main/java/com/racing/web/controller/WebController.java
> +    private ResponseEntity<Map<String, Integer>> getResultByName(@RequestParam("name") String name) {
앗 실수했습니다. 수정했습니다 !

2024-07-19 13:35 UTC, moonwhistle commented on mission-racing/src/main/java/com/racing/web/controller/WebController.java
> +    private ResponseEntity<Map<String,Object>> getResult() {
모두 dto로 구현하여 쉽게 파악할 수 있게 하였습니다 !

네이밍 관련해서는 여러가지 찾아봤는데, 네이밍을 dto로 통일하면 request인지 response인지 헷갈릴 것 같아서 멘토님 쓰시는 방법으로 작성해보려 합니다!

2024-07-19 13:53 UTC, moonwhistle commented on mission-racing/src/main/java/com/racing/web/service/RacingService.java
> +                .orElse(null);
1. 로직 캡슐화 진행하였습니다.
2. get이라는 네이밍은 있다고 가정하고 꺼내는 것이고(예외가 없는 경우) find는 없을 수도 있다라고 가정하고(예외가 있을 수 있음) 찾을 때 쓰인다는 것을 허지원 파트원 리뷰를 보며 알 수 있었습니다! (멘토님이 써주신 것 입니다.)  이에 따라 저는 네이밍을 find로 바꾸어 줬습니다!
3. Optional로 감싸서 코드를 간소화 하였습니다!

2024-07-20 05:29 UTC, sosow0212 requested changes
코드가 많이 바뀌었네요!
슬슬 감을 잡으신 것 같아서 질문 위주의 코드리뷰를 달아봤습니다.
계층에 대한 이해와 빈에 대한 이해가 이제 슬슬 잡혀가는 단계라서 학습하시면서 답변해보시면 많이 도움될 것 같습니다~

저도 그런 경험이 똑같이 있었는데 개인적으로는 `스프링 공식문서와 baeldung`이라는 사이트 참고해서 원문으로 읽거나 번역하시면서 읽는게 진짜 많이 도움이 됩니다.

학습하면서 계속 DI, IoC는 왜 사용하는지 객체지향적으로도 연관지어보고 SOLID 원칙이랑도 연관지어보고 해당 기능을 사용하면서 (== 스프링을 사용하면서) 웹이 아닌 콘솔로 만들 때랑은 무엇이 달라졌고 어떤 것이 편해졌는지도 계속 고민하다보면 어느 순간 딱 이해가 되는 순간이 생길거에요~

뛰다보면 러너스 하이가 오는 것처럼 스프링도 딱 그 순간이 있는데 꼭 경험해보셨으면 좋겠습니다 ㅋㅋ
동작원리도 포함해서 이런 것들이 유기적으로 연결이 되면 그때는 Bean을 언제 달아줘야하는지에 대해서도 바로바로 떠올려지니 꼭 고민을 많이해보시고 공식문서 많이 읽으시는 걸 추천드립니다!

2024-07-20 05:29 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/controller/WebController.java
> +@RestController
@Controller 잘못 적으신 것 맞죠?! @RestController가 말씀하신 것처럼 @Controller + @ResponseBody 입니다
@Controller는 주로 템플릿엔진(타임리프, jsp...) 띄울 때 자주 사용합니다 ㅎㅎ

2024-07-20 05:29 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/controller/WebController.java
> +        return new ResponseEntity<>(HttpStatus.CREATED);
아래는 `ResponseEntity.ok(...)`로 `*빌더`로 구현하셨는데 여기는 생성자 방식으로 구현하셨네요!
builder와 생성자 방식은 무엇이 다를까요? (이펙티브 자바 없으시다면 사셔서 꼭 읽어보시는 거 추천드립니다)

ResponseEntity는 개인적으로 빌더로 해주는 것이 보기에 명확하고 다양하게 커스텀할 수 있는 것 같아서 선호합니다 ㅎㅎ
둘 다 사용해보시고 개인이 선호하는 것을 정해보시고 + 팀원이 선호하지 않을 경우 반대 케이스도 알아야하니 그 경우도 공부해보시면 좋을 것 같습니다!

2024-07-20 05:29 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/controller/WebController.java
> +    private ResponseEntity<Optional<Map<String, Integer>>> getResultByName(@RequestParam("name") String name) {
최종적으로 클라이언트단에 반환하는데 Optional이 들어가도 될까요? null이 존재한다면 예외를 반환하는게 좋지 않을까요?
1. Optional의 정확한 의미와 역할은 무엇일까요?
2. `Optional 안티패턴`이란 무엇일까요?
3. `Map<String, Integer>`로 반환하면 무엇이 문제일까요? Dto로 보내는 방법은 없을까요?
4. 스프링에서 `throw new ... `와 같은 예외가 발생하면 클라이언트단에는 어떻게 반환이 될까요?
5. 4번 질문에 이어서 스프링에선 예외 응답을 설정하고 커스텀하게 예외 메시지를 수정해서 반환할 수 있을까요?

2024-07-20 05:29 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/repository/CarRepository.java
> +    }
이 부분이 조금 어색한데요
1. 네이밍은 find가 더 적절하지 않을까요? 이유는 무엇일까요?
2. reverseOrder 메서드가 필요할까요? API에서 자동차 정보를 반환할 때 `name`이 들어오는데 그렇다면 map.get(name)을 하면 해결해줄 수 있지 않을까요?!

2024-07-20 05:29 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/repository/CarRepository.java
> +@Repository
Bean으로 등록해주셨네요!

1. 빈 말고 그냥 일반 객체로 선언하는 것과 Bean으로 등록하는 것과 무엇이 다를까요?
2. 그렇다면 언제 객체를 빈으로 등록하는 것이 좋을까요?

2024-07-20 05:29 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/service/RacingService.java
> +        }
저장의 책임은 Repository에 있을 것 같은데
`carRepository.saveAll(List<Car>)` 형식이 되면 응집도도 높아지고 가독성도 더 좋을 것 같아요 ㅎㅎ 
(해당 리뷰는 관점에 차이가 있어서 안 지켜도 되긴 합니다! -> SaveAll이 없다고 전제할 수도 있으니깐요!)

2024-07-20 05:29 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/controller/WebController.java
> +    private final CreateRandomNumber createRandomNumber;
이것도 결국 도메인 메서드인데 책임 측면에서 컨트롤러보다는 서비스에서 가지고 있다가 주입해주는 것이 좋지 않을까요?

2024-07-20 05:29 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/service/RacingService.java
> +        List<String> winner = Cars.getWinner(cars);
Cars.getWinner 보다

List<car> foundCars를 repository에서 꺼내온 후에 
`Cars cars = new Cars(foundCars); ` 이렇게 일급 컬렉션으로 만들어준 후 `cars.getWinner()`를 해주는 것이 응집성도 높을 것 같습니다!

지금은 static 메서드로 수행을 하는데 어색해보여서요 ㅎㅎ

2024-07-20 05:29 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/service/RacingService.java
> +        return new CarResultResponse(String.join(",", winner), getCarStatus(cars));
반환을 위한 간단한 로직은 dto에서 처리해주셔도 됩니다!
`return CarResultResponse.from(cars (일급컬렉션)); `

이렇게 해주고 내부에서 알아서 로직을 처리해주는 것처럼요~ 근데 dto가 도메인을 의존한다는 단점이 있긴 하지만 어차피 변환만 하는 정도라면 저는 개인적으론 타협해도 된다고 생각합니다. (복잡해진다면 서비스 코드가 너무 길어지고 다른 코드들을 보기 힘들어서)

2024-07-20 05:29 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/service/RacingService.java
> +    }
이 부분에서도 repository에서 모든 것을 꺼내고 stream을 통해 이름과 일치하는지를 찾고있네요

db에서 찾는 행위는 repository에서의 역할인데요. 그렇다면 서비스에서는 실제로 repository에 데이터가 있는지 없는지만 알면 되지 않을까요?

정리하자면 name에 해당하는 값이 있을 수도 없을 수도 있으니 repository에서는 `findByName(name)` 이라는 메서드를 만들고 반환형은 Optional<Car>로 해준 후 

서비스레이어에서 
Car foundCar = repository.findByName(name)
                                            .orElseThrow(예외)

이런식으로 해준다면 책임에 맞게 로직을 분리도 하고 예외도 처리해줄 수 있을 것 같습니다!

어차피 사용자는 이름에 해당하는 자동차가 있을거라 생각하고 조회를 했으니 없다면 없다고 예외를 발생해주는 것이 클라이언트단에서 처리하기도 좋아보이고요~

2024-07-20 05:29 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/dto/CarResultResponse.java
> +public record CarResultResponse(String winner, List<Map<String, Integer>> status) {
Map<String, Integer>에서 key, value가 각각 무엇을 의미하는지 알기 힘듭니다.
Map<String, Integer> 자체를 dto로 만들고 List<dto>를 반환해주는 것이 좋지 않을까요?

2024-07-22 10:08 UTC, moonwhistle commented on mission-racing/src/main/java/com/racing/web/controller/WebController.java
> +        return new ResponseEntity<>(HttpStatus.CREATED);
생성자 방식으로 구현하게 되는 경우, 굳이 안넣어줘도 될 매개변수를 넣어주거나 나중에 많은 정보를 포함시키기 위해 매개변수를 넣어줄 때 가독성이 떨어질 것 같습니다. 
하지만 builder 패턴으로 구현하는 경우, 필요한 매개변수만 넣어주면 되기에 가독성도 훨씬 좋고 생성자 방식보다 안정성이 있다고 하여 builder 패턴으로 구현하도록 리팩터링 하였습니다!

2024-07-22 10:42 UTC, moonwhistle commented on mission-racing/src/main/java/com/racing/web/repository/CarRepository.java
> +    }
1. 네이밍의 경우 finde가 적절할 것 같습니다!! Repository에서 꺼내려는 Car들이 있을 수 도 있고 없을 수 도 있기 때문입니다!
2. Repository 에 reverseOrder 과 같은 메서드는 어울리지 않는다는 사실을 깨달았습니다 ! 멘토님 리뷰 참고하여 name 값 따로 저장해주는 리스트 파고 map.get(name) 과 같은 방식으로 값 꺼내올 수 있도록 하였습니다!

2024-07-22 11:08 UTC, moonwhistle commented on mission-racing/src/main/java/com/racing/web/service/RacingService.java
> +        }
jparepository 인터페이스 관련해서 찾아봤을 때, saveAll 메서드가 있어서 구현할까 하였지만 별 생각 없이 save로 구현했던 것 같습니다!! 연습하는 겸 리팩터링 하였습니다!!

2024-07-22 11:11 UTC, moonwhistle commented on mission-racing/src/main/java/com/racing/web/controller/WebController.java
> +    private final CreateRandomNumber createRandomNumber;
오.. 서비스에서 구현하는 것이 더 좋은 것 같습니다!! 리팩터링 하였습니다.

2024-07-22 11:31 UTC, moonwhistle commented on mission-racing/src/main/java/com/racing/web/service/RacingService.java
> +    }
저번에 코드를 작성하면서 repository와 service 의 책임을 정확하게 못 나눴다는 사실을 계속 코드 고치며 느끼고 있습니다. 멘토님 조언대로 하니, 메소드가 더욱 간결해져서 좋은 것 같습니다. 감사합니다.

2024-07-22 12:01 UTC, moonwhistle commented on mission-racing/src/main/java/com/racing/web/dto/CarResultResponse.java
> +public record CarResultResponse(String winner, List<Map<String, Integer>> status) {
dto로 리펙터링 하였습니다!

2024-07-22 12:05 UTC, moonwhistle commented on mission-racing/src/main/java/com/racing/web/service/RacingService.java
> +        return new CarResultResponse(String.join(",", winner), getCarStatus(cars));
멘토님 조언대로 리팩터링 하였습니다. !!

2024-07-22 14:35 UTC, moonwhistle commented on mission-racing/src/main/java/com/racing/web/service/RacingService.java
> +        List<String> winner = Cars.getWinner(cars);
원래 Cars는 매개변수를 List<Name>으로 받는데, List<Car>를 받아주기 위해 오버로딩하여 리팩터링 진행하였습니다!

2024-07-22 15:05 UTC, moonwhistle commented on mission-racing/src/main/java/com/racing/web/repository/CarRepository.java
> +@Repository
## 일반 객체로 선언하는 것과 빈으로 등록하는 것의 차이

1. 생성 및 관리
   - 일반 객체: 개발자가 명시적으로 객체를 생성하고 관리해야 한다. 객체 생성 시 의존성 주입, 라이프사이클 관리, 초기화 및 소멸 작업을 수동으로 처리해야 함.
   - 빈 객체: Spring 컨테이너에 의해 관리. Spring이 빈의 생성, 의존성 주입, 라이프사이클 관리, 초기화 및 소멸 작업을 자동으로 처리한다.

2. 의존성 주입 (Dependency Injection):
   - 일반 객체: 의존성을 직접 코드 내에서 주입해야 함. 
   - 빈 객체: Spring이 자동으로 의존성을 주입. 생성자 주입, 세터 주입, 필드 주입 등 다양한 방식으로 주입할 수 있다.

3. 스코프:
   - 일반 객체: 객체의 스코프를 직접 관리해야 함. (싱글톤, 프로토타입 등)
   - 빈 객체: Spring이 빈의 스코프를 관리한다. 기본적으로 싱글톤 스코프이지만, 다른 스코프(프로토타입, 요청, 세션 등)로 설정할 수 있음.


## 언제 빈으로 등록하는 것이 좋을까 ? 

1. 의존성 주입이 필요한 경우 
2. 객체의 스코프가 중요한 경우

리드미에 정리한 내용입니다 !

2024-07-22 15:11 UTC, moonwhistle commented on mission-racing/src/main/java/com/racing/web/controller/WebController.java
> +    private ResponseEntity<Optional<Map<String, Integer>>> getResultByName(@RequestParam("name") String name) {
## Optional

### Optional 이란 
* null이 올 수 있는 값을 감싸는 Wrapper 클래스로, 참조하더라도 NPE가 발생하지 않도록 도와주는 클래스이다.

### 안티패턴이란? 
* 안티패턴은 실제 많이 사용되는 패턴이지만 비효율적이거나 비생산적인 패턴을 의미한다. 안티패턴은 성능, 디버깅, 유지보수, 가독성등에 있어 부정적인 영향을 줄 수 있기 때문에 지양해야하는 패턴이다.

### Optional 안티패턴
* 필드로 사용금지
  * Optional은 Serializable를 구현하지 않기 때문에 필드로 사용하면 안된다.
  
* isPresent()-get() 대신 orElse(), orElseGet(), orElseThrow() 사용하기

* Optional을 생성자나 메서드 파라메터로 사용금지

* orElse() 대신 orElseGet(), orElseThrow() 사용하기


3. Map<String, Integer> 로 반환하면 다른 코드 읽는 분들이 String, Integer 가 무엇을 뜻하는지 정확히 모르실 것 같습니다.

4. exception 메세지를 설정했다면 메세지를 반환할 것 같습니다!! (객체에 exception 메세지를 넣어서 보냄.)

5. exception을 커스텀 하여 반환할 수 있는 것으로 알고 있습니다. exceptionHandler(ExceptionController)도 쓰이는 것으로 알고 있습니다!!

2024-07-23 07:33 UTC, sosow0212 approved these changes
수고하셨습니다! 몇 가지 아쉬운 부분이 있는데 리뷰 확인해보시고 고민한 후에 다음 미션 때는 반영해주세요 ㅎㅎ 어느정도 구조적으로도 파악하신 것 같네요!
아마 다음 미션부터는 더 어려워질텐데 복습도 한 번 하시고 개념 싹 다시 잡고 가시는 것 추천드립니다!
복습하실 땐 꼭 스프링 공식문서와 baeldung 사이트 가셔서 키워드 검색 및 학습 해주세요~

2024-07-23 07:33 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/console/view/InputVIew.java
> +    private final Scanner input = new Scanner(System.in);
1. 클래스 네이밍 실수가 있습니다😂 ㅋㅋ
2. Scanner도 외부에서 받는 것과 지금처럼 받는 것의 차이는 무엇일까요? 각자 어떤 장단점이 있을까요

2024-07-23 07:33 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/dto/CarStatusResponse.java
> +    private final Map<String, Integer> carStatus;
```suggestion
public class CarStatusResponse {

    private final Map<String, Integer> carStatus;
```

2024-07-23 07:33 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/dto/CarStatusResponse.java
> +    private final Map<String, Integer> carStatus;
Map에서 key와 value가 어떤 값인지 어떤 의미를 가지는지 다른 개발자는 알기 힘들 것 같아요.
Map<String, Integer> 자체도 dto로 만들 수 있지 않을까요?

현재 클래스 명도 여러 차의 정보를 주니깐 CarsStatusResponse로 바꿔도 좋을 것 같고 아래처럼 Map을 Dto로 감싸주세요
CarsStatusResponse { List<CarStatusResponse> }

2024-07-23 07:33 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/dto/CarStatusResponse.java
> +    }
이 코드는 어떤 역할을 하고 @JsonAnyGetter 어노테이션은 무슨 역할을 할까요?
이 코드가 없다면 클라이언트측으로 반환이 안 될까요? 이유는 무엇일까요!

2024-07-23 07:33 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/repository/CarRepository.java
> +    private int tryCount;
`Map<이름, Car객체> db`  이 정도로만 있어도 되지 않을까요? 보통 테이블이 있는 경우는 id(pk)값을 키로 가져가지만 지금은 이름에 해당하는 차랑 객체만 있어도 될 것 같아요. tryCount도 필요하다면 전체를 하나의 cars로 묶고 tryCount까지 관리하는 객체가 있어도 될 것 같고요 carNames는 필요하지 않아 보입니다!

2024-07-23 07:33 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/repository/CarRepository.java
> +    }
map에 저장한다면, map.keySet()을 하면 모든 CarNames를 조회할 수 있을텐데 해당 메서드는 불필요해보입니다! (필드도 마찬가지고요)

2024-07-23 07:33 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/repository/CarRepository.java
> +    }
return map.values()로 해도 되지 않을까요?

2024-07-23 07:33 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/repository/CarRepository.java
> +        return Optional.ofNullable(database.get(name));
👍 값이 없다면 null값 처리에 대한 책임은 해당 메서드를 호출하는 Service에서 할 수 있도록 처리하셨군요!

2024-07-23 07:33 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/service/RacingService.java
> +        carRepository.saveTryCount(createRequest.tryCount());
`carRepository.saveCars(cars);` 이렇게 할 순 없을까요? moveCount가 걸린다면 한단계 더 상위 객체를 만들어도 될 것 같아요 아니면 요구사항이 정해진 것이 아니니 `재시작시 사용자의 moveCount는 5로 고정된다`라는 스스로의 규칙을 만들어도 될 것 같고요 ㅎㅎ

2024-07-24 06:13 UTC, moonwhistle commented on mission-racing/src/main/java/com/racing/console/view/InputVIew.java
> +    private final Scanner input = new Scanner(System.in);
1. 클래스 네이밍 수정하였습니다!! ㅠ
2. 외부에서 받게 된다면, 다른 입력소스도 넣어줄 수 있어서  테스트 시 편할 것 같습니다. 또한, 스캐너에 의존성을 끊을 수 있을 것 같습니다!! 이러한 이유로 외부에서 주입받도록 코드 수정하였습니다.

2024-07-24 06:15 UTC, moonwhistle commented on mission-racing/src/main/java/com/racing/web/dto/CarStatusResponse.java
> +    private final Map<String, Integer> carStatus;
개행 수정하였습니다!!

2024-07-24 06:57 UTC, moonwhistle commented on mission-racing/src/main/java/com/racing/web/dto/CarStatusResponse.java
> +    private final Map<String, Integer> carStatus;
Map<String, Interger> -> Map<CarNameResponse, MoveCountResponse> 이런식으로 key와 value 를 알 수 있도록 dto로 만들었습니다!!

2024-07-24 07:04 UTC, moonwhistle commented on mission-racing/src/main/java/com/racing/web/dto/CarStatusResponse.java
> +    }
1. @JsonAnyGetter 어노테이션은 Map의 필드 속성이 직렬화 되어 나타내게 하는 어노테이션입니다!
2. 클라이언트 측으로 반환은 되지만 {"CarName" : "jay", "MoveCount": "3"} 이러한 형식으로 반환됩니다. 문제에서 주어진 반환 형식은 {"jay" : "3"} 이므로, JsonAnyGetter를 사용했습니다!

2024-07-24 07:16 UTC, moonwhistle commented on mission-racing/src/main/java/com/racing/web/repository/CarRepository.java
> +    private int tryCount;
tryCount 만 관리하는 객체와 Map<이름, Car객체> db 만 있도록 리팩터링 하였습니다!

2024-07-24 07:16 UTC, moonwhistle commented on mission-racing/src/main/java/com/racing/web/repository/CarRepository.java
> +    }
다시 코드를 보니 필요없는 메서드였던 것 같습니다..;; 삭제하여 리팩터링 하였습니다!

2024-07-24 07:18 UTC, moonwhistle commented on mission-racing/src/main/java/com/racing/web/repository/CarRepository.java
> +    }
map.values() 하였을 때 , 데이터가 큐 형식으로 반환되어서 Response 값이 문제 조건과 달라 이러한 코드를 작성했던 것 같습니다. Map databse = LinkedHashMap 으로 바꾸어 문제 해결하였습니다!

2024-07-24 07:19 UTC, moonwhistle commented on mission-racing/src/main/java/com/racing/web/repository/CarRepository.java
> +        return Optional.ofNullable(database.get(name));
멘토님이 힌트 주신 덕분입니다..!

2024-07-24 07:27 UTC, moonwhistle commented on mission-racing/src/main/java/com/racing/web/service/RacingService.java
> +        carRepository.saveTryCount(createRequest.tryCount());
carRepository.saveCars(cars); 이러한 형식으로 할 수 있도록 리팩터링 하였습니다 ! 뭔가 코드를 고칠수록 저번에 작성한 코드에서 불필요한 코드가 많았다는 느낌이 듭니다..ㅠ

2024-07-24 07:51 UTC, sosow0212 commented on mission-racing/src/main/java/com/racing/web/dto/CarStatusResponse.java
> +    private final Map<String, Integer> carStatus;
Map<CarNameResponse, MoveCountResponse> 이것보다는 
지금 상태에선 List<...Response> 이런 구조가 되는게 좋지 않을까요?!

Map을 씌웠을때 json과 List<Dto>의 json 반환 형식은 어떻게 다를까요?
한 번 확인해보시면 좋을 것 같아요.

2024-07-24 07:52 UTC, merged