Lotto/step2 미션 피드백 요청
sosow0212/2024-mju-mentoring-spring-2 pull request #9
Opened 2024-07-31 11:40 UTC by SEUNGBOONG

7월 31마크다운에 적어 두었습니다! 

지금 JPA 공부 방향성이 틀렸다고 결론이 났습니다
계속 고집부리면서 스스로 공부해본결과 머리가 멈춰서 피드백이 필요합니다! 
아예 처음으로 돌아가서 공부해야할것 같습니다 
데이터 전송방식이 잘못된것을 알겠는데 최소 10시간은 고민한 것 같은데 아무리생각해도 모르겠습니다

2024-07-31 13:10 UTC, sosow0212 requested changes
몇 가지 컨벤션 확인해주세요! setter를 사용하시는데 캡슐화랑 관련해서 무엇이 단점인지 고민해보시면 좋을 것 같아요! 리뷰 보시고 모르는 부분 있으면 연락주세요~

2024-07-31 13:10 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/controller/LottoController.java
> +    }
1. POST /api/lottos/buy 로 요청을 보내게될텐데요 RESTful 에서는 어떻게 표기하는게 좋을까요? 표기법 한 번 찾아보시면 도움 많이 되실 것 같아요
2. 반환 타입은 Dto로 감싸서 주세요! 
3. 프론트엔드가 `구매 완료됨`이라는 반환 바디가 필요할까요? 때에 따라서 응답코드로 반환받을 수 있지만 보통은 실패하는 경우의 반환 바디가 더 중요하다고 생각이듭니다!

2024-07-31 13:10 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/controller/LottoController.java
> +                .count() * 1000;
비즈니스 로직이 컨트롤러로 노출이 됐네요!
서비스에서 도메인의 메서드를 이용해 상태값을 바꾼 후 반환해주는 건 어떨까요?

2024-07-31 13:10 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/controller/LottoController.java
> +    private UserService userService;
Lotto에서 LottoService, UserService 총 두개의 관심사를 알고 있어야되네요~
지금은 배우지 않았지만 다음 미션 때 이 부분 한 번 같이 수정해봅시다!

2024-07-31 13:10 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/controller/dto/BuyRequest.java
> +@Data
@Data 어노테이션은 지양해주세요 record를 쓸 수도 있지만 왜 @Data를 지양해야할까요?

2024-07-31 13:10 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/domain/Lottos.java
> +    private final NumberGenerator numberGenerator;
이것도 필드로 관리하기보단 도메인 메서드 매개변수로 사용할 수 있지 않을까요?
현재 방식대로라면 로또 생성 전략이 수동생성 후 자동생성이라면 객체도 두 개가 생길 것 같아요.

2024-07-31 13:10 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/entity/LottoTicket.java
> +@Setter
Setter는 사용 지양해주세요

2024-07-31 13:10 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/entity/LottoTicket.java
> +@NoArgsConstructor
이렇게만 사용한다면 외부에서도 사용할 수 있지 않을까요?

2024-07-31 13:10 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/entity/LottoTicket.java
> +    private List<Integer> numbers;
1. 현재는 저장하면 데이터베이스에 어떤식으로 저장이될까요?
2. 테이블 분리가 나쁜 것은 아니지만 String으로 연결하는 방식을 사용한다면 간결하게 표현할 순 있을 것 같아요. 그러면 이때는 어떤 단점이 있을까요? (데이터 조회 차원에서)

2024-07-31 13:10 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/entity/LottoTicket.java
> +    private boolean winner;
네이밍 확인해주세요!

2024-07-31 13:10 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/repository/LottoTicketRepository.java
> +public interface LottoTicketRepository extends JpaRepository<LottoTicket, Long> {
JpaRepository에서 @Repository가 이미 들어가있기 때문에 어노테이션이 없어도 됩니다

2024-07-31 13:10 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/entity/LottoTicket.java
> +package com.lotto.entity;
Entity와 Domain의 차이는 무엇일까요?

2024-07-31 13:10 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/domain/Lottos.java
> +        }
개별적인 로또의 생성책임은 로또한테 주는 것이 좋을 것 같아요.
현재는 Lotto 객체가 하는 일이 없어보입니다!

2024-07-31 13:10 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/domain/RandomNumberGenerator.java
> +public class RandomNumberGenerator implements NumberGenerator {
해당 클래스를 Bean으로 등록하면 무엇이 좋을까요?

2024-07-31 13:10 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/service/LottoService.java
> +    @Autowired
Autowired 지양해주세요

2024-07-31 13:10 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/service/LottoService.java
> +    private void settingLottos(final List<Lotto> generateLottos, final User user) {
네이밍이 적절하지 않아보입니다!

2024-07-31 13:10 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/service/LottoService.java
> +        user.setBalance(user.getBalance() - ticketCount * 1000);
캡슐화가 안 되어있습니다

2024-07-31 13:10 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/service/LottoService.java
> +    }
이것도 캡슐화가 안 되어있습니다!

2024-07-31 13:10 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/service/LottoService.java
> +        }
saveAll 메서드도 알아보시면 좋을 것 같아요~

2024-07-31 13:10 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/service/UserService.java
> +    @Transactional
readonly 속성도 공부해보시면 좋을 것 같습니다

2024-07-31 13:10 UTC, sosow0212 commented on study/lotto/7월31일까지.md
> +- 유저 네임은 ? 겹칠수가 있어서 계속해서 고민중에있었다
unique 속성에 대해 공부해보시면 좋을 것 같습니다!
+ pk로 id는 왜 사용하는지도 생각해보면 좋을 것 같습니다~

2024-07-31 13:10 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/service/UserService.java
> +        User user = new User(userName, balance);
이 예외도 정팩메로 넘겨줄 수 있지 않을까요? 도메인 로직이 노출되어있습니다

2024-07-31 13:10 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/entity/LottoTicket.java
> +    private Long userId;
간접참조를 하셨는데 직접참조(JPA 매핑)과 어떤 차이가 있을까요?

직접참조 방식으로 매핑을 한다면 어떤 어노테이션을 사용해야할까요?

2024-08-01 05:33 UTC, SEUNGBOONG commented on mission-lotto/src/main/java/com/lotto/controller/LottoController.java
> +    private UserService userService;
이부분이 가장 큰 고민이 있엇던 부분입니다 ,,, 
사실상 이부분 고민이 전반적으로 차지해서 다른 과정까지 파생적으로 고민했던것 같습니다.. 결국 
서비스를 두개를 의존하기보단 Lotto는 로또끼리 유저는 유저끼리 구조를 해보고싶었는데 해결이되지 않았습니다
그래서 떠오른 방법이 - >  DTO느낌처럼 서비스도 이런 느낌에 서비스클래스를 만들면되지않을까 ? 정도 였습니다

2024-08-01 05:36 UTC, SEUNGBOONG commented on mission-lotto/src/main/java/com/lotto/controller/dto/BuyRequest.java
> +@Data
# data 어노테이션

- ToString Getter Setter EqualsAndHashCode RequiredArgsConstructor 을 모두 포함하는 강력한 어노테이션이다
- @ToString : toString 메소드를 자동생성

- @Getter : 모든 필드의 getter메소드 가 자동 생성

- @Setter : 모든 필드의 setter 메소드가 자동 생성
  
- @EqualsAndHashCode : equals, hashCode 메서드 자동생성
  
- @RequiredArgsConstructor : final이나 @NonNull인 필드 값만 파라미터로 받는 생성자 자동생성.

- 예를 들어 id의 필드가 변경을 허용치 않기로했다면 setter가 없어야한다. 
- 하지만 data를 사용하면 id필드도 세터가 생성되기떄문에 안정성을 보장받을 수 없게됩니다.!

2024-08-01 07:35 UTC, SEUNGBOONG commented on mission-lotto/src/main/java/com/lotto/service/LottoService.java
> +        }
넵

2024-08-01 07:38 UTC, SEUNGBOONG commented on mission-lotto/src/main/java/com/lotto/domain/Lottos.java
> +    private final NumberGenerator numberGenerator;
넵

2024-08-01 08:40 UTC, SEUNGBOONG commented on mission-lotto/src/main/java/com/lotto/service/UserService.java
> +        User user = new User(userName, balance);
넵 수정했씁니다

2024-08-01 08:41 UTC, SEUNGBOONG commented on mission-lotto/src/main/java/com/lotto/entity/LottoTicket.java
> +    private Long userId;
DDD 방식에서 에그리거트와 다른 에그리거트 관계에서 직접 참조 보단 간접 참조를 권장한다고 되어있습니다!
직접참조는 OneToOne OneToMany를 사용합니다.

2024-08-12 05:45 UTC, sosow0212 requested changes
객체지향이 점점 지켜지지 않는 것 같아서 속상합니다 🥲

리뷰 확인해보시고 천천히 다시 고민해보시는 건 어떨까요? 리뷰에서 근사한 코드를 말해드릴 수도 있지만 왜 그렇게 사용하는지는 스스로가 깨우쳐야하기 때문에 진짜 고민하다가 모르겠으면 카톡으로 말씀해주세요!

지금은 계층 구조에 대해 헷갈리시는 것 같고, 그러면서 도메인 로직이 서비스로 많이 노출되어 있습니다.
또한 Controller단에서도 RESTful이 지켜지지 않은 상태입니다.

도메인에 빈을 달으신 부분도 있어서 빈으로 언제 정의 해야하는지도 공식문서로 꼭 학습하셔야하고,
테이블 설계에서도 어떻게 테이블을 생성하면 좋을지 고민해보셔도 좋을 것 같아요.

테이블 설계를 위해선 Entity VS Domain이란 무엇이 다른지 학습해보시는게 먼저일 것 같고, 그후에는 JPA를 사용하는 목적 자체가 결국 객체지향적으로 사용하기 위해서인데 지금은 Entity + JPA가 섞여있는 구조입니다. 즉 Entity를 도메인처럼 사용하고 계신 것 같은데 정답도 없고 보통 이렇게들 많이 사용해서 이게 잘못된 구조는 아니긴 하지만 Entity와 Domain 이 둘의 확실한 차이를 알고 적용한다면 또 다른 관점에서 개발할 수 있는 좋은 기회가 될 것 같습니다. 

실제로는 Entity와 Domain을 분리하고 중간에 Mapper를 이용하기도 하지만 여기까지는 아직 알 필요가 없긴하니 JPA 매핑에 대해서 학습해보시고 더 적절한 테이블 설계는 어떤 것일지 많이 고민해보시면 좋을 것 같습니다!

2024-08-12 05:45 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/lottoTicket/controller/LottoController.java
> +    @PostMapping("/setWinningNumbers")
RESTful 학습해보시면 url 설계 규칙에 명사는 피하라고 나와있습니다.
적절한 네이밍으로 변경이 필요해보입니다!

2024-08-12 05:45 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/lottoTicket/controller/LottoController.java
> +    @PostMapping("/setWinningNumbers")
다른 부분도 url 설계를 다시 하셔야할 것 같습니다 ㅠ

2024-08-12 05:45 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/lottoTicket/controller/LottoController.java
> +    }
도메인 로직이 컨트롤러까지 노출되어 있습니다!

2024-08-12 05:45 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/lottoTicket/controller/LottoController.java
> +                .toList();
위에도 그렇고 해당 코드들을 서비스에서 캡슐화 할 수 있지 않을까요?

2024-08-12 05:45 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/lottoTicket/controller/dto/LottoResponse.java
> +    private final int winnings;
winnings가 무엇을 의미하는지 알기 어려울 것 같습니다 ㅠ

2024-08-12 05:45 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/lottoTicket/controller/dto/WinningNumbersDTO.java
> +public record WinningNumbersDTO(@NotNull List<Integer> winningNumbers) {
이전 리뷰에서 말씀드렸지만 Dto라는 네이밍은 request인지 response인지 쉽게 알기 힘듭니다.
따라서 WinningNumbersResponse, WinningNumbersRequest와 같은 네이밍으로 설계해주세요

2024-08-12 05:45 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/lottoTicket/controller/dto/WinningNumbersDTO.java
> +    }
해당 코드들이 record에서 필요할까요? 어떤 의도로 작성하신 코드일까요?

2024-08-12 05:45 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/lottoTicket/controller/message/SettingWinningNumbers.java
> +}
해당 클래스도 의미없는 클래스인 것 같습니다.
로그가 필요하다면 log.info와 같이 로깅을 사용하는게 적절할 것 같습니다 !

2024-08-12 05:45 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/lottoTicket/domain/entity/Lotto.java
> +public class Lotto {
테이블은 Lottos이고 클래스명은 Lotto인 이유가 있을까요?

2024-08-12 05:45 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/lottoTicket/domain/repository/LottoRepository.java
> +@Repository
JpaRepository를 상속받는 클래스인데 해당 클래스 안에는 이미 @Repository 어노테이션이 있어서 LottoRepository에는 @Repository가 없어도 빈으로 작동이 됩니다!

2024-08-12 05:45 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/lottoTicket/infrastructure/vo/LottoTickets.java
> +@Component
해당 클래스를 빈으로 등록하신 이유가 있으신가요?

2024-08-12 05:45 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/lottoTicket/infrastructure/vo/LottoTickets.java
> +    private final List<LottoTicket> tickets;
일급컬렉션 객체인데 LottoGenerator도 필드로 관리할 필요가 있을까요? 생성 메서드에 매개변수로 받아도 충분할 것 같습니다

2024-08-12 05:45 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/lottoTicket/service/LottoService.java
> +    private List<Integer> winningNumbers;
필드로 winningNumbers를 두고 getter로 받아오는 이유가 있을까요?
어떤 의도에서 다음과 같이 구현하셨는지 궁금합니다!

LottoService는 싱글톤 객체인데 레이스컨디션이 일어나지 않을까요?

2024-08-12 05:45 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/lottoTicket/service/LottoService.java
> +    }
도메인 로직이 외부에 노출되어있습니다
getter로 값을 꺼내 외부의 값과 비교하기보다는 1000원이라는 값은 도메인이 알아야되는 값이 아닐까요?

lotto.generate(생성인터페이스, 로또가격) 이렇게 둔다면 문제가 있다면 도메인 내부에서 예외를 발생시키고 정상이라면 계산한 후 적절한 값을 반환할텐데

서비스에서는 현재 생성과 도메인 로직에 관여를 하고 있습니다!

2024-08-12 05:45 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/lottoTicket/service/LottoService.java
> +    }
이 부분도 도메인 로직이 외부로 노출되었습니다 ㅠ

2024-08-12 05:45 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/lottoTicket/service/LottoService.java
> +    }
해당 코드는 정상적으로 작동되지 않을 것 같습니다!
이것도 도메인 로직을 통해 구매 후 반환이나 우승을 판단해서 반환할 수 있지 않을까요?

2024-08-12 05:45 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/lottoTicket/service/LottoService.java
> +        user.setLottoCount(user.getLottoCount() + ticketCount);
setter는 지양해주세요!
도메인에서 구매에 따른 값 변경은 스스로 처리하는 것이 해당 도메인의 책임이자 역할같습니다!

2024-08-12 05:45 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/lottoTicket/service/LottoService.java
> +    }
이 부분도 테이블 설계를 다르게 하신다면
`var memberLotto = MemberLotto.findByMemberId(memberId)...`
`var something = memberLotto.getSomething(...)`
`something.doDomainMethod()...`

이렇게 나눠볼 수 있을 것 같습니다.
Lotto, User가 있다면 MemberLotto(Long id, Member member, Lotto lotto)와 같이 중간테이블을 둔다면 모든 문제를 해결할 수 있을 것 같습니다!

간접참조나 매핑을 하셔도 되고요

2024-08-12 05:45 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/lottoTicket/service/exception/InsufficientBalanceException.java
> +}
다른 클래스도 마지막 개행이 아직도 추가가 되지 않습니다 ㅠ
```suggestion
}
```

2024-08-12 05:45 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/user/domain/entity/User.java
> +@Setter
Setter 사용은 지양해주세요 외부에서 값을 수정한다면 도메인이 자신의 책임을 수행하지 못하고 외부에서 수행해줄 것 같습니다

2024-08-12 05:45 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/user/domain/entity/User.java
> +@NoArgsConstructor
접근제어자 설정을 따로 하지 않으면 외부에서 빈생성자를 통해 부적절한 초기 값이 있는 객체를 만들 수 있지 않을까요?

2024-08-12 05:45 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/user/service/UserService.java
> +                .build();
이 부분도 0이라는 초기값을 외부에서 주입해주는데 그렇다면 초기값 설정에 대한 책임은 Service에 있는데 도메인이 해당 책임을 가지는게 유지보수측면과 객체지향 측면에서 적절할 것 같습니다.
User.createWithDefaultLotto...()와 같은 정적팩토리 메서드를 통해 꼭 필요한 값만 넣어주는 게 좋을 것 같습니다

2024-08-12 05:45 UTC, sosow0212 commented on mission-lotto/src/main/java/com/lotto/user/service/UserService.java
> +        }
1. 해당 메서드는 static일 필요가 없습니다 ㅠ
2. 도메인 로직이 노출되었습니다!

2024-08-12 05:45 UTC, sosow0212 commented on mission-lotto/src/test/java/com/lotto/lottoTicket/controller/LottoControllerTest.java
> +                        .content("{\"winningNumbers\":[1,2,3,4,5,6]}"))
objectMapper를 통해 초기 값을 세팅해준 dto로 매핑해준다면 위와 같이 raw타입을 쓰지 않아도 됩니다!

2024-08-12 05:45 UTC, sosow0212 commented on mission-lotto/src/test/java/com/lotto/user/controller/UserControllerTest.java
> +                        .content("{\"userName\":\"John Doe\",\"balance\":1000}"))
이 부분도 마찬가지입니다!

2024-08-12 05:45 UTC, sosow0212 commented on study/lotto/4질문내용.md
> +   - 결국 컨트롤러에서만 DTO를 사용해야 하는것이 아닌지 ?
기본적으로 서비스에서는 `값이 변경된 도메인을 반환해주고` 컨트롤러에서는 `도메인을 dto로 변환해주는 것`이 레이어드아키텍처에서의 책임이라고 생각합니다.

물론 서비스를 조회와 명령으로 나눈다면 순수 데이터 조회만 하는 조회 서비스에서는 dto로 필요한 컬럼을 감싼 dto를 반환할 수 있지만 현재 미션에서는 이렇게 할 필요가 없으니 서비스에서는 domain을 반환, 컨트롤러에서는 이걸 dto로 변환 해주면 될 것 같습니다!

2024-08-12 05:45 UTC, sosow0212 commented on study/lotto/8월2일.md
> +- 검색 GPT 등 다양한거 계속 시도해봐도 결과는 같음 오히려 자꾸 모르는 것들 만 추가되고 공부도 안하고쓰니까 더 헷갈림이제
ㅠㅠ gpt를 사용하는 것도 좋은데 일단 키워드 하나씩 학습하시고 작동 원리 학습하신 거 기반으로 진행하시면 큰 무리 없이 해당 미션을 진행할 수 있습니다.

외부 블로그를 보시면서 새로운 개념들을 학습하면 오히려 지금 불필요한 정보들도 써야될 것 같아서 혼동만 오는데 이 부분은 제가 나중에 다른 미션을 통해 점점 개선하는 방식으로 설명해드릴테니 지금까지 했던 내용 + 리뷰에서 언급했던 내용들로만 해결하시면 될 것 같습니다

2024-08-12 05:45 UTC, sosow0212 commented on study/lotto/8월3일.md
> +실질적인 데이터의 상태 변화 등의 처리는 도메인 계층에서 진행할 수 있도록 위임하는 것이 중요하다.
요게 중요합니다 지금은 서비스에 도메인 로직이 많이 노출되어있습니다!

2024-08-12 05:57 UTC, SEUNGBOONG commented on mission-lotto/src/main/java/com/lotto/lottoTicket/controller/LottoController.java
> +    @PostMapping("/setWinningNumbers")
넵 수정하겠습니다!

2024-08-16 10:38 UTC, sosow0212 requested changes
지난 미션 반영이 안되어있고, 전반적으로 잘못된 개행이라든지 메서드 순서 정렬 및 클래스 코드 정렬이 안 되어있습니다 ㅠ 확인해주시고 꼭 고쳐주세요!
그리고 클래스 마지막 개행 추가도 안되어있는데 나중에 프로젝트할 때 문제 생길 여지가 있어서 이번 리뷰에서 설정파일 수정 후 다 고치고 넘어가는 게 좋을 것 같습니다. 
하시다가 어려운 부분 있으면 연락주세요!

2024-08-16 10:38 UTC, sosow0212 commented on mission-lotto/build.gradle
> +    annotationProcessor 'org.projectlombok:lombok:1.18.24'
최신 버전으로 바꾼 이유가 궁금합니다~

2024-08-16 10:38 UTC, sosow0212 commented on mission-lotto/src/main/java/com/web/lotto/controller/LottoController.java
> +    }
Lombok을 사용하셨는데 @RequireArgs~ 어노테이션을 클래스 레벨로 달아도 될 것 같습니다

2024-08-16 10:38 UTC, sosow0212 commented on mission-lotto/src/main/java/com/web/lotto/controller/LottoController.java
> +
```suggestion
```

2024-08-16 10:38 UTC, sosow0212 commented on mission-lotto/src/main/java/com/web/lotto/controller/LottoController.java
> +    @PostMapping("/buying")
RESTful 참고하면 `POST /lottos`로도 충분하지 않을까요?
문서 참고하셔서 설계 규칙 한 번 찾아보시면 좋을 것 같아요 다른 부분도 마찬가지입니다!

2024-08-16 10:38 UTC, sosow0212 commented on mission-lotto/src/main/java/com/web/lotto/controller/LottoController.java
> +}
마지막 개행 문제가 아직도 전역적으로 해결이 되지 않았는데 협업하실 때 문제가 될 수 있을 것 같아요 설정 다시 확인해주세요

2024-08-16 10:38 UTC, sosow0212 commented on mission-lotto/src/main/java/com/web/lotto/controller/dto/LottoResponse.java
> +        , int winningMoney) {
```suggestion
        Long id,
        List<Integer> lottoTickets,
        List<Integer> winningLottoTicket,
        User user,
        int winningMoney
       ) {
```

2024-08-16 10:38 UTC, sosow0212 commented on mission-lotto/src/main/java/com/web/lotto/controller/message/SettingWinningNumbers.java
> +}
굳이 필요가 없는 클래스인 것 같습니다

2024-08-16 10:38 UTC, sosow0212 commented on mission-lotto/src/main/java/com/web/lotto/domain/entity/Lotto.java
> +@NoArgsConstructor
접근제어자 설정이 안되어있습니다! 적절한 것으로 해주세요
JPA에서 반드시 필요한 생성자는 무엇인지도 고민해보면 좋을 것 같습니다
몇 번 리뷰를 남긴 건데 다음 미션부터 신경써주세요 ㅠㅠ

2024-08-16 10:38 UTC, sosow0212 commented on mission-lotto/src/main/java/com/web/lotto/domain/entity/Lotto.java
> +public class Lotto {
테이블 네임을 다르게 한 이유를 모르겠습니다 ㅠ 다음에는 신경써주세요!

2024-08-16 10:38 UTC, sosow0212 commented on mission-lotto/src/main/java/com/web/lotto/domain/entity/Lotto.java
> +    @ElementCollection(fetch = FetchType.EAGER)
EAGER, LAZY 차이도 꼭 학습해주세요!

2024-08-16 10:38 UTC, sosow0212 commented on mission-lotto/src/main/java/com/web/lotto/domain/exception/NotSetWinningNumbers.java
> +public class NotSetWinningNumbers extends IllegalStateException{
```suggestion
public class NotSetWinningNumbers extends IllegalStateException {
```

CustomException에서 IllegalStateException을 상속하신 이유가 무엇인가요?
스프링 커스텀 예외에 대해 학습하고 수정해주세요!

2024-08-16 10:38 UTC, sosow0212 commented on mission-lotto/src/main/java/com/web/lotto/domain/repository/LottoRepository.java
> +public interface LottoRepository extends JpaRepository<Lotto, Long> {
이 부분도 지난 번에 리뷰에 남겼는데 JpaRepository 자체에 @Repository가 달려서 상속하면 빈도 그대로 받아옵니다
그래서 해당 클래스엔 @Repository가 필요없습니다 ㅠ

2024-08-16 10:38 UTC, sosow0212 commented on mission-lotto/src/main/java/com/web/lotto/domain/vo/GeneratorLotto.java
> +}
정렬 신경써주세요!

2024-08-16 10:38 UTC, sosow0212 commented on mission-lotto/src/main/java/com/web/lotto/domain/vo/LottoTicket.java
> +    }
```suggestion

    public LottoTicket(List<Integer> numbers, final RandomGeneratorLotto randomGeneratorLotto) {
        this.numbers = randomGeneratorLotto.generateRandomNumber();
    }
```

2024-08-16 10:38 UTC, sosow0212 commented on mission-lotto/src/main/java/com/web/lotto/domain/vo/WinningLottoCalculator.java
> +                .sum();
```suggestion
        return lotto.stream()
                .mapToInt(ticket -> {
                    int matchingCount = getMatchingCount(lotto);
                    LottoPrice prize = LottoPrice.getPrizeByCount(matchingCount);
                    return prize.getPrizeAmount() * calculateWinningCheckNumbers(lotto, allLottoTickets)
                            .getOrDefault(prize, 0L).intValue();
                })
                .sum();
```

2024-08-16 10:38 UTC, sosow0212 commented on mission-lotto/src/main/java/com/web/lotto/domain/vo/exception/BoundaryLottoNumberValueException.java
> +public class BoundaryLottoNumberValueException extends RuntimeException{
여기는 RuntimeException을 달아주셨네요! + 정렬 해주세요

2024-08-16 10:38 UTC, sosow0212 commented on mission-lotto/src/main/java/com/web/lotto/domain/vo/exception/BoundaryLottoNumberValueException.java
> +
```suggestion
```

2024-08-16 10:38 UTC, sosow0212 commented on mission-lotto/src/main/java/com/web/lotto/infrastructure/LottoPrice.java
> +    FIRST_PRIZE(6, 2000000),
```suggestion
public enum LottoPrice {

    FIRST_PRIZE(6, 2000000),
```

2024-08-16 10:38 UTC, sosow0212 commented on mission-lotto/src/main/java/com/web/lotto/service/LottoService.java
> +
```suggestion
```

2024-08-16 10:38 UTC, sosow0212 commented on mission-lotto/src/main/java/com/web/lotto/service/LottoService.java
> +public class LottoService {
메서드 순서 맞춰주세요!
A public -> A' private -> A'' private... --> B public -> B private ...

public 메서드에서 사용하는 메서드 순으로 쭉 변경해주세요

2024-08-16 10:38 UTC, sosow0212 commented on mission-lotto/src/main/java/com/web/lotto/service/LottoService.java
> +    }
이거 자체가 도메인 메서드 같습니다

member.buyLotto(...) 를 만들고
buyLotto 내에서 금액 처리와 예외처리를 모두 해주는게 맞을 것 같아요

지금은 캡슐화가 안 되어있습니다!

2024-08-16 10:38 UTC, sosow0212 commented on mission-lotto/src/main/java/com/web/lotto/service/LottoService.java
> +
여기도 그렇고 다른 클래스 모두 개행 신경써주세요!

2024-08-16 10:38 UTC, sosow0212 commented on mission-lotto/src/main/java/com/web/lotto/service/LottoService.java
> +        user.setLottoCount(lottoCount);
미션 요구사항인 setter 지양이 지켜지지 않고 있습니다.
도메인 로직이 외부로 전부 노출되어 있습니다 도메인 클래스를 통해서 해당 작업을 위임해주세요!

2024-08-16 10:38 UTC, sosow0212 commented on mission-lotto/src/main/java/com/web/lotto/service/LottoService.java
> +public class LottoService {
@Transactional 어노테이션도 빠져있습니다!

2024-08-16 10:38 UTC, sosow0212 commented on mission-lotto/src/main/java/com/web/lotto/service/LottoService.java
> +        userRepository.save(user);
이것도 트랜잭션이 있으면 save() 메서드가 없어도 jpa에서 알아서 저장해줍니다! 왜 그런지 꼭 찾아보세요

2024-08-16 10:38 UTC, sosow0212 commented on mission-lotto/src/main/java/com/web/lotto/service/LottoService.java
> +        }
이것도 클래스로 만들고 jpa saveAll(...) 을 통해 쿼리를 한 번에 날릴 수 있지 않을까요?
지금은 쿼리가 tickets.size() 만큼 발생하는 것 같습니다

2024-08-16 10:38 UTC, sosow0212 commented on mission-lotto/src/main/java/com/web/lotto/service/exception/InsufficientBalanceException.java
> +public class InsufficientBalanceException extends RuntimeException{
다른 곳도 전부 정렬해주세요!

2024-08-16 10:38 UTC, sosow0212 commented on mission-lotto/src/main/java/com/web/user/controller/UserController.java
> +
```suggestion
```

다른 곳도 신경써주세요!

2024-08-16 10:38 UTC, sosow0212 commented on mission-lotto/src/main/java/com/web/user/domain/entity/User.java
> +    private Lotto lotto;
지금 Lotto도 Member를 @ManyToOne으로 매핑하고
Member도 Lotto를 @ManyToOne으로 매핑하고 있습니다. 

1:1 매핑이라면 위에 매핑어노테이션은 잘못된 것 같고, 어떻게 매핑해야할지 고민해보면 좋을 것 같습니다.
이 부분 수정해주세요! 문제가 생기는 부분입니다

2024-08-16 10:38 UTC, sosow0212 commented on mission-lotto/src/main/java/com/web/user/service/UserService.java
> +                .lottoCount(0)
`기본 lottoCoun = 0 이다.` 라는 생성전략이 서비스로 노출되어 있습니다.
도메인 생성자 혹은 정팩메 만들어서 외부에서 쓰는 게 좋을 것 같고 0도 상수처리 해주세요!

2024-08-16 10:38 UTC, sosow0212 commented on mission-lotto/src/main/java/com/web/user/service/UserService.java
> +        validateBalanceException(balance);
이 부분도 밑에 Member의 생성자에 넣으면 blance 값이 뭔지 몰라도 Member 생성자 로직 내부에서 처리하면서 캡슐화를 할 수 있지 않을까요?

2024-08-16 10:38 UTC, sosow0212 commented on mission-lotto/src/test/java/com/web/lottoTicket/controller/LottoControllerTest.java
> +                        .value(5));
다음부턴 다른 필드들도 검증해주세요! 모든 필드를 검증해줘야합니다

2024-08-16 10:38 UTC, sosow0212 commented on mission-lotto/src/test/java/com/web/lottoTicket/controller/LottoControllerTest.java
> +                        .content("{\"winningNumbers\":[1,2,3,4,5,6]}"))
이것도 지난 리뷰에 남긴 것인데 ObjectMapper를 이용해서 직렬화/역직렬화를 수행해주세요

2024-08-16 10:38 UTC, sosow0212 commented on mission-lotto/src/test/java/com/web/lottoTicket/controller/LottoControllerTest.java
> +//        Mockito.when(lottoService.calculateTotalWinnings(lotto)).thenReturn(w);
```suggestion
```

2024-08-16 10:38 UTC, sosow0212 commented on mission-lotto/src/test/java/com/web/user/controller/UserControllerTest.java
> +        CreateUserRequest request = new CreateUserRequest(null, "Seungboong", 1000, 0);
null 값이 들어간다는 건 어딘가 문제가 있는 로직 같습니다. 다음부터는 생성자에 id를 빼거나 다른 방식으로 만들어주세요!

2024-08-16 10:38 UTC, sosow0212 commented on mission-lotto/src/test/java/com/web/user/domain/entity/UserTest.java
> +public class UserTest {
해당 도메인의 모든 기능 로직과 누락된 Lotto 도메인 테스트도 해주세요. 테스트가 진행되지 않고 리팩토링을 한다면 어디서 버그가 나는지 찾기가 너무 힘들어서 미리 해두시면 좋습니다!

2024-08-16 10:38 UTC, sosow0212 commented on mission-lotto/src/test/java/com/web/user/controller/UserControllerTest.java
> +public class UserControllerTest {
Service 레이어 테스트도 공부하셔서 다음 미션부터 적용해주세요!

2024-08-16 10:44 UTC, SEUNGBOONG commented on mission-lotto/build.gradle
> +    annotationProcessor 'org.projectlombok:lombok:1.18.24'
처음에 도메인 설계가 잘못된지 모르고,,  
찾아보니 롬복 최신버전 사용을 안해서 그럴수도있다해서 시도했었던 거였습니다ㅜ

2024-08-16 10:49 UTC, SEUNGBOONG commented on mission-lotto/build.gradle
> +    annotationProcessor 'org.projectlombok:lombok:1.18.24'
<img width="487" alt="스크린샷 2024-08-16 오후 7 48 26" src="https://github.com/user-attachments/assets/dd9570f3-c4bc-4e63-a86a-b8128fc96f25">
ㅜㅜ 아무리찾아봐도 이거 체크하는 거 . ㅅ같은데 항상 반영이안되는것 같네여 ..

2024-08-16 10:50 UTC, SEUNGBOONG commented on mission-lotto/src/main/java/com/web/lotto/controller/LottoController.java
> +    }
넵 확인후 수정하겠습니다.

2024-08-16 15:40 UTC, SEUNGBOONG commented on mission-lotto/src/main/java/com/web/lotto/controller/LottoController.java
> +    @PostMapping("/buying")
넵 내일 다시한번 정독해보겠습니다!

2024-08-17 00:58 UTC, SEUNGBOONG commented on mission-lotto/src/main/java/com/web/lotto/controller/LottoController.java
> +    }
@RequireArgsConstructor는 가장 권장하는 의존성 주입인 생성자 중비방식을 도와주는 역할일까요? 아니면 
그 자체 역할을 해주는 것일까요?  생성자 주입처럼 final 붙이는 게맞을까여

2024-08-17 02:06 UTC, SEUNGBOONG commented on mission-lotto/src/main/java/com/web/lotto/controller/LottoController.java
> +}
반영했습니다!

2024-08-17 02:25 UTC, SEUNGBOONG commented on mission-lotto/src/test/java/com/web/user/controller/UserControllerTest.java
> +public class UserControllerTest {
넵

2024-08-17 02:25 UTC, SEUNGBOONG commented on mission-lotto/src/test/java/com/web/user/domain/entity/UserTest.java
> +public class UserTest {
넵 감사합니다

2024-08-17 02:28 UTC, SEUNGBOONG commented on mission-lotto/src/test/java/com/web/lottoTicket/controller/LottoControllerTest.java
> +                        .content("{\"winningNumbers\":[1,2,3,4,5,6]}"))
적용해봤는데 .. 익숙하지가 않아서 잘했는지 의문입니다

2024-08-17 03:40 UTC, sosow0212 commented on mission-lotto/src/main/java/com/web/lotto/controller/LottoController.java
> +    }
이 부분은 답변 드릴 수 있지만 해당 어노테이션이 어떤 역할을 하는지, 어떤 변화를 만들어주는지 찾아보시면 금방 아실 수 있을 것 같습니다! 찾아봐도 어렵다면 말씀해주세요!

2024-08-17 07:50 UTC, sosow0212 approved these changes
아직 아쉬운 부분들이 남아있습니다
JPA 객체지향이 지켜지지 않는 부분도 있고, 직렬화/역직렬화에 대해 이해하지 못한 부분들도 보입니다 ㅠㅠ
이번 미션에서 서비스 레이어 @Transactional 어노테이션도 빠져있는데 이에 대한 이해와 JPA와 연관지어서도 고민해봐야하는데 잘 이뤄지지 못한 것 같아요.
시간이 너무 지체 돼서 Approve 하겠습니다! 키워드들에 대해 학습해보시고 나중에 다시 고쳐보도록 해요! 수고하셨습니다 👍

2024-08-17 07:50 UTC, sosow0212 commented on mission-lotto/src/main/java/com/web/lotto/controller/LottoController.java
> +@RequestMapping("/api/lotto")
기존처럼 lottos가 좋을 것 같아요 ㅎㅎ
`자원명사복수형/{자원id}` 이런식으로 쓰이니깐요

2024-08-17 07:50 UTC, sosow0212 commented on mission-lotto/src/main/java/com/web/lotto/controller/LottoController.java
> +    @PostMapping("/lottoTicket")
```suggestion
    @PostMapping
```

2024-08-17 07:50 UTC, sosow0212 commented on mission-lotto/src/main/java/com/web/lotto/controller/LottoController.java
> +    private LottoResponse expressingLottoResponse(final Lotto lotto) {
메서드는 동사형으로 만들어주세요

2024-08-17 07:50 UTC, sosow0212 commented on mission-lotto/src/main/java/com/web/lotto/controller/LottoController.java
>      }
요런거 굳이 나눌 필요는 없을 것 같아요 !

2024-08-17 07:50 UTC, sosow0212 commented on mission-lotto/src/main/java/com/web/lotto/controller/LottoController.java
> +        }
ObjectMapper를 현재 클래스에서 사용하신 이유가 있을까요?
직렬화 역직렬화가 지금은 되어 있고 테스트에서는 되질 않아서 사용하라고 말씀 드렸습니다!
직렬/역직렬화 개념에 대해 학습해보시면 좋을 것 같습니다

2024-08-17 07:50 UTC, sosow0212 commented on mission-lotto/src/main/java/com/web/lotto/infrastructure/RandomGeneratorLotto.java
>      }
return으로 반환을 해주는게 나중에 재사용하기에도 더 좋을 것 같아요 ㅠ

2024-08-17 07:50 UTC, sosow0212 commented on mission-lotto/src/main/java/com/web/user/controller/UserController.java
> +    private final ObjectMapper objectMapper;
굳이 여기서 필요하지 않아보입니다!

2024-08-17 07:50 UTC, sosow0212 commented on mission-lotto/src/main/java/com/web/user/controller/UserController.java
> +    private final ObjectMapper objectMapper;
objectMapper가 무엇인지 학습해보시고, 테스트에서 `\ id=3, \n pid =~~` 이런식으로 값 검증을 하시는데 이때 사용해주세요

2024-08-17 07:50 UTC, sosow0212 commented on mission-lotto/src/main/java/com/web/lotto/service/LottoService.java
>  public class LottoService {
Transactional이 아직도 빠져있습니다

2024-08-17 07:51 UTC, merged